// Azure Managed Grafana — Standard SKU with Azure Monitor access via RBAC

@description('Resource name prefix')
param resourcePrefix string

@description('Azure region')
param location string

@description('Resource tags')
param tags object

var grafanaName = '${resourcePrefix}-grafana'
var monitoringReaderRoleDefinitionId = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  '43d0d8ad-25c7-4714-9337-8ba259a9fe05' // Monitoring Reader
)

resource grafana 'Microsoft.Dashboard/grafana@2024-10-01' = {
  name: grafanaName
  location: location
  tags: tags
  identity: {
    type: 'SystemAssigned'
  }
  sku: {
    name: 'Standard'
  }
  properties: {
    apiKey: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    deterministicOutboundIP: 'Disabled'
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
  }
}

// Azure Monitor is exposed to Grafana through its managed identity RBAC.
resource grafanaMonitoringReader 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(resourceGroup().id, grafanaName, 'MonitoringReader')
  properties: {
    roleDefinitionId: monitoringReaderRoleDefinitionId
    principalId: grafana.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

@description('Managed Grafana resource name')
output grafanaName string = grafana.name

@description('Managed Grafana endpoint URL')
output grafanaEndpoint string = grafana.properties.endpoint

@description('Managed Grafana principal ID')
output grafanaPrincipalId string = grafana.identity.principalId
