-- 004_seed_siltgate.sql — Seed zone data for The Siltgate city zone.

-- ═══════════════════════════════════════════════════════════════
-- New item definitions
-- ═══════════════════════════════════════════════════════════════
INSERT INTO item_definitions (id, name, type, tier, base_stats, base_durability, weight, description, soulbound, stackable, max_stack, status) VALUES
  ('dockworker_hook', 'Dockworker''s Hook', 'weapon', 'common', '{"damage":9,"speed":1.1}', 40, 4, 'A curved iron hook mounted on a wooden handle, used to haul cargo. Just as effective at hauling flesh.', false, false, 1, 'published'),
  ('smugglers_dagger', 'Smuggler''s Dagger', 'weapon', 'common', '{"damage":11,"speed":1.3}', 45, 2, 'A slender blade with a blackened finish to prevent glinting in torchlight. Balanced for throwing.', false, false, 1, 'published'),
  ('fish_knife', 'Fish Knife', 'weapon', 'scrap', '{"damage":5,"speed":1.4}', 20, 1, 'A thin-bladed filleting knife, its edge still keen despite years of salt exposure.', false, false, 1, 'published'),
  ('leather_jerkin', 'Leather Jerkin', 'armour', 'common', '{"armour":4,"weight":6}', 45, 6, 'Stiff boiled leather, cut for mobility. Standard dock worker protection.', false, false, 1, 'published'),
  ('smugglers_cloak', 'Smuggler''s Cloak', 'armour', 'common', '{"armour":2,"weight":3}', 35, 3, 'A dark hooded cloak with hidden pockets sewn into the lining.', false, false, 1, 'published'),
  ('plague_mask', 'Plague Mask', 'armour', 'sturdy', '{"armour":1,"weight":2}', 50, 2, 'A beaked mask stuffed with dried herbs. Reduces the effect of toxic fumes.', false, false, 1, 'published'),
  ('city_map', 'City Map', 'material', 'common', '{}', NULL, 0.5, 'A folded parchment showing the streets of The Siltgate. Annotations in several hands suggest frequent revision.', false, false, 1, 'published'),
  ('sewer_lamp', 'Sewer Lamp', 'consumable', 'common', '{"duration":10}', NULL, 2, 'A shuttered brass lantern filled with rendered fat. Burns with a smoky, orange flame.', false, false, 1, 'published'),
  ('silk_scarf', 'Silk Scarf', 'material', 'common', '{}', NULL, 0.3, 'A length of dyed silk, still vivid despite its age. Merchants trade these as informal currency.', false, true, 10, 'published'),
  ('brass_compass', 'Brass Compass', 'material', 'sturdy', '{}', NULL, 0.5, 'A navigational compass with a cracked glass face. The needle still trembles toward north.', false, false, 1, 'published'),
  ('harbor_manifest', 'Harbor Manifest', 'material', 'common', '{}', NULL, 0.3, 'A water-stained shipping manifest listing cargo, destinations, and — interestingly — undeclared goods.', false, true, 10, 'published'),
  ('alley_thugs_coin', 'Alley Thug''s Coin', 'material', 'scrap', '{}', NULL, 0.1, 'A clipped copper coin, its edges filed to remove the mint mark. Untraceable currency of the slums.', false, true, 50, 'published'),
  ('dock_rope', 'Dock Rope', 'material', 'scrap', '{}', NULL, 1.5, 'A length of tarred hemp rope, frayed but still strong. Useful for binding or climbing.', false, true, 10, 'published'),
  ('noble_signet_ring', 'Noble Signet Ring', 'material', 'refined', '{}', NULL, 0.2, 'A gold ring bearing the crest of a Highwind family. Proof of status — or a useful forgery.', false, false, 1, 'published'),
  ('silt_venom_sac', 'Silt Venom Sac', 'material', 'common', '{}', NULL, 0.3, 'A translucent sac of pale green venom, extracted from a silt serpent. Alchemists value it highly.', false, true, 20, 'published'),
  ('serpent_scale', 'Serpent Scale', 'material', 'common', '{}', NULL, 0.2, 'An iridescent scale shed by a silt serpent. Hard as iron and surprisingly flexible.', false, true, 20, 'published'),
  ('harbourmaster_key', 'Harbourmaster''s Key', 'key', 'common', '{}', NULL, 0.3, 'A heavy brass key on a corroded chain. Opens the harbourmaster''s locked stores.', false, false, 1, 'published')
ON CONFLICT (id) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════
-- New creature definitions
-- ═══════════════════════════════════════════════════════════════
INSERT INTO creature_definitions (type, name, slug, description, max_hp, attack, defence, armour, agility, min_count, max_count, preferred_rooms, forbidden_rooms, idle_ticks_min, idle_ticks_max, flee_threshold, loot_table, status)
VALUES
  ('city_dog', 'City Dog', 'city_dog', 'A lean, wary mutt that haunts the market stalls, surviving on scraps and stolen fish. More bark than bite, unless cornered.', 12, 4, 1, 0, 5, 1, 2, '{corridor,junction}', '{boss}', 30, 60, 0.4, '[{"itemId":"rat_tail","dropWeight":30}]'::jsonb, 'published'),
  ('pigeon_flock', 'Pigeon Flock', 'pigeon_flock', 'A cloud of grimy urban pigeons, pecking at crumbs between the cobblestones. Harmless but aggressive when food is threatened.', 5, 1, 0, 0, 8, 1, 1, '{corridor,junction,entry}', '{boss,dead_end}', 20, 40, 0.8, '[]'::jsonb, 'published'),
  ('feral_dog', 'Feral Dog', 'feral_dog', 'A scarred, muscular dog gone wild. Its lips are permanently pulled back from yellowed fangs. Hunts in pairs.', 20, 7, 2, 1, 5, 1, 2, '{corridor,dead_end}', '{boss,entry}', 30, 60, 0.3, '[{"itemId":"rat_tail","dropWeight":20},{"itemId":"waterlogged_bone","dropWeight":30}]'::jsonb, 'published'),
  ('alley_thug', 'Alley Thug', 'alley_thug', 'A desperate figure wrapped in rags and leather scraps. Armed with a crude weapon and the courage of hunger.', 30, 9, 3, 2, 4, 1, 2, '{corridor,junction,dead_end}', '{entry,boss}', 40, 80, 0.2, '[{"itemId":"alley_thugs_coin","dropWeight":60},{"itemId":"smugglers_dagger","dropWeight":15},{"itemId":"leather_jerkin","dropWeight":10}]'::jsonb, 'published'),
  ('dockside_smuggler', 'Dockside Smuggler', 'dockside_smuggler', 'A cloaked figure with quick hands and quicker feet. Trades in contraband and violence in equal measure.', 40, 11, 4, 3, 6, 1, 2, '{dead_end,corridor}', '{entry,boss}', 50, 100, 0.2, '[{"itemId":"smugglers_dagger","dropWeight":30},{"itemId":"smugglers_cloak","dropWeight":20},{"itemId":"alley_thugs_coin","dropWeight":40}]'::jsonb, 'published'),
  ('silt_serpent', 'Silt Serpent', 'silt_serpent', 'A thick-bodied serpent adapted to the flooded sewers. Its scales shimmer with an oily iridescence and its bite delivers a numbing venom.', 35, 10, 3, 2, 7, 1, 2, '{corridor,dead_end}', '{entry,boss}', 40, 80, 0.25, '[{"itemId":"silt_venom_sac","dropWeight":50},{"itemId":"serpent_scale","dropWeight":40}]'::jsonb, 'published'),
  ('plague_bearer', 'Plague Bearer', 'plague_bearer', 'A shambling figure wrapped in stained bandages, its breath a visible miasma. Whether alive or dead is unclear — and irrelevant to its hostility.', 80, 14, 5, 4, 2, 1, 1, '{dead_end,boss}', '{entry,corridor}', 60, 120, 0.1, '[{"itemId":"plague_mask","dropWeight":25},{"itemId":"silt_venom_sac","dropWeight":30},{"itemId":"sewer_moss","dropWeight":40}]'::jsonb, 'published'),
  ('the_harbourmaster', 'The Harbourmaster', 'the_harbourmaster', 'A massive figure in a salt-crusted greatcoat, wielding a barbed anchor chain. Once the city''s port authority — now a territorial monster guarding its domain with inhuman strength.', 120, 16, 7, 8, 3, 1, 1, '{boss}', '{entry,corridor,dead_end,junction}', 80, 150, 0, '[{"itemId":"harbourmaster_key","dropWeight":100},{"itemId":"dockworker_hook","dropWeight":40},{"itemId":"brass_compass","dropWeight":30},{"itemId":"harbor_manifest","dropWeight":50}]'::jsonb, 'published')
ON CONFLICT (type) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════
-- Zone record
-- ═══════════════════════════════════════════════════════════════
INSERT INTO zones (id, slug, name, description, level_min, level_max, tier, theme, entry_room_slugs, lifecycle, category, max_players, pvp_enabled, repop_interval_seconds)
VALUES (gen_random_uuid(), 'the-siltgate', 'The Siltgate',
  'A sprawling port city built on the ruins of something older. Salt wind, tar smoke, and the clamor of commerce fill the air. Social strata are evident from the gleaming promenades above to the drowned sewers below.',
  1, 100, 1, 'urban', '{market-square}', 'persistent', 'city', 0, false, 0);

-- ═══════════════════════════════════════════════════════════════
-- Rooms (136 rooms across 7 quarters)
-- ═══════════════════════════════════════════════════════════════
INSERT INTO zone_rooms (zone_id, slug, name, description, type, properties, npcs, loot_containers, hazards)
SELECT z.id, v.slug, v.name, v.description, v.type,
       v.properties::text[], v.npcs::jsonb, v.loot_containers::jsonb, v.hazards::jsonb
FROM zones z, (VALUES

  -- Market Square (10 rooms)
  ('market-square',
   'Market Square',
   'The beating heart of The Siltgate spreads before you, a cacophony of hawkers, haggling merchants, and milling crowds. Stalls draped in coloured canvas jostle for space on worn flagstones stained by a thousand spilled cargoes. The mingled scent of cardamom, brine, and fresh leather hangs in the salt wind.',
   'entry',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('city-gate',
   'City Gate',
   'Massive iron-banded oak doors stand open beneath a stone archway scarred by siege marks long weathered smooth. Guards in tarnished half-plate lean on polearms, eyes tracking every newcomer. Beyond the threshold the road dissolves into dust and silence.',
   'entrance',
   '{heavy_door}',
   '[]',
   '[]',
   '[]'),
  ('bazaar-row-1',
   'Bazaar Row',
   'A corridor of rickety market stalls stretches eastward, their awnings bleached by salt and sun. Vendors cry their wares over the flutter of startled pigeons pecking at grain spills. The air tastes of cumin and wood smoke.',
   'corridor',
   '{}',
   '[{"creatureId": "pigeon_flock", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('bazaar-row-2',
   'Bazaar Row',
   'Canvas tarps sag overhead, creating a patchwork tunnel of diffused light and shadow. Crates of unclaimed cargo line the walkway, their shipping marks half-scrubbed. The reek of overripe fruit mingles with the sharper tang of lamp oil.',
   'corridor',
   '{}',
   '[]',
   '[{"id": "bazaar-crate-1", "type": "crate", "items": ["silk_scarf", "harbor_manifest"]}]',
   '[]'),
  ('bazaar-row-3',
   'Bazaar Row',
   'The eastern end of the bazaar thins to a narrow gauntlet of competing stalls. A lean dog weaves between the legs of shoppers, nosing at fallen scraps. Underfoot, the cobbles are slick with fish scales and crushed herbs.',
   'corridor',
   '{}',
   '[{"creatureId": "city_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('fountain-plaza',
   'Fountain Plaza',
   'A verdigrised bronze fountain dominates this open square, its basins green with algae and bright with tossed copper coins. Pigeons strut along the rim, untroubled by the crowd. Side streets radiate outward like spokes from this civic hub.',
   'junction',
   '{}',
   '[{"creatureId": "pigeon_flock", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('tavern-row',
   'Tavern Row',
   'A row of drinking establishments shoulder one another along this cramped lane, their signs creaking in the harbour breeze. Spilled ale darkens the cobbles and the sound of competing lute-players clashes in the doorways. The smell of roasting meat drifts from somewhere above.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('money-changers-row',
   'Money-Changers'' Row',
   'Small counting-houses with barred windows crowd this cul-de-sac, their shutters latched tight against thieves. The clink of coin on coin provides a constant metallic undertone. An iron strongbox bolted to the wall bears fresh scratches around its lock.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "moneychanger-lockbox-1", "type": "chest", "items": ["alley_thugs_coin", "alley_thugs_coin"]}]',
   '[]'),
  ('scribe-corner',
   'Scribe''s Corner',
   'Ink-stained desks cluster beneath a sagging awning where scribes copy documents by lamplight, squinting at faded originals. Quills scratch on parchment in quiet industry. A shelf of rolled maps and shipping manifests leans against the wall, available for a price.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "scribe-desk-1", "type": "crate", "items": ["city_map", "harbor_manifest"]}]',
   '[]'),
  ('news-board',
   'The News Board',
   'A large cork-and-timber board stands nailed to the wall, layered thick with postings — bounties, warnings, trade notices, and desperate pleas. Wax seals and iron tacks hold the chaos in place. A small crowd gathers to read the latest proclamations.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),

  -- Silver Arcade (18 rooms)
  ('silver-arcade-1',
   'Silver Arcade',
   'Polished limestone flags stretch beneath an arcade of carved pillars, their capitals depicting merchant galleons and weighing scales. Hanging lanterns of blue glass cast cool light across the promenade. A wiry dog trots purposefully between the columns, collar jingling.',
   'corridor',
   '{}',
   '[{"creatureId": "city_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('silver-arcade-2',
   'Silver Arcade',
   'The arcade widens here, its vaulted ceiling painted with faded murals of trade routes and distant ports. Boot heels click sharply on the clean stone. The scent of cedar polish and new leather drifts from the workshops lining the passage.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('silver-arcade-3',
   'Silver Arcade',
   'Ironwork brackets support oil lamps that illuminate display windows showcasing fine metalwork and bolts of dyed cloth. Pigeons roost in the eaves above, their cooing a soft counterpoint to the clink of commerce. The stone underfoot is grooved with centuries of cart traffic.',
   'corridor',
   '{}',
   '[{"creatureId": "pigeon_flock", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('silver-arcade-4',
   'Silver Arcade',
   'The eastern terminus of the arcade opens onto a small courtyard where delivery carts queue. Apprentices in leather aprons hurry between workshops, arms laden with parcels. A brass sundial on a plinth marks the hour, its shadow creeping across pale stone.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('cobblestone-street-1',
   'Cobblestone Street',
   'Rounded cobbles fitted with artisan precision line this cross-street, their surfaces polished to a dull sheen by generations of foot traffic. Shopfronts with leaded-glass windows display their wares in orderly arrangements. The air smells faintly of sandalwood and money.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('cobblestone-street-2',
   'Cobblestone Street',
   'A mossy gutter runs down the centre of this well-maintained lane, carrying rainwater toward hidden drains. A lean dog noses at a discarded meat pie near a wrought-iron bench. Flower boxes on upper windows add unexpected colour to the stone facades.',
   'corridor',
   '{}',
   '[{"creatureId": "city_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('cobblestone-street-3',
   'Cobblestone Street',
   'This stretch of cobblestone curves gently southward, flanked by the taller buildings of the merchant quarter. Shuttered windows above suggest living quarters, and a child peers down from behind lace curtains. The distant clang of a smith''s hammer rings from a side street.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('narrow-alley-1',
   'Narrow Alley',
   'A slender passage cuts between two merchant halls, its walls close enough to touch with outstretched arms. Delivery ropes hang overhead, strung between upper floors. It smells of damp plaster and the faintest trace of perfume from a nearby shop.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('narrow-alley-2',
   'Narrow Alley',
   'Refuse collects in the corners of this thin alley where the street-sweepers rarely venture. A heap of discarded packing straw and broken crates provides shelter for scurrying things. The walls are scrawled with chalk tallies — someone''s running count of debts.',
   'corridor',
   '{}',
   '[]',
   '[{"id": "alley-refuse-1", "type": "crate", "items": ["rat_tail"]}]',
   '[]'),
  ('guild-hall',
   'Guild Hall',
   'A broad chamber behind heavy oak doors serves as the meeting place for the city''s trade guilds. Banner-hung walls bear the sigils of a dozen professions, and a long table dominates the centre, its surface scarred by heated negotiation. A stairway in the corner spirals downward into darkness.',
   'junction',
   '{heavy_door}',
   '[]',
   '[]',
   '[]'),
  ('jewelers-lane',
   'Jeweler''s Lane',
   'Display cases of thick glass and iron line this dead-end passage, their contents glittering under focused lamplight. The jewelers here work in guarded silence, their eyes flicking up at every footstep. Velvet-lined trays hold rings, chains, and stones of suspect provenance.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "jeweler-case-1", "type": "chest", "items": ["noble_signet_ring", "tarnished_medallion"]}]',
   '[]'),
  ('cloth-merchants-hall',
   'Cloth Merchant''s Hall',
   'Bolts of fabric in every hue stand in tall racks from floor to ceiling, filling the room with a fibrous warmth. The air is thick with the scent of dye and sizing. A measuring table dominates the centre, its brass yardstick nailed firmly in place.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "cloth-bolt-1", "type": "crate", "items": ["silk_scarf"]}]',
   '[]'),
  ('glassblowers-workshop',
   'Glassblower''s Workshop',
   'Heat rolls from a glowing furnace in waves, distorting the air. Rods of molten glass cool in iron cradles, and shelves display finished work — bottles, lenses, decorative baubles. Flakes of ash drift from the chimney, and the stone floor is warm underfoot.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[{"type": "open_flame", "severity": 0.2}]'),
  ('apothecary',
   'The Apothecary',
   'Dried herbs hang in bundles from ceiling hooks, their mingled fragrances creating a dense, medicinal fog. Shelves of labelled jars contain powders, tinctures, and things that float in cloudy liquid. A brass scale sits on the counter, one pan weighted with a lead standard.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "apothecary-shelf-1", "type": "crate", "items": ["healing_draught", "stamina_tonic"]}]',
   '[]'),
  ('merchant-inn',
   'The Merchant''s Inn',
   'Clean rushes cover the floor of this respectable establishment, and the smell of beeswax candles overwhelms the usual city stink. A staircase leads to private rooms above, and a serving counter offers wine and cold meats. Ledgers lie open by the door, tracking guests and their trades.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('wine-merchants-cellar',
   'Wine Merchant''s Cellar',
   'Stone steps descend into a cool, vaulted cellar lined with oak casks and dusty bottles. The air is heavy with tannin and the sweetness of aging grape. A tasting table bears several uncorked bottles, their contents catching the lamplight like dark jewels.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('pawn-shop',
   'Pawn Shop',
   'A cramped room heaped with the detritus of broken fortunes — dented helmets, tarnished brooches, chipped blades. The proprietor''s counter is caged in iron mesh, and a ledger of unredeemed pledges lies open. Everything here has a story; none of them end well.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "pawn-bin-1", "type": "crate", "items": ["tarnished_medallion", "corroded_pipe"]}]',
   '[]'),
  ('silk-road',
   'Silk Road',
   'A narrow alcove screened by hanging silks in layered colours, each bolt more vivid than the last. The fabric whispers against itself in the draft. Merchants here deal in textiles traded from ports across the known seas, and prices are whispered, never shouted.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "silk-bundle-1", "type": "crate", "items": ["silk_scarf", "silk_scarf"]}]',
   '[]'),

  -- Highwind Estates (16 rooms)
  ('estate-gate',
   'Estate Gate',
   'Wrought-iron gates worked in the pattern of wind-blown leaves guard the ascent to the Highwind Estates. Stone griffins crouch atop the gateposts, their features softened by salt erosion. Beyond, a flagstone path climbs through a world visibly cleaner than the city below.',
   'entrance',
   '{heavy_door}',
   '[]',
   '[]',
   '[]'),
  ('promenade-walk-1',
   'Promenade Walk',
   'A wide promenade of pale marble stretches along the elevated terrace, offering views over the rooftops of the market quarter. Iron railings ornate with scrollwork line the outer edge. Pigeons preen on the balustrade, and the air here carries the scent of jasmine from nearby planters.',
   'corridor',
   '{}',
   '[{"creatureId": "pigeon_flock", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('promenade-walk-2',
   'Promenade Walk',
   'Gas lamps on slender poles illuminate this stretch of the promenade, their mantles glowing even in daylight. Ornamental trees in stone planters provide dappled shade. The sound of the city below is muted to a comfortable murmur.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('promenade-walk-3',
   'Promenade Walk',
   'A section of the promenade where the railing bows outward to form a semicircular overlook. A well-groomed dog pads along beside an invisible master. The breeze is stronger here, carrying the tang of the harbour far below.',
   'corridor',
   '{}',
   '[{"creatureId": "city_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('promenade-walk-4',
   'Promenade Walk',
   'The promenade narrows as it approaches the eastern wing of the estates, the marble giving way to fitted granite. Ivy climbs the walls on either side, and a locked service door is nearly invisible beneath the foliage. Footsteps echo crisply in the confined space.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('courtyard-fountain',
   'Courtyard Fountain',
   'A private courtyard centres on a three-tiered fountain of white stone, its water running clear and bright. Topiary hedges shaped into geometric forms surround the basin. Pigeons bathe in the lowest tier, sending tiny arcs of water into the sunlight.',
   'junction',
   '{}',
   '[{"creatureId": "pigeon_flock", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('garden-terrace',
   'Garden Terrace',
   'Terraced beds of herbs and flowering shrubs step downward from a stone retaining wall, filling the air with the scent of lavender and rosemary. Gravel paths wind between the plantings. A stone bench offers a view across the rooftops to the harbour.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('observatory',
   'The Observatory',
   'A circular room at the top of a short tower, its domed ceiling painted with a star chart. A brass telescope on a pivoting mount points toward the harbour mouth. Charts and maps cover the desk, weighted down with polished stones and a cracked compass.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "observatory-desk-1", "type": "crate", "items": ["city_map", "brass_compass"]}]',
   '[]'),
  ('noble-residence-1',
   'Noble Residence',
   'Behind a heavy oak door, a vestibule opens into understated wealth — marble tile, gilt-framed portraits, and the smell of aged wood and beeswax. A coat of arms hangs above the inner archway, its motto illegible with age. The silence here is the kind that money buys.',
   'dead_end',
   '{heavy_door}',
   '[]',
   '[{"id": "noble-chest-1", "type": "chest", "items": ["noble_signet_ring", "silk_scarf"]}]',
   '[]'),
  ('noble-residence-2',
   'Noble Residence',
   'A second noble house, its entrance hall more austere than its neighbour, with bare stone walls hung with old weapons and hunting trophies. A threadbare carpet runs the length of the hall, suggesting former glory now in gentle decline. Cold drafts seep from the upper floors.',
   'dead_end',
   '{heavy_door}',
   '[]',
   '[]',
   '[]'),
  ('library-entrance',
   'Library Entrance',
   'Tall shelves of dark wood frame the entrance to the estates'' modest library, their contents ranging from navigational treatises to bound collections of city edicts. The smell of old paper and leather binding hangs thick. A reading lectern stands by the window, bathed in pale light.',
   'dead_end',
   '{}',
   '[]',
   '[{"id": "library-shelf-1", "type": "crate", "items": ["city_map", "harbor_manifest"]}]',
   '[]'),
  ('iron-balcony-1',
   'Iron Balcony',
   'A narrow iron-grated walkway extends along the outer wall of the estates, suspended over the rooftops below. The grating vibrates with each step, and the view is vertiginous. Salt wind buffets anyone who pauses here too long.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('iron-balcony-2',
   'Iron Balcony',
   'The balcony continues westward, curving to follow the contour of the building. Rust blooms at the joins of the iron plates, and one section of railing has been replaced with rope. A nest of some large bird clings to the underside of the overhang.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('servants-passage',
   'Servants'' Passage',
   'A plain corridor of whitewashed stone, unadorned and utilitarian. Hooks on the walls hold aprons and work gloves. The passage connects the public rooms to the kitchens and service areas, and the smell of boiling laundry drifts from somewhere ahead.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('belvedere',
   'The Belvedere',
   'An open-air pavilion at the highest point of the estates, its roof supported by fluted columns. From here the entire city unfolds — market stalls, dock cranes, the dark smudge of the slums, and the glittering sea beyond. The wind up here is constant and clean.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  ('highwind-bridge',
   'Highwind Bridge',
   'An arched stone bridge spans the gap between two wings of the estates, its sides lined with planter boxes trailing vines. The bridge sways perceptibly in strong wind. Looking down through the drainage slots reveals the streets far below, tiny figures moving through the haze.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),

  -- Dockward (22 rooms)
  ('dock-street-1',
   'Dock Street',
   'Tar-blackened planks replace cobblestones as the city gives way to the docks. The air thickens with brine, fish, and the creosote smell of preserved timber. A lean dog skulks between coiled ropes and stacked barrels, growling at strangers.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "city_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('dock-street-2',
   'Dock Street',
   'Barrel hoops and broken crate slats litter the margins of this dock road. A salt-crusted winch juts from a loading platform, its chain hanging slack over the quayside. The clang of ship bells carries from the waterfront.',
   'corridor',
   '{pvp}',
   '[]',
   '[{"id": "dock-barrel-1", "type": "crate", "items": ["dock_rope", "corroded_pipe"]}]',
   '[]'),
  ('dock-street-3',
   'Dock Street',
   'The street sags underfoot where the timbers have rotted beneath, each step producing a wet creak. A scarred dog with matted fur watches from beneath an overturned hull. The stench of bilge water and spoiled cargo is overpowering here.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('dock-street-4',
   'Dock Street',
   'Warehouse walls crowd this section of the dock road, their iron-bolted doors marked with shipping company sigils. Pulleys dangle from upper loading bays, ropes swaying in the harbour wind. Chalk marks on the cobbles indicate recent cargo deliveries.',
   'corridor',
   '{pvp}',
   '[]',
   '[]',
   '[]'),
  ('dock-street-5',
   'Dock Street',
   'The southernmost stretch of dock road, where legitimate commerce begins to shade into something less respectable. Lookouts lounge in doorways, and conversations halt as strangers pass. A figure in rough leathers fingers a blade hilt without pretending otherwise.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "alley_thug", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('fish-market',
   'Fish Market',
   'An open-sided market hall where the day''s catch is laid out on beds of crushed ice and seaweed. Scales glitter under the harsh light and blood drains into channels cut in the stone floor. The clamour of competitive bidding battles the screaming of gulls.',
   'junction',
   '{pvp}',
   '[{"creatureId": "pigeon_flock", "spawnCount": 1}]',
   '[{"id": "fish-crate-1", "type": "crate", "items": ["fish_knife", "dock_rope"]}]',
   '[]'),
  ('barnacled-quay',
   'Barnacled Quay',
   'The quay''s stone surface is encrusted with barnacles and dried kelp below the high-water mark, and slippery even above it. Iron bollards trail mooring lines into the murky harbour. Standing water collects in the depressions, green with algae.',
   'corridor',
   '{pvp}',
   '[]',
   '[]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('rope-walk',
   'Rope Walk',
   'A long, narrow stretch of quayside where rope-makers once twisted hemp into ships'' cable. Coils of rope in various stages of decay hang from wall-mounted hooks. A scarred dog with a dockworker''s temperament patrols the area, teeth bared.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('warehouse-1',
   'Warehouse',
   'A cavernous storage space behind a reinforced door, its interior divided by rows of wooden shelving stacked with unmarked crates. The air is stale and thick with dust. Rough voices echo from the shadows, and the scrape of heavy boots on stone warns of company.',
   'dead_end',
   '{pvp,heavy_door}',
   '[{"creatureId": "alley_thug", "spawnCount": 2}]',
   '[{"id": "warehouse-crate-1", "type": "crate", "items": ["dock_rope", "corroded_pipe", "dockworker_hook"]}]',
   '[]'),
  ('warehouse-2',
   'Warehouse',
   'Smaller than its neighbour, this warehouse smells of damp canvas and mildew. Shipping manifests are nailed to posts beside their corresponding cargo stacks. Water stains on the walls suggest the harbour has claimed this space more than once.',
   'dead_end',
   '{pvp,heavy_door}',
   '[]',
   '[{"id": "warehouse-crate-2", "type": "crate", "items": ["harbor_manifest", "dock_rope"]}]',
   '[]'),
  ('warehouse-3',
   'Warehouse',
   'The most secluded of the dock warehouses, tucked behind the others and accessible only through a narrow passage. Fresh scratches on the lock suggest frequent use at odd hours. Inside, crates bear no markings, and the contents are wrapped in oilcloth against prying eyes.',
   'dead_end',
   '{pvp,heavy_door}',
   '[{"creatureId": "dockside_smuggler", "spawnCount": 1}]',
   '[{"id": "warehouse-crate-3", "type": "crate", "items": ["smugglers_dagger", "smugglers_cloak"]}]',
   '[]'),
  ('pier-1',
   'Pier',
   'Weathered timbers extend over the dark harbour water, their pilings encrusted with mussels and green weed. The planks are slippery with spray, and gaps between them reveal the swell below. Mooring cleats protrude at intervals, some trailing frayed rope into the tide.',
   'dead_end',
   '{pvp,water}',
   '[]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('pier-2',
   'Pier',
   'A shorter pier jutting at an angle from the quay, its far end partially collapsed into the water. A feral dog has claimed the dry section as its territory, snarling at approach. The remaining planks groan under any weight.',
   'dead_end',
   '{pvp,water}',
   '[{"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('pier-3',
   'Pier',
   'The longest of the harbour piers, reaching far enough out for deeper-draught vessels. A supply crate sits near the end, left behind or deliberately cached. Waves slap against the pilings with a rhythmic boom, and the wood is perpetually wet.',
   'dead_end',
   '{pvp,water}',
   '[]',
   '[{"id": "pier-crate-1", "type": "crate", "items": ["dock_rope", "fish_knife"]}]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('chandlers-shop',
   'Chandler''s Shop',
   'A cramped shop crammed with maritime supplies — lanterns, rope, pitch, canvas, and tin cups. Everything is coated in a thin film of salt. The proprietor is absent, but a handwritten price list is nailed to the doorframe.',
   'dead_end',
   '{pvp}',
   '[]',
   '[{"id": "chandler-shelf-1", "type": "crate", "items": ["sewer_lamp", "dock_rope"]}]',
   '[]'),
  ('sailmakers-loft',
   'Sailmaker''s Loft',
   'An upper-floor workshop reached by an exterior staircase, its wide doors open to the harbour wind. Half-finished sails spread across the floor like fallen clouds, their edges weighted with iron bars. The smell of canvas and linseed oil fills the space.',
   'dead_end',
   '{pvp}',
   '[]',
   '[]',
   '[]'),
  ('dry-dock',
   'Dry Dock',
   'A rectangular basin cut into the quayside, its massive timber gates holding back the harbour. The hull of a half-repaired vessel sits propped on blocks, its keel exposed and copper-sheathed. Tools and materials are scattered across the work platform.',
   'dead_end',
   '{pvp}',
   '[]',
   '[{"id": "drydock-crate-1", "type": "crate", "items": ["dockworker_hook", "corroded_pipe"]}]',
   '[]'),
  ('smugglers-cove',
   'Smuggler''s Cove',
   'A hidden inlet beneath the harbour wall, accessible only through a concealed passage. Oilskin-wrapped bundles are stacked against the damp rock, and a shallow-draught boat bobs on a short painter. Two cloaked figures guard the cache with drawn blades and hostile stares.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "dockside_smuggler", "spawnCount": 2}]',
   '[{"id": "smuggler-stash-1", "type": "chest", "items": ["smugglers_dagger", "smugglers_cloak", "alley_thugs_coin"]}]',
   '[]'),
  ('tide-gate',
   'Tide Gate',
   'An ancient gate of rusted iron and barnacled stone controls the flow between the harbour and the lower waterways. The mechanism groans when operated, and seawater seeps through the gaps regardless. The smell of brine and decay rises from below, and steps descend into darkness.',
   'entrance',
   '{pvp,heavy_door,water}',
   '[]',
   '[]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('tar-pit',
   'Tar Pit',
   'A sunken yard where bubbling pitch is heated in iron cauldrons for caulking hulls. The fumes are acrid and eye-watering, rising in oily black wisps. The ground is tacky underfoot, and discarded brushes have fused to the stone.',
   'dead_end',
   '{pvp}',
   '[]',
   '[]',
   '[{"type": "toxic_fumes", "severity": 0.3}]'),
  ('dockside-tavern',
   'Dockside Tavern',
   'A low-ceilinged drinking hole built from salvaged ship timbers, its walls decorated with carved figureheads and tattered ensigns. The ale is cheap and the clientele cheaper. Sawdust on the floor absorbs whatever gets spilled, and much gets spilled.',
   'dead_end',
   '{pvp}',
   '[]',
   '[]',
   '[]'),
  ('harbourmasters-office',
   'Harbourmaster''s Office',
   'A fortified stone building overlooking the quay, its windows barred and its door reinforced with iron strapping. Inside, navigational charts paper the walls and a massive desk dominates the room. The harbourmaster is here — massive, territorial, and no longer entirely human.',
   'boss',
   '{pvp,heavy_door}',
   '[{"creatureId": "the_harbourmaster", "spawnCount": 1}]',
   '[{"id": "harbourmaster-desk-1", "type": "chest", "items": ["harbourmaster_key", "harbor_manifest", "brass_compass"]}]',
   '[]'),

  -- Beggar's Span (22 rooms)
  ('span-gate',
   'Span Gate',
   'A gap in a crumbling wall serves as the unofficial border between civilisation and destitution. No guards stand here — nobody wants the post. Beyond, the streets narrow and the buildings sag, and the air takes on the sour reek of poverty.',
   'entrance',
   '{pvp}',
   '[]',
   '[]',
   '[]'),
  ('beggars-lane-1',
   'Beggar''s Lane',
   'A muddy track between leaning tenements, its surface churned to brown paste by countless shuffling feet. Rats scurry brazenly across the path. Ragged figures huddle in doorways, watching with hollow eyes.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[]',
   '[]'),
  ('beggars-lane-2',
   'Beggar''s Lane',
   'The lane deepens here, running between buildings that have settled unevenly into the soft ground. A feral dog gnaws something unidentifiable in a patch of wan light. Washing lines overhead drip grey water onto the heads of passers-by.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('beggars-lane-3',
   'Beggar''s Lane',
   'The easternmost reach of the lane, where it dead-ends against a wall of collapsed masonry. Rats swarm around a cracked drain, emboldened by numbers. The stench of refuse is thick enough to taste.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 3}]',
   '[]',
   '[]'),
  ('narrow-alley-3',
   'Narrow Alley',
   'A tight passage between crumbling walls, barely wide enough for two abreast. Rats nest in the gaps between bricks, their eyes glinting in the dimness. Overhead, rotting beams bridge the gap, remnants of an upper floor that has long since fallen.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[]',
   '[]'),
  ('narrow-alley-4',
   'Narrow Alley',
   'The alley bends sharply here, creating a blind corner that locals avoid after dark. A corpse in rags slumps against the wall, pockets already turned out. Whether death came by blade or hunger is impossible to tell.',
   'corridor',
   '{pvp}',
   '[]',
   '[{"id": "alley-corpse-2", "type": "corpse", "items": ["alley_thugs_coin", "rat_tail"]}]',
   '[]'),
  ('narrow-alley-5',
   'Narrow Alley',
   'Deeper into the slums, where even the rats grow bolder. A figure in a ragged hood presses flat against the wall as you pass, one hand hidden. The cobbles here are cracked and tilted, creating ankle-breaking traps in the poor light.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "alley_thug", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('narrow-alley-6',
   'Narrow Alley',
   'This stretch of alley runs along the back of a collapsed tenement, its wall bulging outward at a worrying angle. Rats pour from a gap in the foundations in a constant trickle. The smell of mould and wet rot is inescapable.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[]',
   '[]'),
  ('narrow-alley-7',
   'Narrow Alley',
   'Rubble from a partial collapse narrows this already claustrophobic passage to a squeeze. Dust motes float in the single shaft of light penetrating from above. The stones underfoot shift unpredictably, threatening to give way.',
   'corridor',
   '{pvp}',
   '[]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.2}]'),
  ('narrow-alley-8',
   'Narrow Alley',
   'The alley opens slightly where a building has been reduced to its foundations, creating a small clearing of broken stone. A feral dog has made its den in the rubble, teeth bared at any intrusion. Scratch marks on the walls suggest desperate climbing.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('lean-to-camp',
   'Lean-To Camp',
   'A cluster of shelters cobbled together from salvaged wood, canvas, and flattened tin. Small fires smoulder in improvised pits, and the inhabitants eye strangers with a mix of fear and calculation. Rats bold enough to steal from the living skitter between the shelters.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 3}]',
   '[{"id": "camp-sack-1", "type": "crate", "items": ["rat_tail", "bent_rebar"]}]',
   '[]'),
  ('rat-run-1',
   'Rat Run',
   'A low, narrow passage that runs beneath a collapsed upper storey, forcing anyone taller than a child to stoop. Rats flood through in waves, their claws clicking on damp stone. The smell is biological and terrible.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 3}]',
   '[]',
   '[]'),
  ('rat-run-2',
   'Rat Run',
   'The passage opens into a wider space where multiple rat tunnels converge. Gnawed bones and torn fabric litter the floor. A lean feral dog disputes territory with the rat packs, lunging and snapping in bursts of sudden violence.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}, {"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('flophouse',
   'The Flophouse',
   'A roofless shell of a building where straw pallets line the walls in desperate rows. The inhabitants pay in scraps for the privilege of sleeping somewhere marginally safer than the open street. A thug in the corner collects the toll with a meaningful display of steel.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "alley_thug", "spawnCount": 1}]',
   '[{"id": "flophouse-mattress-1", "type": "crate", "items": ["alley_thugs_coin", "scavenger_shiv"]}]',
   '[]'),
  ('broken-bridge',
   'Broken Bridge',
   'The remnant of a stone footbridge spans nothing, its far end sheared away and dropping into a rubble-filled void. The remaining arch sags visibly. A makeshift railing of rope and sticks does little to prevent the unwary from a fatal step.',
   'dead_end',
   '{pvp}',
   '[]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.4}]'),
  ('gutter-drain',
   'Gutter Drain',
   'A wide iron grate set into the muddy ground funnels the slum''s runoff into the sewers below. The water that collects here is grey and foul, ankle-deep in the rainy season. Rats crowd the grate''s edges, slipping through the bars and back again. A gap in the ironwork is large enough to descend through.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('thieves-den',
   'Thieves'' Den',
   'A concealed room behind a false wall, its entrance disguised as a pile of refuse. Inside, stolen goods are sorted on rough tables under hooded lamplight. Armed figures watch the single entrance with the professional wariness of those who cannot afford to be surprised.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "alley_thug", "spawnCount": 2}]',
   '[{"id": "thieves-stash-1", "type": "chest", "items": ["smugglers_dagger", "smugglers_cloak", "alley_thugs_coin"]}]',
   '[]'),
  ('mud-flat',
   'Mud Flat',
   'The ground gives way to sucking grey mud where the slum''s drainage pools before creeping toward the harbour. A feral dog picks its way across, legs caked to the haunch. Each step produces a wet, reluctant sound, and the mud smells of salt and sewage.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('ruined-tenement-1',
   'Ruined Tenement',
   'The shell of a three-storey tenement, its upper floors caved in and its ground level filled with rubble. Rats nest in the debris, and something larger has scratched territorial marks on the remaining doorframe. Corroded pipes jut from the walls like broken bones.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[{"id": "tenement-rubble-1", "type": "crate", "items": ["corroded_pipe", "rat_tail"]}]',
   '[{"type": "unstable_rubble", "severity": 0.3}]'),
  ('ruined-tenement-2',
   'Ruined Tenement',
   'Another gutted building, this one blackened by an old fire. Charred beams lean at angles across the interior, and ash still coats every surface. A feral dog growls from the shadows of what was once a hearth. The walls creak ominously in the wind.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.3}]'),
  ('pawn-alley',
   'Pawn Alley',
   'A narrow lane where the desperate trade whatever they have left for a few more hours of survival. Items of dubious origin are displayed on blankets spread across the mud. A tarnished medallion catches the dim light, its chain still warm from its previous owner.',
   'corridor',
   '{pvp}',
   '[]',
   '[{"id": "pawn-refuse-1", "type": "crate", "items": ["tarnished_medallion", "rat_tail"]}]',
   '[]'),
  ('beggar-kings-court',
   'Beggar King''s Court',
   'A wider space amid the ruins, cleared and claimed by the slum''s self-appointed sovereign. A throne of scavenged furniture sits on a platform of stacked pallets. Armed thugs and snarling dogs form a court of sorts, their loyalty purchased with scraps of power and protection.',
   'junction',
   '{pvp}',
   '[{"creatureId": "alley_thug", "spawnCount": 2}, {"creatureId": "feral_dog", "spawnCount": 1}]',
   '[{"id": "beggar-throne-1", "type": "chest", "items": ["smugglers_cloak", "alley_thugs_coin", "alley_thugs_coin"]}]',
   '[]'),

  -- Ashgate Wastes (22 rooms)
  ('rubble-street-1',
   'Rubble Street',
   'The street dissolves into a field of broken stone, every step raising puffs of grey dust. Blackened walls rise on either side like rotting teeth. A scavenger picks through the debris with practised efficiency, pocketing anything metallic.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "rubble_scavenger", "spawnCount": 1}]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.2}]'),
  ('rubble-street-2',
   'Rubble Street',
   'Heaps of shattered masonry have been pushed to the sides of this street, creating unsteady walls of debris higher than a man. Corroded pipes and twisted rebar jut from the piles. The chemical smell of old destruction still lingers in the stone.',
   'corridor',
   '{pvp}',
   '[]',
   '[{"id": "rubble-pile-1", "type": "crate", "items": ["corroded_pipe", "bent_rebar"]}]',
   '[{"type": "unstable_rubble", "severity": 0.2}]'),
  ('rubble-street-3',
   'Rubble Street',
   'The destruction intensifies eastward, with entire building facades toppled across the road. A feral dog watches from atop a rubble heap, silhouetted against the hazy sky. The ground trembles faintly — settling foundations, or something worse.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 1}]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.3}]'),
  ('rubble-street-4',
   'Rubble Street',
   'A relatively clear stretch where someone has attempted to mark a path through the devastation with stacked stones. A scavenger follows the markers, sack slung over one shoulder. The silence here is oppressive, broken only by the crunch of grit underfoot.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "rubble_scavenger", "spawnCount": 1}]',
   '[]',
   '[]'),
  ('rubble-street-5',
   'Rubble Street',
   'The road bends around the bulk of a collapsed tower, its stones fanned across the intersection like discarded toys. Bent rebar and tarnished fittings protrude from the rubble. Wind whistles through the gaps, carrying a dry, ashy taste.',
   'corridor',
   '{pvp}',
   '[]',
   '[{"id": "rubble-pile-2", "type": "crate", "items": ["bent_rebar", "tarnished_medallion"]}]',
   '[{"type": "unstable_rubble", "severity": 0.2}]'),
  ('collapsed-building-1',
   'Collapsed Building',
   'A pancaked structure reduced to layers of compressed stone and splintered timber. The lower level is partially accessible through a gap in the debris, revealing a cellar full of salvageable material. The ceiling sags dangerously, held up by a single cracked beam.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "rubble_scavenger", "spawnCount": 1}]',
   '[{"id": "collapsed-salvage-1", "type": "crate", "items": ["corroded_pipe", "bent_rebar"]}]',
   '[{"type": "unstable_rubble", "severity": 0.4}]'),
  ('collapsed-building-2',
   'Collapsed Building',
   'What remains of a residential block rises in a jagged silhouette against the sky. Rats swarm through the voids between collapsed floors. The interior smells of mould and the peculiar sweetness of old plaster dust.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.4}]'),
  ('collapsed-building-3',
   'Collapsed Building',
   'The most extensively ruined structure in the wastes, its walls blown outward as if by an explosion from within. Scavengers pick through the scattered stone with urgency, filling sacks with anything useful. The rubble shifts underfoot with every step, threatening to swallow the unwary.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "rubble_scavenger", "spawnCount": 2}]',
   '[{"id": "collapsed-salvage-2", "type": "crate", "items": ["bent_rebar", "scavenger_shiv"]}]',
   '[{"type": "unstable_rubble", "severity": 0.5}]'),
  ('ashgate',
   'Ashgate',
   'A surviving gatehouse at the city''s eastern limit, its heavy door scarred but intact. Beyond, the wasteland gives way to the blasted terrain of the Warrens. The lintel bears a carved warning, half-obliterated by the same force that destroyed the surrounding blocks.',
   'entrance',
   '{pvp,heavy_door}',
   '[]',
   '[]',
   '[]'),
  ('scorched-plaza',
   'Scorched Plaza',
   'An open square blasted clean of any structure, its flagstones cracked and discoloured by extreme heat. The ground radiates warmth even now, and feral dogs circle the perimeter, drawn by the thermals. A chemical haze hangs at knee height, stinging the eyes.',
   'junction',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 2}]',
   '[]',
   '[{"type": "toxic_fumes", "severity": 0.2}]'),
  ('crumbling-wall-1',
   'Crumbling Wall',
   'The remnant of a fortification or property wall extends in a crumbling line, its upper courses spilled across the ground. The stone is pitted and scored as if by acid rain. Each gust of wind dislodges another shower of grit from above.',
   'corridor',
   '{pvp}',
   '[]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.3}]'),
  ('crumbling-wall-2',
   'Crumbling Wall',
   'A continuation of the ruined wall where it turns a corner and partially shelters a hollow in the rubble. A scavenger has made a temporary camp here, using the wall as a windbreak. Tool marks on the stone suggest systematic salvage.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "rubble_scavenger", "spawnCount": 1}]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.3}]'),
  ('bone-pit',
   'Bone Pit',
   'A shallow depression filled with animal bones, stripped clean and bleached by the elements. Feral dogs compete for territory here, their snarling a constant backdrop. The bones are mixed with rubble and the toxic fumes that seep from cracks in the earth.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 2}]',
   '[{"id": "bone-pile-1", "type": "corpse", "items": ["waterlogged_bone", "rat_tail"]}]',
   '[{"type": "toxic_fumes", "severity": 0.3}]'),
  ('plague-house',
   'Plague House',
   'A quarantined building marked with faded red crosses, its windows bricked up from the outside. Inside, the air is thick with a greenish miasma that clings to the walls. A shuffling figure wrapped in stained bandages moves in the deeper shadows, breathing audibly.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "plague_bearer", "spawnCount": 1}]',
   '[{"id": "plague-chest-1", "type": "chest", "items": ["plague_mask", "sewer_lamp"]}]',
   '[{"type": "toxic_fumes", "severity": 0.4}]'),
  ('ashgate-chapel',
   'Burned Chapel',
   'The stone skeleton of a small chapel, its wooden elements entirely consumed by fire. The altar survives, blackened but intact, and something has been placed upon it — an offering or a warning. Rats have colonised the crypt beneath, spilling upward through cracks in the floor.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "slum_rat", "spawnCount": 3}]',
   '[{"id": "chapel-altar-1", "type": "altar", "items": ["tarnished_medallion"]}]',
   '[]'),
  ('shattered-bridge',
   'Shattered Bridge',
   'An overpass that once connected two buildings now hangs in pieces, its central span dropped into the street below. The remaining stubs jut out like broken arms. The rubble beneath is unstable, and the drop on either side is enough to kill.',
   'dead_end',
   '{pvp}',
   '[]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.5}]'),
  ('dust-bowl',
   'Dust Bowl',
   'A circular depression where the wind spirals, trapping fine ash and dust in a perpetual slow vortex. Visibility drops to arm''s length in the centre. A scavenger skirts the edge, cloth wrapped over nose and mouth, eyes narrowed to slits.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "rubble_scavenger", "spawnCount": 1}]',
   '[]',
   '[{"type": "toxic_fumes", "severity": 0.2}]'),
  ('wrecked-barricade',
   'Wrecked Barricade',
   'Someone built a defensive barricade across this street and someone else tore it apart. Overturned carts, furniture, and sandbags lie scattered. A thug picks through the wreckage, pocketing what the builders left behind.',
   'corridor',
   '{pvp}',
   '[{"creatureId": "alley_thug", "spawnCount": 1}]',
   '[{"id": "barricade-stash-1", "type": "crate", "items": ["bent_rebar", "dock_rope"]}]',
   '[]'),
  ('ash-garden',
   'Ash Garden',
   'What was once a courtyard garden is now a grey expanse of compacted ash, the skeletal remains of trees standing like bleached coral. No bird sings here. Toxic fumes rise in lazy tendrils from the soil, and nothing living takes root.',
   'dead_end',
   '{pvp}',
   '[]',
   '[]',
   '[{"type": "toxic_fumes", "severity": 0.2}]'),
  ('carrion-field',
   'Carrion Field',
   'A wide intersection where bodies were once piled and burned, leaving a permanent stain on the stone. Feral dogs and rats contest the territory in vicious, running skirmishes. The chemical stench of old death and fresh toxins creates a miasma that waters the eyes and tightens the throat.',
   'junction',
   '{pvp}',
   '[{"creatureId": "feral_dog", "spawnCount": 2}, {"creatureId": "slum_rat", "spawnCount": 2}]',
   '[{"id": "carrion-corpse-1", "type": "corpse", "items": ["waterlogged_bone", "rat_tail"]}]',
   '[{"type": "toxic_fumes", "severity": 0.3}]'),
  ('blast-crater',
   'Blast Crater',
   'A deep, bowl-shaped crater punched into the earth by some catastrophic detonation. The stone at the rim is fused to glass in places. Something moves in the bottom — a thick-bodied serpent, its scales catching what little light penetrates the toxic haze.',
   'dead_end',
   '{pvp}',
   '[{"creatureId": "silt_serpent", "spawnCount": 1}]',
   '[{"id": "crater-debris-1", "type": "crate", "items": ["shardsteel_shard", "corroded_pipe"]}]',
   '[{"type": "toxic_fumes", "severity": 0.4}]'),
  ('scavengers-market',
   'Scavenger''s Market',
   'A cleared space where the waste-dwellers trade their salvage. Blankets spread on the rubble display bent metal, cracked glass, and unidentifiable fragments. Scavengers haggle in curt gestures and coded slang, eyes constantly scanning for threats.',
   'junction',
   '{pvp}',
   '[{"creatureId": "rubble_scavenger", "spawnCount": 2}]',
   '[{"id": "scav-crate-1", "type": "crate", "items": ["scavenger_shiv", "bent_rebar", "corroded_pipe"]}]',
   '[]'),

  -- Drowned Veins (26 rooms)
  ('undercity-gate',
   'Undercity Gate',
   'A heavy iron door set into the floor of the guild hall opens onto a steep spiral staircase descending into dripping darkness. The air that rises is cold and damp, carrying the sounds of running water and something breathing. Moss grows thick on the steps, making each one treacherous.',
   'entrance',
   '{pvp,heavy_door}',
   '[]',
   '[]',
   '[]'),
  ('sewer-junction-1',
   'Sewer Junction',
   'Three tunnels converge at this vaulted intersection, their waters mingling in a broad, shallow pool. Bioluminescent moss clings to the ceiling, casting a sickly green glow. A sewer lurker''s wet breathing echoes from one of the passages, impossible to place.',
   'junction',
   '{pvp,water}',
   '[{"creatureId": "sewer_lurker", "spawnCount": 1}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('sewer-junction-2',
   'Sewer Junction',
   'A wider junction where the ceiling rises to a dome, its surface thick with condensation that drips in a constant, maddening patter. The current here is stronger, pulling at the ankles. A lurker clings to the upper wall, barely visible against the slick stone.',
   'junction',
   '{pvp,water}',
   '[{"creatureId": "sewer_lurker", "spawnCount": 1}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('sewer-junction-3',
   'Sewer Junction',
   'The easternmost junction, where harbour water intrudes through cracks in the outer wall. The water is brackish and deeper here, reaching the knee at high tide. Steps carved into the wall lead upward to a heavy grate — the tide gate above.',
   'junction',
   '{pvp,water}',
   '[]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('sewer-tunnel-1',
   'Sewer Tunnel',
   'A straight stretch of brick-lined tunnel, its floor submerged under a shin-deep flow of murky water. Rats cling to the narrow ledges above the waterline, their eyes reflecting the dim light. The bricks are slimy with algae, and the smell is indescribable.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('sewer-tunnel-2',
   'Sewer Tunnel',
   'The tunnel narrows here where the walls have bowed inward under the weight of the city above. Debris — broken pipes, rotted timber, clumps of pale moss — collects against the constriction. The current pushes harder through the gap, churning the dark water to foam.',
   'corridor',
   '{pvp,water}',
   '[]',
   '[{"id": "sewer-debris-1", "type": "crate", "items": ["sewer_moss", "corroded_pipe"]}]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('sewer-tunnel-3',
   'Sewer Tunnel',
   'A tunnel that branches southward, its ceiling dropping low enough to force a crouch. The water deepens, and the sound of something large moving through it carries from ahead. Scratch marks on the walls are fresh, gouged into the brick by something with claws.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "sewer_lurker", "spawnCount": 1}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('sewer-tunnel-4',
   'Sewer Tunnel',
   'A long, straight section of tunnel where the echo plays tricks, making footsteps sound like they come from every direction. Rats surge through the water in panicked waves. The brickwork here is older, cruder — part of whatever existed before the city was built above.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "slum_rat", "spawnCount": 3}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('sewer-tunnel-5',
   'Sewer Tunnel',
   'The tunnel passes beneath what must be a major street, its ceiling reinforced with iron beams that weep orange rust into the flow. The water is shallower here, barely covering the ankles, but the footing is treacherous on the slime-coated stone.',
   'corridor',
   '{pvp,water}',
   '[]',
   '[]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('sewer-tunnel-6',
   'Sewer Tunnel',
   'The easternmost tunnel, where the sewer system begins to break down into natural cavern. Brick gives way to rough-hewn rock, and the water runs clearer but colder. A lurker''s pale form slides beneath the surface ahead, vanishing with barely a ripple.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "sewer_lurker", "spawnCount": 1}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('sewer-tunnel-7',
   'Sewer Tunnel',
   'A wider tunnel segment where the ceiling is high enough to stand. Rats nest on a ledge above the waterline, their refuse forming a reeking midden. Pale moss glows on the walls, providing just enough light to reveal the dark water''s sluggish movement.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[{"id": "sewer-debris-2", "type": "crate", "items": ["sewer_moss", "rat_tail"]}]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('sewer-tunnel-8',
   'Sewer Tunnel',
   'The westernmost tunnel, where the sewer system meets the natural water table. The water here is cold and surprisingly clean, welling up from cracks in the bedrock. The silence is absolute save for the drip of condensation and the distant rush of deeper currents.',
   'corridor',
   '{pvp,water}',
   '[]',
   '[]',
   '[{"type": "standing_water", "severity": 0.2}]'),
  ('drain-grate-1',
   'Drain Grate',
   'A vertical shaft capped by an iron grate, through which dim light and street noise filter from above. The walls are slick with condensation, and rats use the grate''s bars as a highway between the surface and the depths. Corroded pipes feed into the shaft, draining the city''s effluent.',
   'dead_end',
   '{pvp,water}',
   '[{"creatureId": "slum_rat", "spawnCount": 2}]',
   '[{"id": "drain-debris-1", "type": "crate", "items": ["corroded_pipe", "sewer_moss"]}]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('drain-grate-2',
   'Drain Grate',
   'Another vertical shaft, this one partially blocked by debris that has washed down from above. The grate overhead is rusted shut. Water cascades down one wall in a thin sheet, pooling on the floor before flowing into the main tunnel.',
   'dead_end',
   '{pvp,water}',
   '[]',
   '[]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('bone-canal',
   'Bone Canal',
   'A narrow waterway lined with bones embedded in the walls — a catacomb repurposed as a drain. The bones are old and fragile, crumbling at a touch. A lurker trails through the knee-deep water, disturbing a half-submerged corpse wedged against the wall.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "sewer_lurker", "spawnCount": 1}]',
   '[{"id": "bone-canal-corpse-1", "type": "corpse", "items": ["waterlogged_bone", "sewer_moss"]}]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('blackwater-crossing',
   'Blackwater Crossing',
   'A submerged intersection where the water runs deep and black, opaque with sediment and worse. Something large displaces the water ahead — the sinuous movement of a silt serpent. Crossing requires wading chest-deep through water that seems to pull at your legs.',
   'corridor',
   '{pvp,water}',
   '[{"creatureId": "silt_serpent", "spawnCount": 1}]',
   '[]',
   '[{"type": "standing_water", "severity": 0.4}]'),
  ('plague-bearers-lair',
   'Plague Bearer''s Lair',
   'A vaulted chamber thick with greenish gas that burns the lungs and blurs the vision. An altar of stacked bones dominates the centre, draped with stained cloth and ringed with guttering candles. The plague bearer kneels before it, bandaged hands raised, its breath a wet rattle that fills the room.',
   'boss',
   '{pvp,water}',
   '[{"creatureId": "plague_bearer", "spawnCount": 1}]',
   '[{"id": "plague-altar-1", "type": "altar", "items": ["plague_mask", "silt_venom_sac", "serpent_scale"]}]',
   '[{"type": "toxic_gas", "severity": 0.5}]'),
  ('drowned-shrine',
   'Drowned Shrine',
   'A submerged altar room, its religious iconography blurred by centuries of water damage. Offerings of corroded metal and smooth stones are piled at the base of a faceless statue. The water here is deeper and still, disturbed only by the slow drift of particles in the current.',
   'dead_end',
   '{pvp,water}',
   '[]',
   '[{"id": "shrine-offering-1", "type": "altar", "items": ["drowned_offering", "tarnished_medallion"]}]',
   '[{"type": "standing_water", "severity": 0.4}]'),
  ('flooded-chamber',
   'Flooded Chamber',
   'A large room almost entirely submerged, its ceiling barely clearing the waterline. Stone pillars rise from the murk, supporting an ancient vaulted roof. A silt serpent coils around one pillar, its iridescent scales catching the faint bioluminescent glow.',
   'dead_end',
   '{pvp,water}',
   '[{"creatureId": "silt_serpent", "spawnCount": 1}]',
   '[{"id": "flooded-chest-1", "type": "chest", "items": ["sewer_lamp", "waterlogged_bone"]}]',
   '[{"type": "standing_water", "severity": 0.5}]'),
  ('silt-pool',
   'Silt Pool',
   'A natural depression in the sewer floor where silt has accumulated in a deep, murky pool. Serpents twist through the clouded water, their movements visible only as ripples on the surface. The pool''s edges are treacherous, dropping away steeply into unseen depths.',
   'dead_end',
   '{pvp,water}',
   '[{"creatureId": "silt_serpent", "spawnCount": 2}]',
   '[{"id": "silt-deposit-1", "type": "crate", "items": ["silt_venom_sac", "serpent_scale"]}]',
   '[{"type": "standing_water", "severity": 0.4}]'),
  ('effluent-outflow',
   'Effluent Outflow',
   'The point where the sewer system discharges into the harbour through a wide pipe set into the outer wall. Toxic gas accumulates here where the confined air meets the sea breeze. The view through the outflow pipe reveals a circle of grey sky and churning water.',
   'dead_end',
   '{pvp,water}',
   '[]',
   '[]',
   '[{"type": "toxic_gas", "severity": 0.4}]'),
  ('sewer-vault',
   'Sewer Vault',
   'A locked stone chamber set into the sewer wall, its heavy door suggesting it once stored something valuable. Inside, the floor is dry — the room sits slightly above the waterline. Lurkers guard the space with the ferocity of things that have claimed territory.',
   'dead_end',
   '{pvp,water,heavy_door}',
   '[{"creatureId": "sewer_lurker", "spawnCount": 2}]',
   '[{"id": "vault-chest-1", "type": "chest", "items": ["smugglers_dagger", "alley_thugs_coin", "brass_compass"]}]',
   '[{"type": "standing_water", "severity": 0.3}]'),
  ('collapsed-sewer',
   'Collapsed Sewer',
   'A section of tunnel where the ceiling has partially given way, dumping rubble into the watercourse and creating a dam of broken stone. Water backs up behind the obstruction, forming a deeper pool. Rats swarm the rubble pile, and the remaining ceiling groans threateningly.',
   'dead_end',
   '{pvp,water}',
   '[{"creatureId": "slum_rat", "spawnCount": 3}]',
   '[]',
   '[{"type": "unstable_rubble", "severity": 0.4}, {"type": "standing_water", "severity": 0.3}]'),
  ('serpent-den',
   'Serpent''s Den',
   'A natural pocket in the rock where multiple silt serpents have established a communal nest. Shed scales litter the ledges above the waterline, glittering like scattered coins. The serpents coil and uncoil in the dark water, their eyes reflecting light in paired points of cold fire.',
   'dead_end',
   '{pvp,water}',
   '[{"creatureId": "silt_serpent", "spawnCount": 2}]',
   '[{"id": "serpent-nest-1", "type": "crate", "items": ["silt_venom_sac", "serpent_scale", "serpent_scale"]}]',
   '[{"type": "standing_water", "severity": 0.4}]'),
  ('fungal-cavern',
   'Fungal Cavern',
   'A side chamber where the damp conditions have fostered an explosion of pale, luminous fungi. The growths cover every surface — walls, ceiling, and the surface of the standing water — casting a ghostly blue-white light. A lurker moves among the fungal stalks, disturbing clouds of spores.',
   'dead_end',
   '{pvp,water}',
   '[{"creatureId": "sewer_lurker", "spawnCount": 1}]',
   '[{"id": "fungal-patch-1", "type": "crate", "items": ["sewer_moss", "sewer_moss"]}]',
   '[{"type": "toxic_gas", "severity": 0.3}]'),
  ('sewer-cistern-1',
   'Sewer Cistern',
   'A cylindrical stone tank, part of the city''s original water system, now flooded with dark, stagnant water. The walls are perfectly circular, rising into shadow above. A serpent slides through the water with lazy confidence, its territory unchallenged in this forgotten place.',
   'dead_end',
   '{pvp,water}',
   '[{"creatureId": "silt_serpent", "spawnCount": 1}]',
   '[{"id": "cistern-chest-1", "type": "chest", "items": ["sewer_lamp", "waterlogged_bone"]}]',
   '[{"type": "standing_water", "severity": 0.4}]')
) AS v(slug, name, description, type, properties, npcs, loot_containers, hazards)
WHERE z.slug = 'the-siltgate';

-- ═══════════════════════════════════════════════════════════════
-- Exits
-- ═══════════════════════════════════════════════════════════════
INSERT INTO zone_exits (zone_id, from_room_slug, direction, to_room_slug, target_zone_slug, target_room_slug, locked, hidden)
SELECT z.id, v.from_slug, v.direction, v.to_slug,
       NULLIF(v.target_zone, ''), NULLIF(v.target_room, ''),
       v.is_locked, v.is_hidden
FROM zones z, (VALUES
  ('market-square', 'north', 'fountain-plaza', '', '', false, false),
  ('fountain-plaza', 'south', 'market-square', '', '', false, false),
  ('market-square', 'east', 'bazaar-row-1', '', '', false, false),
  ('bazaar-row-1', 'west', 'market-square', '', '', false, false),
  ('market-square', 'south', 'tavern-row', '', '', false, false),
  ('tavern-row', 'north', 'market-square', '', '', false, false),
  ('market-square', 'west', 'city-gate', '', '', false, false),
  ('city-gate', 'east', 'market-square', '', '', false, false),
  ('bazaar-row-1', 'east', 'bazaar-row-2', '', '', false, false),
  ('bazaar-row-2', 'west', 'bazaar-row-1', '', '', false, false),
  ('bazaar-row-2', 'east', 'bazaar-row-3', '', '', false, false),
  ('bazaar-row-3', 'west', 'bazaar-row-2', '', '', false, false),
  ('bazaar-row-3', 'south', 'money-changers-row', '', '', false, false),
  ('money-changers-row', 'north', 'bazaar-row-3', '', '', false, false),
  ('fountain-plaza', 'north', 'news-board', '', '', false, false),
  ('news-board', 'south', 'fountain-plaza', '', '', false, false),
  ('tavern-row', 'east', 'scribe-corner', '', '', false, false),
  ('scribe-corner', 'west', 'tavern-row', '', '', false, false),
  ('fountain-plaza', 'east', 'silver-arcade-1', '', '', false, false),
  ('silver-arcade-1', 'west', 'fountain-plaza', '', '', false, false),
  ('bazaar-row-3', 'east', 'span-gate', '', '', false, false),
  ('span-gate', 'west', 'bazaar-row-3', '', '', false, false),
  ('tavern-row', 'south', 'dock-street-1', '', '', false, false),
  ('dock-street-1', 'north', 'tavern-row', '', '', false, false),
  ('fountain-plaza', 'up', 'estate-gate', '', '', false, false),
  ('estate-gate', 'down', 'fountain-plaza', '', '', false, false),
  ('silver-arcade-1', 'east', 'silver-arcade-2', '', '', false, false),
  ('silver-arcade-2', 'west', 'silver-arcade-1', '', '', false, false),
  ('silver-arcade-1', 'south', 'narrow-alley-1', '', '', false, false),
  ('narrow-alley-1', 'north', 'silver-arcade-1', '', '', false, false),
  ('silver-arcade-2', 'east', 'silver-arcade-3', '', '', false, false),
  ('silver-arcade-3', 'west', 'silver-arcade-2', '', '', false, false),
  ('silver-arcade-2', 'south', 'cobblestone-street-1', '', '', false, false),
  ('cobblestone-street-1', 'north', 'silver-arcade-2', '', '', false, false),
  ('silver-arcade-3', 'east', 'silver-arcade-4', '', '', false, false),
  ('silver-arcade-4', 'west', 'silver-arcade-3', '', '', false, false),
  ('silver-arcade-3', 'north', 'guild-hall', '', '', false, false),
  ('guild-hall', 'south', 'silver-arcade-3', '', '', false, false),
  ('silver-arcade-4', 'north', 'silk-road', '', '', false, false),
  ('silk-road', 'south', 'silver-arcade-4', '', '', false, false),
  ('silver-arcade-4', 'south', 'cobblestone-street-3', '', '', false, false),
  ('cobblestone-street-3', 'north', 'silver-arcade-4', '', '', false, false),
  ('cobblestone-street-1', 'east', 'cobblestone-street-2', '', '', false, false),
  ('cobblestone-street-2', 'west', 'cobblestone-street-1', '', '', false, false),
  ('cobblestone-street-2', 'east', 'cobblestone-street-3', '', '', false, false),
  ('cobblestone-street-3', 'west', 'cobblestone-street-2', '', '', false, false),
  ('cobblestone-street-2', 'south', 'narrow-alley-2', '', '', false, false),
  ('narrow-alley-2', 'north', 'cobblestone-street-2', '', '', false, false),
  ('narrow-alley-1', 'south', 'apothecary', '', '', false, false),
  ('apothecary', 'north', 'narrow-alley-1', '', '', false, false),
  ('narrow-alley-2', 'south', 'wine-merchants-cellar', '', '', false, false),
  ('wine-merchants-cellar', 'north', 'narrow-alley-2', '', '', false, false),
  ('guild-hall', 'north', 'jewelers-lane', '', '', false, false),
  ('jewelers-lane', 'south', 'guild-hall', '', '', false, false),
  ('guild-hall', 'east', 'cloth-merchants-hall', '', '', false, false),
  ('cloth-merchants-hall', 'west', 'guild-hall', '', '', false, false),
  ('cobblestone-street-1', 'south', 'glassblowers-workshop', '', '', false, false),
  ('glassblowers-workshop', 'north', 'cobblestone-street-1', '', '', false, false),
  ('cobblestone-street-3', 'south', 'pawn-shop', '', '', false, false),
  ('pawn-shop', 'north', 'cobblestone-street-3', '', '', false, false),
  ('cobblestone-street-3', 'east', 'merchant-inn', '', '', false, false),
  ('merchant-inn', 'west', 'cobblestone-street-3', '', '', false, false),
  ('guild-hall', 'down', 'undercity-gate', '', '', false, false),
  ('undercity-gate', 'up', 'guild-hall', '', '', false, false),
  ('estate-gate', 'north', 'promenade-walk-1', '', '', false, false),
  ('promenade-walk-1', 'south', 'estate-gate', '', '', false, false),
  ('promenade-walk-1', 'east', 'promenade-walk-2', '', '', false, false),
  ('promenade-walk-2', 'west', 'promenade-walk-1', '', '', false, false),
  ('promenade-walk-1', 'north', 'courtyard-fountain', '', '', false, false),
  ('courtyard-fountain', 'south', 'promenade-walk-1', '', '', false, false),
  ('promenade-walk-2', 'east', 'promenade-walk-3', '', '', false, false),
  ('promenade-walk-3', 'west', 'promenade-walk-2', '', '', false, false),
  ('promenade-walk-2', 'south', 'iron-balcony-1', '', '', false, false),
  ('iron-balcony-1', 'north', 'promenade-walk-2', '', '', false, false),
  ('promenade-walk-3', 'east', 'promenade-walk-4', '', '', false, false),
  ('promenade-walk-4', 'west', 'promenade-walk-3', '', '', false, false),
  ('promenade-walk-3', 'north', 'garden-terrace', '', '', false, false),
  ('garden-terrace', 'south', 'promenade-walk-3', '', '', false, false),
  ('promenade-walk-4', 'north', 'highwind-bridge', '', '', false, false),
  ('highwind-bridge', 'south', 'promenade-walk-4', '', '', false, false),
  ('courtyard-fountain', 'north', 'noble-residence-1', '', '', false, false),
  ('noble-residence-1', 'south', 'courtyard-fountain', '', '', false, false),
  ('courtyard-fountain', 'east', 'library-entrance', '', '', false, false),
  ('library-entrance', 'west', 'courtyard-fountain', '', '', false, false),
  ('courtyard-fountain', 'west', 'servants-passage', '', '', false, false),
  ('servants-passage', 'east', 'courtyard-fountain', '', '', false, false),
  ('garden-terrace', 'north', 'noble-residence-2', '', '', false, false),
  ('noble-residence-2', 'south', 'garden-terrace', '', '', false, false),
  ('garden-terrace', 'east', 'observatory', '', '', false, false),
  ('observatory', 'west', 'garden-terrace', '', '', false, false),
  ('garden-terrace', 'west', 'iron-balcony-2', '', '', false, false),
  ('iron-balcony-2', 'east', 'garden-terrace', '', '', false, false),
  ('iron-balcony-1', 'east', 'iron-balcony-2', '', '', false, false),
  ('iron-balcony-2', 'west', 'iron-balcony-1', '', '', false, false),
  ('highwind-bridge', 'north', 'belvedere', '', '', false, false),
  ('belvedere', 'south', 'highwind-bridge', '', '', false, false),
  ('dock-street-1', 'south', 'dock-street-2', '', '', false, false),
  ('dock-street-2', 'north', 'dock-street-1', '', '', false, false),
  ('dock-street-1', 'east', 'fish-market', '', '', false, false),
  ('fish-market', 'west', 'dock-street-1', '', '', false, false),
  ('dock-street-2', 'south', 'dock-street-3', '', '', false, false),
  ('dock-street-3', 'north', 'dock-street-2', '', '', false, false),
  ('dock-street-2', 'east', 'warehouse-1', '', '', false, false),
  ('warehouse-1', 'west', 'dock-street-2', '', '', false, false),
  ('dock-street-3', 'south', 'dock-street-4', '', '', false, false),
  ('dock-street-4', 'north', 'dock-street-3', '', '', false, false),
  ('dock-street-3', 'west', 'chandlers-shop', '', '', false, false),
  ('chandlers-shop', 'east', 'dock-street-3', '', '', false, false),
  ('dock-street-4', 'south', 'dock-street-5', '', '', false, false),
  ('dock-street-5', 'north', 'dock-street-4', '', '', false, false),
  ('dock-street-4', 'east', 'warehouse-2', '', '', false, false),
  ('warehouse-2', 'west', 'dock-street-4', '', '', false, false),
  ('dock-street-5', 'south', 'tide-gate', '', '', false, false),
  ('tide-gate', 'north', 'dock-street-5', '', '', false, false),
  ('dock-street-5', 'west', 'warehouse-3', '', '', false, false),
  ('warehouse-3', 'east', 'dock-street-5', '', '', false, false),
  ('fish-market', 'east', 'barnacled-quay', '', '', false, false),
  ('barnacled-quay', 'west', 'fish-market', '', '', false, false),
  ('fish-market', 'north', 'dockside-tavern', '', '', false, false),
  ('dockside-tavern', 'south', 'fish-market', '', '', false, false),
  ('fish-market', 'south', 'pier-3', '', '', false, false),
  ('pier-3', 'north', 'fish-market', '', '', false, false),
  ('barnacled-quay', 'east', 'rope-walk', '', '', false, false),
  ('rope-walk', 'west', 'barnacled-quay', '', '', false, false),
  ('barnacled-quay', 'south', 'pier-1', '', '', false, false),
  ('pier-1', 'north', 'barnacled-quay', '', '', false, false),
  ('barnacled-quay', 'north', 'harbourmasters-office', '', '', false, false),
  ('harbourmasters-office', 'south', 'barnacled-quay', '', '', false, false),
  ('rope-walk', 'south', 'pier-2', '', '', false, false),
  ('pier-2', 'north', 'rope-walk', '', '', false, false),
  ('rope-walk', 'east', 'tar-pit', '', '', false, false),
  ('tar-pit', 'west', 'rope-walk', '', '', false, false),
  ('rope-walk', 'north', 'sailmakers-loft', '', '', false, false),
  ('sailmakers-loft', 'south', 'rope-walk', '', '', false, false),
  ('tide-gate', 'east', 'dry-dock', '', '', false, false),
  ('dry-dock', 'west', 'tide-gate', '', '', false, false),
  ('tide-gate', 'south', 'smugglers-cove', '', '', false, true),
  ('smugglers-cove', 'north', 'tide-gate', '', '', false, false),
  ('dock-street-5', 'east', 'narrow-alley-3', '', '', false, false),
  ('narrow-alley-3', 'west', 'dock-street-5', '', '', false, false),
  ('tide-gate', 'down', 'sewer-junction-3', '', '', false, false),
  ('sewer-junction-3', 'up', 'tide-gate', '', '', false, false),
  ('tar-pit', 'east', 'scorched-plaza', '', '', false, false),
  ('scorched-plaza', 'west', 'tar-pit', '', '', false, false),
  ('span-gate', 'east', 'beggars-lane-1', '', '', false, false),
  ('beggars-lane-1', 'west', 'span-gate', '', '', false, false),
  ('beggars-lane-1', 'east', 'beggars-lane-2', '', '', false, false),
  ('beggars-lane-2', 'west', 'beggars-lane-1', '', '', false, false),
  ('beggars-lane-2', 'east', 'beggars-lane-3', '', '', false, false),
  ('beggars-lane-3', 'west', 'beggars-lane-2', '', '', false, false),
  ('beggars-lane-1', 'south', 'narrow-alley-3', '', '', false, false),
  ('narrow-alley-3', 'north', 'beggars-lane-1', '', '', false, false),
  ('beggars-lane-2', 'south', 'rat-run-1', '', '', false, false),
  ('rat-run-1', 'north', 'beggars-lane-2', '', '', false, false),
  ('narrow-alley-3', 'south', 'narrow-alley-4', '', '', false, false),
  ('narrow-alley-4', 'north', 'narrow-alley-3', '', '', false, false),
  ('narrow-alley-4', 'east', 'lean-to-camp', '', '', false, false),
  ('lean-to-camp', 'west', 'narrow-alley-4', '', '', false, false),
  ('narrow-alley-4', 'south', 'narrow-alley-5', '', '', false, false),
  ('narrow-alley-5', 'north', 'narrow-alley-4', '', '', false, false),
  ('narrow-alley-5', 'east', 'narrow-alley-6', '', '', false, false),
  ('narrow-alley-6', 'west', 'narrow-alley-5', '', '', false, false),
  ('narrow-alley-6', 'east', 'narrow-alley-7', '', '', false, false),
  ('narrow-alley-7', 'west', 'narrow-alley-6', '', '', false, false),
  ('narrow-alley-7', 'east', 'narrow-alley-8', '', '', false, false),
  ('narrow-alley-8', 'west', 'narrow-alley-7', '', '', false, false),
  ('narrow-alley-6', 'south', 'gutter-drain', '', '', false, false),
  ('gutter-drain', 'north', 'narrow-alley-6', '', '', false, false),
  ('narrow-alley-7', 'south', 'mud-flat', '', '', false, false),
  ('mud-flat', 'north', 'narrow-alley-7', '', '', false, false),
  ('narrow-alley-8', 'south', 'pawn-alley', '', '', false, false),
  ('pawn-alley', 'north', 'narrow-alley-8', '', '', false, false),
  ('gutter-drain', 'south', 'beggar-kings-court', '', '', false, false),
  ('beggar-kings-court', 'north', 'gutter-drain', '', '', false, false),
  ('mud-flat', 'south', 'broken-bridge', '', '', false, false),
  ('broken-bridge', 'north', 'mud-flat', '', '', false, false),
  ('pawn-alley', 'south', 'ruined-tenement-1', '', '', false, false),
  ('ruined-tenement-1', 'north', 'pawn-alley', '', '', false, false),
  ('beggar-kings-court', 'east', 'ruined-tenement-2', '', '', false, false),
  ('ruined-tenement-2', 'west', 'beggar-kings-court', '', '', false, false),
  ('rat-run-1', 'east', 'flophouse', '', '', false, false),
  ('flophouse', 'west', 'rat-run-1', '', '', false, false),
  ('rat-run-1', 'south', 'rat-run-2', '', '', false, false),
  ('rat-run-2', 'north', 'rat-run-1', '', '', false, false),
  ('rat-run-2', 'east', 'thieves-den', '', '', false, true),
  ('thieves-den', 'west', 'rat-run-2', '', '', false, false),
  ('gutter-drain', 'down', 'sewer-junction-1', '', '', false, false),
  ('sewer-junction-1', 'up', 'gutter-drain', '', '', false, false),
  ('beggars-lane-3', 'east', 'rubble-street-1', '', '', false, false),
  ('rubble-street-1', 'west', 'beggars-lane-3', '', '', false, false),
  ('rubble-street-1', 'east', 'rubble-street-2', '', '', false, false),
  ('rubble-street-2', 'west', 'rubble-street-1', '', '', false, false),
  ('rubble-street-1', 'south', 'collapsed-building-1', '', '', false, false),
  ('collapsed-building-1', 'north', 'rubble-street-1', '', '', false, false),
  ('rubble-street-2', 'east', 'rubble-street-3', '', '', false, false),
  ('rubble-street-3', 'west', 'rubble-street-2', '', '', false, false),
  ('rubble-street-2', 'south', 'scorched-plaza', '', '', false, false),
  ('scorched-plaza', 'north', 'rubble-street-2', '', '', false, false),
  ('rubble-street-3', 'east', 'rubble-street-4', '', '', false, false),
  ('rubble-street-4', 'west', 'rubble-street-3', '', '', false, false),
  ('rubble-street-3', 'north', 'collapsed-building-2', '', '', false, false),
  ('collapsed-building-2', 'south', 'rubble-street-3', '', '', false, false),
  ('rubble-street-4', 'east', 'rubble-street-5', '', '', false, false),
  ('rubble-street-5', 'west', 'rubble-street-4', '', '', false, false),
  ('rubble-street-4', 'south', 'dust-bowl', '', '', false, false),
  ('dust-bowl', 'north', 'rubble-street-4', '', '', false, false),
  ('rubble-street-5', 'east', 'ashgate', '', '', false, false),
  ('ashgate', 'west', 'rubble-street-5', '', '', false, false),
  ('rubble-street-5', 'south', 'wrecked-barricade', '', '', false, false),
  ('wrecked-barricade', 'north', 'rubble-street-5', '', '', false, false),
  ('scorched-plaza', 'south', 'crumbling-wall-1', '', '', false, false),
  ('crumbling-wall-1', 'north', 'scorched-plaza', '', '', false, false),
  ('scorched-plaza', 'east', 'carrion-field', '', '', false, false),
  ('carrion-field', 'west', 'scorched-plaza', '', '', false, false),
  ('crumbling-wall-1', 'south', 'crumbling-wall-2', '', '', false, false),
  ('crumbling-wall-2', 'north', 'crumbling-wall-1', '', '', false, false),
  ('crumbling-wall-1', 'east', 'bone-pit', '', '', false, false),
  ('bone-pit', 'west', 'crumbling-wall-1', '', '', false, false),
  ('crumbling-wall-2', 'south', 'plague-house', '', '', false, false),
  ('plague-house', 'north', 'crumbling-wall-2', '', '', false, false),
  ('carrion-field', 'south', 'scavengers-market', '', '', false, false),
  ('scavengers-market', 'north', 'carrion-field', '', '', false, false),
  ('carrion-field', 'east', 'collapsed-building-3', '', '', false, false),
  ('collapsed-building-3', 'west', 'carrion-field', '', '', false, false),
  ('scavengers-market', 'south', 'ash-garden', '', '', false, false),
  ('ash-garden', 'north', 'scavengers-market', '', '', false, false),
  ('scavengers-market', 'east', 'blast-crater', '', '', false, false),
  ('blast-crater', 'west', 'scavengers-market', '', '', false, false),
  ('dust-bowl', 'south', 'ashgate-chapel', '', '', false, false),
  ('ashgate-chapel', 'north', 'dust-bowl', '', '', false, false),
  ('wrecked-barricade', 'south', 'shattered-bridge', '', '', false, false),
  ('shattered-bridge', 'north', 'wrecked-barricade', '', '', false, false),
  ('sewer-tunnel-8', 'east', 'sewer-tunnel-7', '', '', false, false),
  ('sewer-tunnel-7', 'west', 'sewer-tunnel-8', '', '', false, false),
  ('sewer-tunnel-7', 'east', 'sewer-junction-1', '', '', false, false),
  ('sewer-junction-1', 'west', 'sewer-tunnel-7', '', '', false, false),
  ('sewer-junction-1', 'east', 'sewer-tunnel-1', '', '', false, false),
  ('sewer-tunnel-1', 'west', 'sewer-junction-1', '', '', false, false),
  ('sewer-tunnel-1', 'east', 'sewer-tunnel-2', '', '', false, false),
  ('sewer-tunnel-2', 'west', 'sewer-tunnel-1', '', '', false, false),
  ('sewer-tunnel-2', 'east', 'sewer-junction-2', '', '', false, false),
  ('sewer-junction-2', 'west', 'sewer-tunnel-2', '', '', false, false),
  ('sewer-junction-2', 'east', 'sewer-tunnel-4', '', '', false, false),
  ('sewer-tunnel-4', 'west', 'sewer-junction-2', '', '', false, false),
  ('sewer-tunnel-4', 'east', 'sewer-tunnel-5', '', '', false, false),
  ('sewer-tunnel-5', 'west', 'sewer-tunnel-4', '', '', false, false),
  ('sewer-tunnel-5', 'east', 'sewer-junction-3', '', '', false, false),
  ('sewer-junction-3', 'west', 'sewer-tunnel-5', '', '', false, false),
  ('sewer-junction-3', 'east', 'sewer-tunnel-6', '', '', false, false),
  ('sewer-tunnel-6', 'west', 'sewer-junction-3', '', '', false, false),
  ('sewer-junction-1', 'north', 'undercity-gate', '', '', false, false),
  ('undercity-gate', 'south', 'sewer-junction-1', '', '', false, false),
  ('sewer-junction-1', 'south', 'sewer-tunnel-3', '', '', false, false),
  ('sewer-tunnel-3', 'north', 'sewer-junction-1', '', '', false, false),
  ('sewer-junction-2', 'north', 'drain-grate-1', '', '', false, false),
  ('drain-grate-1', 'south', 'sewer-junction-2', '', '', false, false),
  ('sewer-junction-2', 'south', 'bone-canal', '', '', false, false),
  ('bone-canal', 'north', 'sewer-junction-2', '', '', false, false),
  ('sewer-junction-3', 'south', 'drain-grate-2', '', '', false, false),
  ('drain-grate-2', 'north', 'sewer-junction-3', '', '', false, false),
  ('sewer-tunnel-8', 'south', 'flooded-chamber', '', '', false, false),
  ('flooded-chamber', 'north', 'sewer-tunnel-8', '', '', false, false),
  ('sewer-tunnel-7', 'south', 'fungal-cavern', '', '', false, false),
  ('fungal-cavern', 'north', 'sewer-tunnel-7', '', '', false, false),
  ('sewer-tunnel-5', 'south', 'sewer-cistern-1', '', '', false, false),
  ('sewer-cistern-1', 'north', 'sewer-tunnel-5', '', '', false, false),
  ('sewer-tunnel-3', 'south', 'silt-pool', '', '', false, false),
  ('silt-pool', 'north', 'sewer-tunnel-3', '', '', false, false),
  ('sewer-tunnel-3', 'east', 'serpent-den', '', '', false, false),
  ('serpent-den', 'west', 'sewer-tunnel-3', '', '', false, false),
  ('sewer-tunnel-6', 'east', 'sewer-vault', '', '', false, false),
  ('sewer-vault', 'west', 'sewer-tunnel-6', '', '', false, false),
  ('sewer-tunnel-6', 'south', 'effluent-outflow', '', '', false, false),
  ('effluent-outflow', 'north', 'sewer-tunnel-6', '', '', false, false),
  ('bone-canal', 'south', 'blackwater-crossing', '', '', false, false),
  ('blackwater-crossing', 'north', 'bone-canal', '', '', false, false),
  ('blackwater-crossing', 'south', 'plague-bearers-lair', '', '', false, false),
  ('plague-bearers-lair', 'north', 'blackwater-crossing', '', '', false, false),
  ('plague-bearers-lair', 'east', 'drowned-shrine', '', '', false, false),
  ('drowned-shrine', 'west', 'plague-bearers-lair', '', '', false, false),
  ('drain-grate-2', 'east', 'collapsed-sewer', '', '', false, false),
  ('collapsed-sewer', 'west', 'drain-grate-2', '', '', false, false),
  ('city-gate', 'west', 'city-gate', 'the-refuge', 'market', false, false),
  ('ashgate', 'east', 'ashgate', 'warrens', 'shattered-gate', false, false)
) AS v(from_slug, direction, to_slug, target_zone, target_room, is_locked, is_hidden)
WHERE z.slug = 'the-siltgate';

-- ═══════════════════════════════════════════════════════════════
-- Cross-zone return exits (from Refuge and Warrens back to Siltgate)
-- ═══════════════════════════════════════════════════════════════
INSERT INTO zone_exits (zone_id, from_room_slug, direction, to_room_slug, target_zone_slug, target_room_slug, locked, hidden)
SELECT z.id, v.from_slug, v.direction, v.to_slug,
       NULLIF(v.target_zone, ''), NULLIF(v.target_room, ''),
       v.is_locked, v.is_hidden
FROM zones z, (VALUES
  ('market', 'south', 'market', 'the-siltgate', 'city-gate', false, false)
) AS v(from_slug, direction, to_slug, target_zone, target_room, is_locked, is_hidden)
WHERE z.slug = 'the-refuge'
ON CONFLICT DO NOTHING;

INSERT INTO zone_exits (zone_id, from_room_slug, direction, to_room_slug, target_zone_slug, target_room_slug, locked, hidden)
SELECT z.id, v.from_slug, v.direction, v.to_slug,
       NULLIF(v.target_zone, ''), NULLIF(v.target_room, ''),
       v.is_locked, v.is_hidden
FROM zones z, (VALUES
  ('shattered-gate', 'south', 'shattered-gate', 'the-siltgate', 'ashgate', false, false)
) AS v(from_slug, direction, to_slug, target_zone, target_room, is_locked, is_hidden)
WHERE z.slug = 'warrens'
ON CONFLICT DO NOTHING;

