-- 004_import_midgaard.sql — Import Midgaard as a playable adventure zone.
--
-- Source: Classic DikuMUD/CircleMUD Midgaard zone (zone 30, tbaMUD stock areas)
-- Imported via scripts/import-diku-zone.ts, then adapted for production use.
--
-- 57 rooms, 115 intra-zone exits, 2 cross-zone portal exits (Siltgate ↔ Midgaard)
-- 1 builder meta-room (petshop-storeroom) excluded — no exits, not player content.

BEGIN;

-- ============================================================================
-- Zone: Midgaard City
-- ============================================================================

INSERT INTO zones (id, slug, name, description, level_min, level_max, tier, theme, entry_room_slugs, lifecycle, category, max_players, pvp_enabled, repop_interval_seconds)
VALUES (gen_random_uuid(), 'midgaard', 'Midgaard City',
  'The drowned remnants of an old-world city district, half-submerged and picked over by scavengers. Pre-extinction streets grid out beneath knee-deep brackish water, their storefronts gutted and colonised by moss and fiddler crabs. Temples and guild halls still stand — too massive to topple — but their grandeur belongs to a dead age. The locals call it Midgaard, though no one remembers why.',
  1, 10, 1, 'urban', '{outside-the-west-gate-of-midgaard}', 'persistent', 'dungeon', 20, false, 300)
ON CONFLICT (slug) DO NOTHING;

-- ── Rooms (57) ──────────────────────────────────────────────

INSERT INTO zone_rooms (zone_id, slug, name, description, type, properties, npcs, loot_containers, hazards)
SELECT z.id, v.slug, v.name, v.description, v.type,
       v.properties::text[], v.npcs::jsonb, v.loot_containers::jsonb, v.hazards::jsonb
FROM zones z, (VALUES
  -- vnum 3000
  ('the-reading-room',
   'The Reading Room',
   'You are in a small, simple room which is mostly empty, save a few wooden desks and benches. To the east you hear the bustle of the Temple of Midgaard, a sharp contrast to the relative quiet of this peaceful room.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3001
  ('the-temple-of-midgaard',
   'The Temple Of Midgaard',
   'You are in the southern end of the temple hall in the Temple of Midgaard. The temple has been constructed from giant marble blocks, eternal in appearance, and most of the walls are covered by ancient wall paintings picturing Gods, giants and peasants. Large steps lead down through the grand temple gate, descending the huge mound upon which the temple is built and ends on the temple square below. To the west, you see the Reading Room. The donation room is in a small alcove to your east.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3002
  ('the-clerics-inner-sanctum',
   'The Clerics'' Inner Sanctum',
   'This is the inner sanctum. A picture of the mighty Thor, is hanging on the wall, just above the altar which is set against the western wall. A well in the middle of the floor leads down into darkness. Vile smells waft from the depths.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3003
  ('the-bar-of-divination',
   'The Bar Of Divination',
   'The bar is one of the finest in the land, lucky it is members only. Fine furniture is set all around the room. A small sign is hanging on the wall.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3004
  ('the-entrance-to-the-clerics-guild',
   'The Entrance To The Clerics'' Guild',
   'The entrance hall is a small modest room, reflecting the true nature of the Clerics. The exit leads east to the temple square. A small entrance to the bar is in the northern wall.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3005
  ('the-temple-square',
   'The Temple Square',
   'You are standing on the temple square. Huge marble steps lead up to the temple gate. The entrance to the Clerics'' Guild is to the west, and the old Grunting Boar Inn, is to the east. Just south of here you see the market square, the center of Midgaard.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3006
  ('the-entrance-hall-of-the-grunting-boar-inn',
   'The Entrance Hall Of The Grunting Boar Inn',
   'You are standing in the entrance hall of the Grunting Boar Inn. The hall has been wisely decorated with simple, functional furniture. The heavy smell of dust and aging paper drifts in from the Post Office to the north. A small staircase leads up to the reception and the bar is to the east.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3007
  ('the-grunting-boar',
   'The Grunting Boar',
   'You are standing in the bar. The bar is set against the northern wall, old archaic writing, carvings and symbols cover its top. A fireplace is built into the western wall, and through the southeastern windows you can see the temple square. This place makes you feel like home. A small sign with big letters is fastened to the bar.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3008
  ('the-reception',
   'The Reception',
   'You are standing in the reception. The staircase leads down to the entrance hall. An exit to the north leads to the Cryogenic Center. There is a small sign on the counter.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3009
  ('the-bakery',
   'The Bakery',
   'You are standing inside the small bakery. A sweet scent of danish and fine bread fills the room. The bread and Danish are arranged in fine order on the shelves, and seem to be of the finest quality. A small sign is on the counter.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3010
  ('the-general-store',
   'The General Store',
   'You are inside the general store. All sorts of items are stacked on shelves behind the counter, safely out of your reach. A small note hangs on the wall.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3011
  ('the-weapon-shop',
   'The Weapon Shop',
   'The smell of worked metals and various quenching oils fills the room. Every available space in the room including the ceiling is loaded with various equipment and weaponry. There is a small note on the counter.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3012
  ('main-street',
   'Main Street',
   'You are at the end of the main street of Midgaard. South of here is the entrance to the Guild of Magic Users. The street continues east towards the market square. The magic shop is to the north and to the west is the city gate.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3013
  ('main-street-2',
   'Main Street',
   'You are on the main street passing through the City of Midgaard. South of here is the entrance to the Armory, and the bakery is to the north. East of here is the market square.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3014
  ('market-square',
   'Market Square',
   'You are standing on the market square, the famous Square of Midgaard. A large, peculiar looking statue is standing in the middle of the square. Roads lead in every direction, north to the temple square, south to the common square, east and westbound is the main street.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3015
  ('main-street-3',
   'Main Street',
   'You are on the main street crossing through town. To the north is the general store, and the main street continues east. To the west you see and hear the market place, to the south a small door leads into the Pet Shop.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3016
  ('main-street-4',
   'Main Street',
   'The main street, to the north is the weapon shop and to the south is the Guild of Swordsmen. To the east you leave town and to the west the street leads to the market square.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3017
  ('the-entrance-to-the-mages-guild',
   'The Entrance To The Mages'' Guild',
   'The entrance hall to this guild is a small, poor lighted room.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3018
  ('the-mages-bar',
   'The Mages'' Bar',
   'The bar is one of the weirdest in the land. Mystical images float around the air. Illusions of fine furniture appear all around the room.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3019
  ('the-mages-laboratory',
   'The Mages'' Laboratory',
   'This is the Magical Experiments Laboratory. Dark smoke-stained stones arch over numerous huge oaken tables, most of these cluttered with strange- looking pipes and flasks. The floor is covered with half-erased pentagrams and even weirder symbols, and a blackboard in a dark corner has only been partially cleaned, some painful-looking letters faintly visible.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3020
  ('the-armory',
   'The Armory',
   'The armory has a wide assortment of armor displayed on the walls and in the windows. Helmets, shields, and suits of armor are for sale. To the north is the main street. On the wall is a small note.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3021
  ('the-entrance-hall-to-the-guild-of-swordsmen',
   'The Entrance Hall To The Guild Of Swordsmen',
   'The entrance hall to the Guild of Swordsmen. A place where one has to be careful not to say something wrong (or right). To the east is the bar and to the north is the main street.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3022
  ('the-bar-of-swordsmen',
   'The Bar Of Swordsmen',
   'The bar of swordsmen, once upon a time beautifully furnished. But now the furniture is all around you in small pieces. To the south is the yard, and to the west is the entrance hall.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3023
  ('the-tournament-and-practice-yard',
   'The Tournament And Practice Yard',
   'This is the practice yard of the fighters. To the north is the bar. A well leads down into darkness.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3024
  ('the-eastern-end-of-poor-alley',
   'The Eastern End Of Poor Alley',
   'You are at the poor alley. South of here is the Grubby Inn and to the east you see common square. The alley continues further west.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3025
  ('the-common-square',
   'The Common Square',
   'The common square, people pass you, talking to each other. To the west is the poor alley and to the east is the dark alley. To the north, this square is connected to the market square. From the south you notice a nasty smell.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3026
  ('the-dark-alley',
   'The Dark Alley',
   'The dark alley, to the west is the common square and to the south is the Guild of Thieves. The alley continues east.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3027
  ('the-entrance-hall-to-the-guild-of-thieves',
   'The Entrance Hall To The Guild Of Thieves',
   'The entrance hall to the thieves'' and assassins'' guild. A place where you can lose both your life and your money, if you are not careful. To the north is the dark alley and to the east is the thieves'' bar.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3028
  ('the-thieves-bar',
   'The Thieves'' Bar',
   'The bar of the thieves. Once upon a time this place was beautifully furnished, but now it seems almost empty. To the south is the yard, and to the west is the entrance hall. (Maybe the furniture has been stolen?!)',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3029
  ('the-secret-yard',
   'The Secret Yard',
   'The secret practice yard of thieves and assassins. To the north is the bar. A well leads down into darkness.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3030
  ('the-dump',
   'The Dump',
   'The dump, where the people from the city drop their garbage. Through the garbage you can see a large junction of pipes, looks like the entrance to the sewer system. North of here you see the common square.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3031
  ('the-pet-shop',
   'The Pet Shop',
   'The Pet Shop is a small crowded store, full of cages and animals of various sizes. There is a sign on the wall.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3033
  ('the-magic-shop',
   'The Magic Shop',
   'Behind the counter you see various items, neatly placed in racks, presumably most of them are magic.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3040
  ('inside-the-west-gate-of-midgaard',
   'Inside The West Gate Of Midgaard',
   'You are by two small towers that have been built into the city wall and connected with a footbridge across the heavy wooden gate. Main Street leads east and Wall Road leads south from here.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3041
  ('inside-the-east-gate-of-midgaard',
   'Inside The East Gate Of Midgaard',
   'You are by two small towers that have been built into the city wall and connected with a footbridge across the heavy wooden gate. Main Street leads west from here. To the south you see the Water Shop.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3042
  ('wall-road',
   'Wall Road',
   'You are walking next to the western city wall. The road continues further south and the city gate is just north of here.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3043
  ('wall-road-2',
   'Wall Road',
   'You are walking next to the western city wall. Wall Road continues further north and south. A small, poor alley leads east. Some letters have been written on the wall here.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3044
  ('poor-alley',
   'Poor Alley',
   'You are on Poor Alley, which continues further east. You see the city wall to the west.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3045
  ('the-dark-alley-at-the-levee',
   'The Dark Alley At The Levee',
   'You are standing in the alley which continues east and west. South of here you see the levee.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3046
  ('the-eastern-end-of-the-alley',
   'The Eastern End Of The Alley',
   'You are standing at the eastern end of the alley, the city wall is just east, blocking any further movement. A small warehouse is directly south of here.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3047
  ('wall-road-3',
   'Wall Road',
   'You are standing on the road next to the western city wall, which continues north. South of here is a bridge across the river.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3048
  ('grubby-inn',
   'Grubby Inn',
   'You are inside the old Grubby Inn. This place has not been cleaned for several decades; vile smells make you dizzy.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3049
  ('the-levee',
   'The Levee',
   'You are at the levee. South of here you see the river gently flowing west. The river bank is very low making it possible to enter the river.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3050
  ('the-deserted-warehouse',
   'The Deserted Warehouse',
   'You are inside the warehouse. The room is decorated with various old items from ships.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3051
  ('on-the-bridge',
   'On The Bridge',
   'You are standing on the stone bridge crosses the river. The bridge is built out from the western city wall and the river flows west through an opening in the wall ten feet below the bridge.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3052
  ('outside-the-west-gate-of-midgaard',
   'Outside The West Gate Of Midgaard',
   'You are by two small towers that have been built into the city wall and connected with a footbridge across the heavy wooden gate. To the west you can see the edge of a big forest.',
   'entrance',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3053
  ('outside-the-east-gate-of-midgaard',
   'Outside The East Gate Of Midgaard',
   'You are by two small towers that have been built into the city wall and connected with a footbridge across the heavy wooden gate. To the east the plains stretch out in the distance.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3054
  ('by-the-temple-altar',
   'By The Temple Altar',
   'You are by the temple altar in the northern end of the Temple of Midgaard. A huge altar made from white polished marble dominates this part of the temple. Towering behind the altar is a ten foot tall sitting statue of Odin, the King of the Gods. To the north, steps lead out the back of the temple towards the countryside.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3058
  ('ye-olde-water-shoppe',
   'Ye Olde Water Shoppe',
   'You are standing in the center of a small wooden shop whose walls are covered with racks upon racks of water jugs. Several large barrels with spigots are stacked in the corner.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3059
  ('behind-the-temple-altar',
   'Behind The Temple Altar',
   'You are on a dirt path leading away from the Temple Altar which is south of here. To the north, the path continues through the lush contryside of Midgaard towards the Dragonhelm Mountains far off to the north.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3060
  ('the-great-field-of-midgaard',
   'The Great Field Of Midgaard',
   'You are walking on a wide dirt path through the lush, green, fresh Midgaard countryside. You can see to the horizon to the north, east, and west; the busy city of Midgaard lies to the south. All around you is healthy green grass and an occasional large oak tree. The sun feels wonderful on your face and a pleasant wind blows through your hair. Birds chirp quietly to themselves and you can smell the faint scent of flowers and freshly cut grass. You feel like you could lie down in the grass and stay here forever, surrounded by powerful beauty in all directions. The path you are on continues north through the field and south back to Midgaard.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3061
  ('the-great-field-of-midgaard-2',
   'The Great Field Of Midgaard',
   'You are walking on a wide dirt path through the lush, green, fresh Midgaard countryside. You can see to the horizon to the north, east, and west; the busy city of Midgaard lies to the south. All around you is healthy green grass and an occasional large oak tree. The sun feels wonderful on your face and a pleasant wind blows through your hair. Birds chirp quietly to themselves and you can smell the faint scent of flowers and freshly cut grass. You feel like you could lie down in the grass and stay here forever, surrounded by powerful beauty in all directions. There is a strange structure on the eastern side of the path. A small dirt path splits off of the main path and leads off to the west.',
   'junction',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3062
  ('the-post-office',
   'The Post Office',
   'You are in the central post office for Midgaard. Piles of assorted mail lay untouched in the corners, collecting cobwebs. Several large crates have been pried open by curious customs agents, and are now stacked along the west wall, hiding plenty of ''WANTED'' posters. There is a sign posted on the wall here.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3063
  ('the-midgaard-donation-room',
   'The Midgaard Donation Room',
   'You are in a small, undecorated room just off of the main temple. There are a couple of small wooden benches here where people occasionally sit while they wait for items to appear. The temple is to the west.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3064
  ('the-cryogenic-center',
   'The Cryogenic Center',
   'You are standing in an impossibly white sterile room with cylindrical body-length canisters lined up against the walls. The Reception is to the south.',
   'dead_end',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3065
  ('the-great-field-of-midgaard-3',
   'The Great Field Of Midgaard',
   'You are walking on a wide dirt path through the lush, green, fresh Midgaard countryside. You can see to the horizon to the north, east, and west; the busy city of Midgaard lies to the south. All around you is healthy green grass and an occasional large oak tree. The sun feels wonderful on your face and a pleasant wind blows through your hair. Birds chirp quietly to themselves and you can smell the faint scent of flowers and freshly cut grass. You feel like you could lie down in the grass and stay here forever, surrounded by powerful beauty in all directions. The way north appears to be blocked by a large plot device and you cannot see any way around it.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]'),
  -- vnum 3066
  ('the-dirt-path',
   'The Dirt Path',
   'You are walking along a narrow dirt path through the lush, green, fresh Midgaard countryside. You can see to the horizon to the north and east; the busy city of Midgaard lies to the south. All around you is healthy green grass and an occasional large oak tree. The sun feels wonderful on your face and a pleasant wind blows through your hair. Birds chirp quietly to themselves and you can smell the faint scent of flowers and freshly cut grass. You feel like you could lie down in the grass and stay here forever, surrounded by powerful beauty in all directions. There is a large rusty gate sitting in a stone archway just to the west.',
   'corridor',
   '{}',
   '[]',
   '[]',
   '[]')
) AS v(slug, name, description, type, properties, npcs, loot_containers, hazards)
WHERE z.slug = 'midgaard'
ON CONFLICT (zone_id, slug) DO NOTHING;

-- ── Exits (115 intra-zone) ──────────────────────────────────

INSERT INTO zone_exits (zone_id, from_room_slug, direction, to_room_slug, target_zone_slug, target_room_slug, locked, hidden)
SELECT z.id, v.from_slug, v.direction, v.to_slug,
       NULLIF(v.target_zone, ''), NULLIF(v.target_room, ''),
       v.is_locked, v.is_hidden
FROM zones z, (VALUES
  ('the-reading-room', 'east', 'the-temple-of-midgaard', '', '', false, false),
  ('the-temple-of-midgaard', 'north', 'by-the-temple-altar', '', '', false, false),
  ('the-temple-of-midgaard', 'east', 'the-midgaard-donation-room', '', '', false, false),
  ('the-temple-of-midgaard', 'south', 'the-temple-square', '', '', false, false),
  ('the-temple-of-midgaard', 'west', 'the-reading-room', '', '', false, false),
  ('the-temple-of-midgaard', 'down', 'the-temple-square', '', '', false, false),
  ('the-clerics-inner-sanctum', 'east', 'the-bar-of-divination', '', '', false, false),
  ('the-bar-of-divination', 'south', 'the-entrance-to-the-clerics-guild', '', '', false, false),
  ('the-bar-of-divination', 'west', 'the-clerics-inner-sanctum', '', '', false, false),
  ('the-entrance-to-the-clerics-guild', 'north', 'the-bar-of-divination', '', '', false, false),
  ('the-entrance-to-the-clerics-guild', 'east', 'the-temple-square', '', '', false, false),
  ('the-temple-square', 'north', 'the-temple-of-midgaard', '', '', false, false),
  ('the-temple-square', 'east', 'the-entrance-hall-of-the-grunting-boar-inn', '', '', false, false),
  ('the-temple-square', 'south', 'market-square', '', '', false, false),
  ('the-temple-square', 'west', 'the-entrance-to-the-clerics-guild', '', '', false, false),
  ('the-entrance-hall-of-the-grunting-boar-inn', 'north', 'the-post-office', '', '', false, false),
  ('the-entrance-hall-of-the-grunting-boar-inn', 'east', 'the-grunting-boar', '', '', false, false),
  ('the-entrance-hall-of-the-grunting-boar-inn', 'west', 'the-temple-square', '', '', false, false),
  ('the-entrance-hall-of-the-grunting-boar-inn', 'up', 'the-reception', '', '', false, false),
  ('the-grunting-boar', 'west', 'the-entrance-hall-of-the-grunting-boar-inn', '', '', false, false),
  ('the-reception', 'north', 'the-cryogenic-center', '', '', false, false),
  ('the-reception', 'down', 'the-entrance-hall-of-the-grunting-boar-inn', '', '', false, false),
  ('the-bakery', 'south', 'main-street-2', '', '', false, false),
  ('the-general-store', 'south', 'main-street-3', '', '', false, false),
  ('the-weapon-shop', 'south', 'main-street-4', '', '', false, false),
  ('main-street', 'north', 'the-magic-shop', '', '', false, false),
  ('main-street', 'east', 'main-street-2', '', '', false, false),
  ('main-street', 'south', 'the-entrance-to-the-mages-guild', '', '', false, false),
  ('main-street', 'west', 'inside-the-west-gate-of-midgaard', '', '', false, false),
  ('main-street-2', 'north', 'the-bakery', '', '', false, false),
  ('main-street-2', 'east', 'market-square', '', '', false, false),
  ('main-street-2', 'south', 'the-armory', '', '', false, false),
  ('main-street-2', 'west', 'main-street', '', '', false, false),
  ('market-square', 'north', 'the-temple-square', '', '', false, false),
  ('market-square', 'east', 'main-street-3', '', '', false, false),
  ('market-square', 'south', 'the-common-square', '', '', false, false),
  ('market-square', 'west', 'main-street-2', '', '', false, false),
  ('main-street-3', 'north', 'the-general-store', '', '', false, false),
  ('main-street-3', 'east', 'main-street-4', '', '', false, false),
  ('main-street-3', 'south', 'the-pet-shop', '', '', false, false),
  ('main-street-3', 'west', 'market-square', '', '', false, false),
  ('main-street-4', 'north', 'the-weapon-shop', '', '', false, false),
  ('main-street-4', 'east', 'inside-the-east-gate-of-midgaard', '', '', false, false),
  ('main-street-4', 'south', 'the-entrance-hall-to-the-guild-of-swordsmen', '', '', false, false),
  ('main-street-4', 'west', 'main-street-3', '', '', false, false),
  ('the-entrance-to-the-mages-guild', 'north', 'main-street', '', '', false, false),
  ('the-entrance-to-the-mages-guild', 'south', 'the-mages-bar', '', '', false, false),
  ('the-mages-bar', 'north', 'the-entrance-to-the-mages-guild', '', '', false, false),
  ('the-mages-bar', 'east', 'the-mages-laboratory', '', '', false, false),
  ('the-mages-laboratory', 'west', 'the-mages-bar', '', '', false, false),
  ('the-armory', 'north', 'main-street-2', '', '', false, false),
  ('the-entrance-hall-to-the-guild-of-swordsmen', 'north', 'main-street-4', '', '', false, false),
  ('the-entrance-hall-to-the-guild-of-swordsmen', 'east', 'the-bar-of-swordsmen', '', '', false, false),
  ('the-bar-of-swordsmen', 'south', 'the-tournament-and-practice-yard', '', '', false, false),
  ('the-bar-of-swordsmen', 'west', 'the-entrance-hall-to-the-guild-of-swordsmen', '', '', false, false),
  ('the-tournament-and-practice-yard', 'north', 'the-bar-of-swordsmen', '', '', false, false),
  ('the-eastern-end-of-poor-alley', 'east', 'the-common-square', '', '', false, false),
  ('the-eastern-end-of-poor-alley', 'south', 'grubby-inn', '', '', false, false),
  ('the-eastern-end-of-poor-alley', 'west', 'poor-alley', '', '', false, false),
  ('the-common-square', 'north', 'market-square', '', '', false, false),
  ('the-common-square', 'east', 'the-dark-alley', '', '', false, false),
  ('the-common-square', 'south', 'the-dump', '', '', false, false),
  ('the-common-square', 'west', 'the-eastern-end-of-poor-alley', '', '', false, false),
  ('the-dark-alley', 'east', 'the-dark-alley-at-the-levee', '', '', false, false),
  ('the-dark-alley', 'south', 'the-entrance-hall-to-the-guild-of-thieves', '', '', false, false),
  ('the-dark-alley', 'west', 'the-common-square', '', '', false, false),
  ('the-entrance-hall-to-the-guild-of-thieves', 'north', 'the-dark-alley', '', '', false, false),
  ('the-entrance-hall-to-the-guild-of-thieves', 'east', 'the-thieves-bar', '', '', false, false),
  ('the-thieves-bar', 'south', 'the-secret-yard', '', '', false, false),
  ('the-thieves-bar', 'west', 'the-entrance-hall-to-the-guild-of-thieves', '', '', false, false),
  ('the-secret-yard', 'north', 'the-thieves-bar', '', '', false, false),
  ('the-dump', 'north', 'the-common-square', '', '', false, false),
  ('the-pet-shop', 'north', 'main-street-3', '', '', false, false),
  ('the-magic-shop', 'south', 'main-street', '', '', false, false),
  ('inside-the-west-gate-of-midgaard', 'east', 'main-street', '', '', false, false),
  ('inside-the-west-gate-of-midgaard', 'south', 'wall-road', '', '', false, false),
  ('inside-the-west-gate-of-midgaard', 'west', 'outside-the-west-gate-of-midgaard', '', '', false, false),
  ('inside-the-east-gate-of-midgaard', 'east', 'outside-the-east-gate-of-midgaard', '', '', false, false),
  ('inside-the-east-gate-of-midgaard', 'south', 'ye-olde-water-shoppe', '', '', false, false),
  ('inside-the-east-gate-of-midgaard', 'west', 'main-street-4', '', '', false, false),
  ('wall-road', 'north', 'inside-the-west-gate-of-midgaard', '', '', false, false),
  ('wall-road', 'south', 'wall-road-2', '', '', false, false),
  ('wall-road-2', 'north', 'wall-road', '', '', false, false),
  ('wall-road-2', 'east', 'poor-alley', '', '', false, false),
  ('wall-road-2', 'south', 'wall-road-3', '', '', false, false),
  ('poor-alley', 'east', 'the-eastern-end-of-poor-alley', '', '', false, false),
  ('poor-alley', 'west', 'wall-road-2', '', '', false, false),
  ('the-dark-alley-at-the-levee', 'east', 'the-eastern-end-of-the-alley', '', '', false, false),
  ('the-dark-alley-at-the-levee', 'south', 'the-levee', '', '', false, false),
  ('the-dark-alley-at-the-levee', 'west', 'the-dark-alley', '', '', false, false),
  ('the-eastern-end-of-the-alley', 'south', 'the-deserted-warehouse', '', '', false, false),
  ('the-eastern-end-of-the-alley', 'west', 'the-dark-alley-at-the-levee', '', '', false, false),
  ('wall-road-3', 'north', 'wall-road-2', '', '', false, false),
  ('wall-road-3', 'south', 'on-the-bridge', '', '', false, false),
  ('grubby-inn', 'north', 'the-eastern-end-of-poor-alley', '', '', false, false),
  ('the-levee', 'north', 'the-dark-alley-at-the-levee', '', '', false, false),
  ('the-deserted-warehouse', 'north', 'the-eastern-end-of-the-alley', '', '', false, false),
  ('on-the-bridge', 'north', 'wall-road-3', '', '', false, false),
  ('outside-the-west-gate-of-midgaard', 'east', 'inside-the-west-gate-of-midgaard', '', '', false, false),
  ('outside-the-east-gate-of-midgaard', 'west', 'inside-the-east-gate-of-midgaard', '', '', false, false),
  ('by-the-temple-altar', 'north', 'behind-the-temple-altar', '', '', false, false),
  ('by-the-temple-altar', 'south', 'the-temple-of-midgaard', '', '', false, false),
  ('ye-olde-water-shoppe', 'north', 'inside-the-east-gate-of-midgaard', '', '', false, false),
  ('behind-the-temple-altar', 'north', 'the-great-field-of-midgaard', '', '', false, false),
  ('behind-the-temple-altar', 'south', 'by-the-temple-altar', '', '', false, false),
  ('the-great-field-of-midgaard', 'north', 'the-great-field-of-midgaard-2', '', '', false, false),
  ('the-great-field-of-midgaard', 'south', 'behind-the-temple-altar', '', '', false, false),
  ('the-great-field-of-midgaard-2', 'north', 'the-great-field-of-midgaard-3', '', '', false, false),
  ('the-great-field-of-midgaard-2', 'south', 'the-great-field-of-midgaard', '', '', false, false),
  ('the-great-field-of-midgaard-2', 'west', 'the-dirt-path', '', '', false, false),
  ('the-post-office', 'south', 'the-entrance-hall-of-the-grunting-boar-inn', '', '', false, false),
  ('the-midgaard-donation-room', 'west', 'the-temple-of-midgaard', '', '', false, false),
  ('the-cryogenic-center', 'south', 'the-reception', '', '', false, false),
  ('the-great-field-of-midgaard-3', 'south', 'the-great-field-of-midgaard-2', '', '', false, false),
  ('the-dirt-path', 'east', 'the-great-field-of-midgaard-2', '', '', false, false)
) AS v(from_slug, direction, to_slug, target_zone, target_room, is_locked, is_hidden)
WHERE z.slug = 'midgaard'
ON CONFLICT (zone_id, from_room_slug, direction) DO NOTHING;

-- ── Cross-zone portal: Siltgate ↔ Midgaard ─────────────────
-- Siltgate city-gate (west) → Midgaard outside-the-west-gate-of-midgaard
-- Midgaard outside-the-west-gate-of-midgaard (west) → Siltgate city-gate

INSERT INTO zone_exits (zone_id, from_room_slug, direction, to_room_slug, target_zone_slug, target_room_slug, locked, hidden)
SELECT z.id, v.from_slug, v.direction, v.to_slug,
       NULLIF(v.target_zone, ''), NULLIF(v.target_room, ''),
       v.is_locked, v.is_hidden
FROM zones z, (VALUES
  ('city-gate', 'west', 'city-gate', 'midgaard', 'outside-the-west-gate-of-midgaard', false, false)
) AS v(from_slug, direction, to_slug, target_zone, target_room, is_locked, is_hidden)
WHERE z.slug = 'the-siltgate'
ON CONFLICT (zone_id, from_room_slug, direction) DO NOTHING;

INSERT INTO zone_exits (zone_id, from_room_slug, direction, to_room_slug, target_zone_slug, target_room_slug, locked, hidden)
SELECT z.id, v.from_slug, v.direction, v.to_slug,
       NULLIF(v.target_zone, ''), NULLIF(v.target_room, ''),
       v.is_locked, v.is_hidden
FROM zones z, (VALUES
  ('outside-the-west-gate-of-midgaard', 'west', 'outside-the-west-gate-of-midgaard', 'the-siltgate', 'city-gate', false, false)
) AS v(from_slug, direction, to_slug, target_zone, target_room, is_locked, is_hidden)
WHERE z.slug = 'midgaard'
ON CONFLICT (zone_id, from_room_slug, direction) DO NOTHING;

COMMIT;
