-- 011_bestiary_creatures.sql — Complete Laeral's Bestiary Implementation
-- Adds 71 new creatures and their loot items from docs/bestiary-design.md

-- ============================================================================
-- 1. Loot Item Definitions (New items for bestiary creatures)
-- ============================================================================

INSERT INTO item_definitions (id, name, type, tier, base_stats, base_durability, weight, description, soulbound, stackable, max_stack, status) VALUES
  ('scrap_metal_chunk', 'Scrap Metal Chunk', 'material', 'scrap', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('scavengers_shiv', 'Scavenger''s Shiv', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('tattered_scrap_vest', 'Tattered Scrap Vest', 'armour', 'scrap', '{"armour":2,"weight":5}', 40, 4, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('waterlogged_cloth', 'Waterlogged Cloth', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('corroded_trinket', 'Corroded Trinket', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('drowned_blade', 'Drowned Blade', 'weapon', 'common', '{"damage":6,"speed":1}', 30, 3, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('hollow_bone_shard', 'Hollow Bone Shard', 'material', 'sturdy', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('translucent_membrane', 'Translucent Membrane', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('stalker_claw', 'Stalker Claw', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('concrete_fragment', 'Concrete Fragment', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('rebar_club', 'Rebar Club', 'material', 'common', '{}', NULL, 5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('burial_shroud', 'Burial Shroud', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('razorwing_feather', 'Razorwing Feather', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('twisted_talon', 'Twisted Talon', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('scrap_prosthetic', 'Scrap Prosthetic', 'material', 'scrap', '{}', NULL, 6, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('brutes_cleaver', 'Brute''s Cleaver', 'material', 'common', '{}', NULL, 7, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('reinforced_scrap_plate', 'Reinforced Scrap Plate', 'armour', 'scrap', '{"armour":2,"weight":5}', 40, 8, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('echo_residue', 'Echo Residue', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('fragmentary_image', 'Fragmentary Image', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('despair_shard', 'Despair Shard', 'material', 'sturdy', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('structural_beam', 'Structural Beam', 'material', 'common', '{}', NULL, 15, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('colossus_heart', 'Colossus Heart', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('foundation_stone', 'Foundation Stone', 'material', 'common', '{}', NULL, 8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('fracture_shard', 'Fracture Shard', 'material', 'sturdy', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('phantom_glass', 'Phantom Glass', 'material', 'common', '{}', NULL, 0.8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('distortion_core', 'Distortion Core', 'material', 'anomalous', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('ember_core', 'Ember Core', 'material', 'anomalous', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('ash_cloak', 'Ash Cloak', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('wardens_brand', 'Warden''s Brand', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('rubblecrusted_vest', 'Rubble-Crusted Vest', 'armour', 'common', '{"armour":2,"weight":5}', 40, 5, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('sovereigns_crown', 'Sovereign''s Crown', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('dust_orb', 'Dust Orb', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('ruin_lords_mantle', 'Ruin Lord''s Mantle', 'material', 'common', '{}', NULL, 6, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_rubble_blade', 'Masterwork Rubble Blade', 'weapon', 'common', '{"damage":6,"speed":1}', 30, 8, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('anomalous_core_fragment', 'Anomalous Core Fragment', 'material', 'anomalous', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('echo_of_the_fall', 'Echo of the Fall', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('toxic_slime', 'Toxic Slime', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('crawler_shell', 'Crawler Shell', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('scuttler_carapace', 'Scuttler Carapace', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('metal_claw', 'Metal Claw', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('corroded_chain', 'Corroded Chain', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('waterlogged_fabric', 'Waterlogged Fabric', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('swimmers_weight', 'Swimmer''s Weight', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('drowned_knife', 'Drowned Knife', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('lamprey_tooth', 'Lamprey Tooth', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('mutant_tissue', 'Mutant Tissue', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('pressure_gland', 'Pressure Gland', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('abyssal_hide', 'Abyssal Hide', 'armour', 'common', '{"armour":2,"weight":5}', 40, 4, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('black_ichor', 'Black Ichor', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('sirens_vocal_cord', 'Siren''s Vocal Cord', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('corroded_crown', 'Corroded Crown', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('song_crystal', 'Song Crystal', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('lurker_fin', 'Lurker Fin', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('tidal_scale', 'Tidal Scale', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('drowning_claw', 'Drowning Claw', 'material', 'common', '{}', NULL, 2.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('eel_organ', 'Eel Organ', 'material', 'common', '{}', NULL, 0.8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('electric_spine', 'Electric Spine', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('conductor_fluid', 'Conductor Fluid', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('leviathan_scale', 'Leviathan Scale', 'material', 'common', '{}', NULL, 5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('spawn_heart', 'Spawn Heart', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('primordial_tooth', 'Primordial Tooth', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('void_heart', 'Void Heart', 'material', 'anomalous', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('pressure_sphere', 'Pressure Sphere', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('sovereigns_trident', 'Sovereign''s Trident', 'material', 'common', '{}', NULL, 6, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('coral_fragment', 'Coral Fragment', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('metalcoral_alloy', 'Metal-Coral Alloy', 'material', 'sturdy', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('amalgam_core', 'Amalgam Core', 'material', 'anomalous', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('choir_robe', 'Choir Robe', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('drowned_score', 'Drowned Score', 'material', 'anomalous', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('conductors_baton', 'Conductor''s Baton', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('harmony_crystal', 'Harmony Crystal', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_sirens_blade', 'Masterwork Siren''s Blade', 'weapon', 'common', '{"damage":6,"speed":1}', 30, 5, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('maw_tooth', 'Maw Tooth', 'material', 'common', '{}', NULL, 8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('abyssal_pearl', 'Abyssal Pearl', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('leviathan_hide', 'Leviathan Hide', 'armour', 'common', '{"armour":2,"weight":5}', 40, 10, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('anomalous_deep_core', 'Anomalous Deep Core', 'material', 'anomalous', '{}', NULL, 0.8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_trident_of_depths', 'Masterwork Trident of Depths', 'material', 'common', '{}', NULL, 7, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('toxic_tooth', 'Toxic Tooth', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('matted_fur', 'Matted Fur', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('mutant_hide', 'Mutant Hide', 'armour', 'common', '{"armour":2,"weight":5}', 40, 2, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('chemicalscarred_fang', 'Chemical-Scarred Fang', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('contaminated_collar', 'Contaminated Collar', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('slime_sample', 'Slime Sample', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('contaminated_core', 'Contaminated Core', 'material', 'anomalous', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('beetle_carapace', 'Beetle Carapace', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('rust_dust', 'Rust Dust', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('acid_gland', 'Acid Gland', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('spitter_hide', 'Spitter Hide', 'armour', 'common', '{"armour":2,"weight":5}', 40, 3, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('caustic_venom', 'Caustic Venom', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('hazmat_fabric', 'Hazmat Fabric', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('respirator_mask', 'Respirator Mask', 'armour', 'common', '{"armour":2,"weight":5}', 40, 2, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('chemical_filter', 'Chemical Filter', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('fungal_growth', 'Fungal Growth', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('infected_tissue', 'Infected Tissue', 'material', 'common', '{}', NULL, 0.8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('spore_pod', 'Spore Pod', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('chrome_scale', 'Chrome Scale', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('venom_sac', 'Venom Sac', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('serpent_fang', 'Serpent Fang', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('titan_flesh', 'Titan Flesh', 'material', 'common', '{}', NULL, 6, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('mutagenic_sample', 'Mutagenic Sample', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('chimeric_bone', 'Chimeric Bone', 'material', 'common', '{}', NULL, 5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('wraith_essence', 'Wraith Essence', 'material', 'refined', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('toxic_condensate', 'Toxic Condensate', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('phasing_residue', 'Phasing Residue', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('crystal_shard', 'Crystal Shard', 'material', 'sturdy', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('behemoth_core', 'Behemoth Core', 'material', 'anomalous', '{}', NULL, 2.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('chemical_lattice', 'Chemical Lattice', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('spillmothers_core', 'Spillmother''s Core', 'material', 'anomalous', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('primordial_sludge', 'Primordial Sludge', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_hazmat_armor', 'Masterwork Hazmat Armor', 'material', 'common', '{}', NULL, 12, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('anomalous_mutation_catalyst', 'Anomalous Mutation Catalyst', 'material', 'anomalous', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('toxic_crown', 'Toxic Crown', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('genesis_sample', 'Genesis Sample', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('thorn_barb', 'Thorn Barb', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('vine_fiber', 'Vine Fiber', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('moss_pelt', 'Moss Pelt', 'material', 'common', '{}', NULL, 2.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('vinewrapped_antler', 'Vine-Wrapped Antler', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('lichen_sample', 'Lichen Sample', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('spore_sample', 'Spore Sample', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('pod_membrane', 'Pod Membrane', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('root_tendril', 'Root Tendril', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('wooden_heart', 'Wooden Heart', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('bark_armor', 'Bark Armor', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('bloom_petal', 'Bloom Petal', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('beast_hide', 'Beast Hide', 'armour', 'common', '{"armour":2,"weight":5}', 40, 4, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('pollen_sac', 'Pollen Sac', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('fungal_mass', 'Fungal Mass', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('spore_core', 'Spore Core', 'material', 'anomalous', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('brute_spore', 'Brute Spore', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('vine_whip', 'Vine Whip', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('chlorophyll_extract', 'Chlorophyll Extract', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('camouflage_leaf', 'Camouflage Leaf', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('wraith_pollen', 'Wraith Pollen', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('spirit_essence', 'Spirit Essence', 'material', 'refined', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('bloom_crystal', 'Bloom Crystal', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('titan_heartwood', 'Titan Heartwood', 'material', 'common', '{}', NULL, 8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('living_bark', 'Living Bark', 'material', 'common', '{}', NULL, 5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('primordial_sap', 'Primordial Sap', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('sovereign_spore', 'Sovereign Spore', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('network_core', 'Network Core', 'material', 'anomalous', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('fungal_crown', 'Fungal Crown', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('predator_fang', 'Predator Fang', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('verdant_hide', 'Verdant Hide', 'armour', 'common', '{"armour":2,"weight":5}', 40, 6, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('apex_claw', 'Apex Claw', 'material', 'common', '{}', NULL, 2.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('mothers_seed', 'Mother''s Seed', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('primordial_bloom', 'Primordial Bloom', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_thornmail', 'Masterwork Thornmail', 'material', 'common', '{}', NULL, 10, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('anomalous_growth_shard', 'Anomalous Growth Shard', 'material', 'sturdy', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('verdant_crown', 'Verdant Crown', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('genesis_pollen', 'Genesis Pollen', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('scrap_tool', 'Scrap Tool', 'material', 'scrap', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('metal_shaving', 'Metal Shaving', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('gremlin_trinket', 'Gremlin Trinket', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('damaged_circuit', 'Damaged Circuit', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('drone_casing', 'Drone Casing', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('power_cell', 'Power Cell', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('workers_tool', 'Worker''s Tool', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('rusted_plate', 'Rusted Plate', 'armour', 'common', '{"armour":2,"weight":5}', 40, 3, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('id_badge', 'ID Badge', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('oil_sample', 'Oil Sample', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('sentry_plating', 'Sentry Plating', 'material', 'common', '{}', NULL, 5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('targeting_module', 'Targeting Module', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('power_core', 'Power Core', 'material', 'anomalous', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('shredder_blade', 'Shredder Blade', 'weapon', 'common', '{"damage":6,"speed":1}', 30, 3, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('hydraulic_fluid', 'Hydraulic Fluid', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('motor_assembly', 'Motor Assembly', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('welding_torch', 'Welding Torch', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('arc_capacitor', 'Arc Capacitor', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('metal_slag', 'Metal Slag', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('data_fragment', 'Data Fragment', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('holographic_residue', 'Holographic Residue', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('logic_bomb', 'Logic Bomb', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('demolisher_arm', 'Demolisher Arm', 'material', 'common', '{}', NULL, 12, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('reinforced_plating', 'Reinforced Plating', 'material', 'common', '{}', NULL, 8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('reactor_core', 'Reactor Core', 'material', 'anomalous', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('nano_sample', 'Nano Sample', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('molecular_disassembler', 'Molecular Disassembler', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('replication_matrix', 'Replication Matrix', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('ai_core', 'AI Core', 'material', 'anomalous', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('quantum_processor', 'Quantum Processor', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('command_override', 'Command Override', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('factory_heart', 'Factory Heart', 'material', 'common', '{}', NULL, 5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_assembly_suit', 'Masterwork Assembly Suit', 'material', 'common', '{}', NULL, 15, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('anomalous_manufacturing_core', 'Anomalous Manufacturing Core', 'material', 'anomalous', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('production_override', 'Production Override', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('eternal_engine', 'Eternal Engine', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('blueprint_archive', 'Blueprint Archive', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_hydraulic_hammer', 'Masterwork Hydraulic Hammer', 'material', 'common', '{}', NULL, 10, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('roach_carapace', 'Roach Carapace', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('glowing_gland', 'Glowing Gland', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('tattered_rad_suit', 'Tattered Rad Suit', 'material', 'scrap', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('makeshift_weapon', 'Makeshift Weapon', 'weapon', 'common', '{"damage":6,"speed":1}', 30, 2.5, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('rad_pills', 'Rad Pills', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('radioactive_dust', 'Radioactive Dust', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('crystallized_fallout', 'Crystallized Fallout', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('hound_pelt', 'Hound Pelt', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('radscarred_fang', 'Rad-Scarred Fang', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('hound_collar', 'Hound Collar', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('ghoul_flesh', 'Ghoul Flesh', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('gamma_organ', 'Gamma Organ', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('prewar_artifact', 'Pre-War Artifact', 'material', 'common', '{}', NULL, 0.8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('scorched_hide', 'Scorched Hide', 'armour', 'common', '{"armour":2,"weight":5}', 40, 5, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('behemoth_bone', 'Behemoth Bone', 'material', 'common', '{}', NULL, 6, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('mutation_sample', 'Mutation Sample', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('wyrm_scale', 'Wyrm Scale', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('venom_gland', 'Venom Gland', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('burrowing_claw', 'Burrowing Claw', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('storm_core', 'Storm Core', 'material', 'anomalous', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('lightning_fragment', 'Lightning Fragment', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('elemental_essence', 'Elemental Essence', 'material', 'refined', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('reactor_core_fragment', 'Reactor Core Fragment', 'material', 'anomalous', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('atomic_heart', 'Atomic Heart', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('enriched_uranium', 'Enriched Uranium', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('phantom_essence', 'Phantom Essence', 'material', 'refined', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('final_memory', 'Final Memory', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('spectral_residue', 'Spectral Residue', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('apex_tissue', 'Apex Tissue', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('mutation_core', 'Mutation Core', 'material', 'anomalous', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('evolved_claw', 'Evolved Claw', 'material', 'common', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('kings_crown', 'King''s Crown', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('nuclear_scepter', 'Nuclear Scepter', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_radiation_suit', 'Masterwork Radiation Suit', 'material', 'common', '{}', NULL, 14, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('anomalous_isotope', 'Anomalous Isotope', 'material', 'anomalous', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('blast_remnant', 'Blast Remnant', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('gamma_crown', 'Gamma Crown', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('echo_of_zero_hour', 'Echo of Zero Hour', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('shadow_wisp', 'Shadow Wisp', 'material', 'common', '{}', NULL, 0.1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('void_tooth', 'Void Tooth', 'material', 'anomalous', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('shadow_cloth', 'Shadow Cloth', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('gloom_essence', 'Gloom Essence', 'material', 'refined', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('void_shard', 'Void Shard', 'material', 'sturdy', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('pale_flesh', 'Pale Flesh', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('drained_bone', 'Drained Bone', 'material', 'common', '{}', NULL, 0.8, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('faded_garment', 'Faded Garment', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('wisp_core', 'Wisp Core', 'material', 'anomalous', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('shadow_flame', 'Shadow Flame', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('void_pelt', 'Void Pelt', 'material', 'anomalous', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('hounds_fang', 'Hound''s Fang', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('shadow_heart', 'Shadow Heart', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('eclipse_shard', 'Eclipse Shard', 'material', 'sturdy', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('fear_crystal', 'Fear Crystal', 'material', 'common', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('shadow_silk', 'Shadow Silk', 'material', 'common', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('weaver_fang', 'Weaver Fang', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('darkness_web', 'Darkness Web', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('sentinel_armor', 'Sentinel Armor', 'material', 'common', '{}', NULL, 6, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('oath_blade', 'Oath Blade', 'weapon', 'common', '{"damage":6,"speed":1}', 30, 4, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('vigil_stone', 'Vigil Stone', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('abyss_core', 'Abyss Core', 'material', 'anomalous', '{}', NULL, 3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('void_plate', 'Void Plate', 'armour', 'anomalous', '{"armour":2,"weight":5}', 40, 7, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('darkness_incarnate', 'Darkness Incarnate', 'material', 'common', '{}', NULL, 2, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('nightmare_essence', 'Nightmare Essence', 'material', 'refined', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('fear_shard', 'Fear Shard', 'material', 'sturdy', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('dream_residue', 'Dream Residue', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('sovereigns_cloak', 'Sovereign''s Cloak', 'material', 'common', '{}', NULL, 4, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('shadow_crown', 'Shadow Crown', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('void_dagger', 'Void Dagger', 'weapon', 'anomalous', '{"damage":6,"speed":1}', 30, 2, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('fragment_of_nothing', 'Fragment of Nothing', 'material', 'common', '{}', NULL, 1, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('masterwork_shadow_armor', 'Masterwork Shadow Armor', 'material', 'common', '{}', NULL, 13, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('anomalous_void_core', 'Anomalous Void Core', 'material', 'anomalous', '{}', NULL, 0.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('darkness_absolute', 'Darkness Absolute', 'material', 'common', '{}', NULL, 0.3, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('crown_of_night', 'Crown of Night', 'material', 'common', '{}', NULL, 1.5, 'Material dropped by dungeon creatures.', false, true, 20, 'published'),
  ('extinction_blade', 'Extinction Blade', 'weapon', 'common', '{"damage":6,"speed":1}', 30, 5, 'Material dropped by dungeon creatures.', false, false, 1, 'published'),
  ('echo_of_the_void', 'Echo of the Void', 'material', 'anomalous', '{}', NULL, 0.2, 'Material dropped by dungeon creatures.', false, true, 20, 'published')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 2. Creature Definitions (81 new creatures from bestiary)
-- ============================================================================

INSERT INTO creature_definitions (type, name, slug, description, max_hp, attack, defence, armour, agility, min_count, max_count, preferred_rooms, forbidden_rooms, idle_ticks_min, idle_ticks_max, flee_threshold, loot_table, aggressive, room_description, status)
VALUES
  ('concrete_shambler', 'Concrete Shambler', 'concrete_shambler', 'Humanoid figures encrusted with concrete and rebar. Each step cracks the floor beneath them. They were buried in the collapse and they remember.',
   90, 22, 9, 12, 1, 1, 2, '{chamber}', '{entry}', 100, 400, 0.25,
   '[{"itemId":"concrete_fragment","dropWeight":60},{"itemId":"rebar_club","dropWeight":30},{"itemId":"burial_shroud","dropWeight":10}]'::jsonb,
   true, 'A concrete shambler drags itself forward, leaving cracks in its wake.', 'published'),

  ('razorwing_swarm', 'Razorwing Swarm', 'razorwing_swarm', 'Mutated pigeons with metallic feathers sharp as knives. They descend in clouds, slashing and pecking.',
   70, 18, 8, 5, 9, 3, 6, '{chamber}', '{boss}', 300, 1200, 0.4,
   '[{"itemId":"razorwing_feather","dropWeight":85},{"itemId":"twisted_talon","dropWeight":15}]'::jsonb,
   true, 'Razorwings circle overhead, their metallic feathers glinting in the dim light.', 'published'),

  ('scrap_brute', 'Scrap Brute', 'scrap_brute', 'Massive scavengers who''ve replaced lost limbs with scrap metal prosthetics. They charge into battle with berserker rage.',
   110, 26, 7, 10, 3, 1, 2, '{chamber}', '{entry}', 100, 400, 0.15,
   '[{"itemId":"scrap_prosthetic","dropWeight":40},{"itemId":"brutes_cleaver","dropWeight":35},{"itemId":"reinforced_scrap_plate","dropWeight":25}]'::jsonb,
   true, 'A scrap brute stands guard, its metal limbs grinding with each movement.', 'published'),

  ('memory_echo', 'Memory Echo', 'memory_echo', 'Translucent humanoid figures that flicker in and out of existence. Psychic imprints of those who died in the collapse. They attack with waves of despair.',
   65, 24, 11, 3, 5, 1, 3, '{chamber}', '{entry}', 100, 600, 0.25,
   '[{"itemId":"echo_residue","dropWeight":70},{"itemId":"fragmentary_image","dropWeight":20},{"itemId":"despair_shard","dropWeight":10}]'::jsonb,
   true, 'Memory echoes drift through the space, their faces filled with frozen terror.', 'published'),

  ('ruin_colossus', 'Ruin Colossus', 'ruin_colossus', 'A walking building. Dozens of floors compressed into a vaguely humanoid shape. Each punch brings down a rain of masonry.',
   200, 45, 18, 25, 1, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.25,
   '[{"itemId":"structural_beam","dropWeight":40},{"itemId":"colossus_heart","dropWeight":30},{"itemId":"foundation_stone","dropWeight":30}]'::jsonb,
   true, 'A ruin colossus stands here, a monument to destruction given terrible life.', 'published'),

  ('fracture_phantom', 'Fracture Phantom', 'fracture_phantom', 'A figure made of broken glass and twisted light. It phases through walls and strikes from impossible angles.',
   140, 50, 22, 8, 12, 1, 2, '{chamber}', '{entry}', 100, 400, 0.3,
   '[{"itemId":"fracture_shard","dropWeight":60},{"itemId":"phantom_glass","dropWeight":30},{"itemId":"distortion_core","dropWeight":10}]'::jsonb,
   true, 'A fracture phantom shifts through broken space, leaving glass trails in the air.', 'published'),

  ('ash_warden', 'Ash Warden', 'ash_warden', 'Robed figures composed entirely of ash and ember. They were firefighters once. Now they spread flame with a zealot''s devotion.',
   125, 42, 16, 12, 6, 1, 2, '{chamber}', '{entry}', 100, 400, 0.2,
   '[{"itemId":"ember_core","dropWeight":50},{"itemId":"ash_cloak","dropWeight":30},{"itemId":"wardens_brand","dropWeight":20}]'::jsonb,
   true, 'An ash warden stands in perpetual conflagration, embers drifting from its robes.', 'published'),

  ('the_sovereign_of_dust', 'The Sovereign of Dust', 'the_sovereign_of_dust', 'A towering figure wreathed in swirling debris. It commands the ruins themselves, calling down avalanches of rubble and commanding lesser creatures.',
   350, 55, 20, 18, 4, 1, 1, '{boss}', '{}', 100, 200, 0.25,
   '[{"itemId":"sovereigns_crown","dropWeight":20},{"itemId":"dust_orb","dropWeight":25},{"itemId":"ruin_lords_mantle","dropWeight":20},{"itemId":"masterwork_rubble_blade","dropWeight":15},{"itemId":"anomalous_core_fragment","dropWeight":10},{"itemId":"echo_of_the_fall","dropWeight":10}]'::jsonb,
   true, 'The Sovereign of Dust hovers above broken ground, debris swirling in impossible patterns.', 'published'),

  ('sludge_crawler', 'Sludge Crawler', 'sludge_crawler', 'Slug-like creatures the size of house cats, covered in toxic slime. They leave acidic trails and cluster around organic matter.',
   20, 6, 2, 1, 3, 3, 6, '{corridor}', '{boss}', 300, 1200, 0.5,
   '[{"itemId":"toxic_slime","dropWeight":75},{"itemId":"crawler_shell","dropWeight":25}]'::jsonb,
   false, 'Sludge crawlers inch across the wet floor, leaving glistening trails.', 'published'),

  ('flood_scuttler', 'Flood Scuttler', 'flood_scuttler', 'Crab-like creatures with rusted metal shells scavenged from sunken infrastructure. They skitter across walls and ceilings.',
   28, 9, 4, 6, 8, 2, 4, '{corridor}', '{entry}', 200, 800, 0.35,
   '[{"itemId":"scuttler_carapace","dropWeight":60},{"itemId":"metal_claw","dropWeight":30},{"itemId":"corroded_chain","dropWeight":10}]'::jsonb,
   true, 'Flood scuttlers cling to the walls, their metal shells clicking.', 'published'),

  ('drowned_swimmer', 'Drowned Swimmer', 'drowned_swimmer', 'Waterlogged corpses that retained enough muscle memory to swim. They lunge from dark water with horrifying speed.',
   40, 11, 3, 2, 7, 1, 3, '{chamber}', '{entry}', 100, 600, 0.15,
   '[{"itemId":"waterlogged_fabric","dropWeight":70},{"itemId":"swimmers_weight","dropWeight":20},{"itemId":"drowned_knife","dropWeight":10}]'::jsonb,
   true, 'A drowned swimmer floats just below the surface, watching.', 'published'),

  ('lamprey_mass', 'Lamprey Mass', 'lamprey_mass', 'A writhing ball of mutated lampreys fused together. They attach to victims and drain blood with horrifying efficiency.',
   25, 8, 2, 0, 6, 2, 4, '{chamber}', '{boss}', 200, 800, 0.4,
   '[{"itemId":"lamprey_tooth","dropWeight":80},{"itemId":"mutant_tissue","dropWeight":20}]'::jsonb,
   true, 'A lamprey mass undulates in the shallows, mouths opening and closing.', 'published'),

  ('pressure_horror', 'Pressure Horror', 'pressure_horror', 'Deep-water predators adapted to crushing depths. Their bodies weep black fluid and their strikes carry the weight of the abyss.',
   95, 24, 10, 14, 4, 1, 2, '{chamber}', '{entry}', 100, 400, 0.1,
   '[{"itemId":"pressure_gland","dropWeight":50},{"itemId":"abyssal_hide","dropWeight":35},{"itemId":"black_ichor","dropWeight":15}]'::jsonb,
   true, 'A pressure horror looms in the deep water, black fluid trailing from its form.', 'published'),

  ('rust_siren', 'Rust Siren', 'rust_siren', 'Humanoid figures corroded beyond recognition, their voices echo through flooded halls with hypnotic resonance. They sing songs of drowning.',
   70, 20, 12, 8, 5, 1, 3, '{chamber}', '{entry}', 100, 600, 0.25,
   '[{"itemId":"sirens_vocal_cord","dropWeight":60},{"itemId":"corroded_crown","dropWeight":30},{"itemId":"song_crystal","dropWeight":10}]'::jsonb,
   true, 'A rust siren stands in the flood, its haunting song echoing.', 'published'),

  ('tidal_lurker', 'Tidal Lurker', 'tidal_lurker', 'Amphibious predators that move with the water flow. They strike from flooded alcoves and drag prey into the depths.',
   85, 27, 9, 7, 10, 1, 2, '{corridor}', '{entry}', 100, 400, 0.3,
   '[{"itemId":"lurker_fin","dropWeight":60},{"itemId":"tidal_scale","dropWeight":30},{"itemId":"drowning_claw","dropWeight":10}]'::jsonb,
   true, 'A tidal lurker moves through the water, nearly invisible.', 'published'),

  ('electrical_eel_cluster', 'Electrical Eel Cluster', 'electrical_eel_cluster', 'Mutated eels that generate bio-electricity. They swim in synchronized schools and discharge in devastating pulses.',
   60, 22, 7, 4, 9, 3, 5, '{chamber}', '{boss}', 300, 1000, 0.45,
   '[{"itemId":"eel_organ","dropWeight":70},{"itemId":"electric_spine","dropWeight":25},{"itemId":"conductor_fluid","dropWeight":5}]'::jsonb,
   true, 'Electrical eels swim in tight formation, crackling with bio-energy.', 'published'),

  ('leviathan_spawn', 'Leviathan Spawn', 'leviathan_spawn', 'Massive serpentine creatures that dwarf humans. They are pieces of something larger, still searching for the rest of themselves.',
   180, 48, 16, 22, 5, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.25,
   '[{"itemId":"leviathan_scale","dropWeight":50},{"itemId":"spawn_heart","dropWeight":30},{"itemId":"primordial_tooth","dropWeight":20}]'::jsonb,
   true, 'A leviathan spawn fills the chamber, its bulk displacing water.', 'published'),

  ('depth_sovereign', 'Depth Sovereign', 'depth_sovereign', 'A being of pure pressure and darkness. It manifests as a humanoid void surrounded by crushing water. Those who hear its voice feel the weight of the ocean.',
   150, 52, 20, 15, 7, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.2,
   '[{"itemId":"void_heart","dropWeight":40},{"itemId":"pressure_sphere","dropWeight":35},{"itemId":"sovereigns_trident","dropWeight":25}]'::jsonb,
   true, 'The depth sovereign hovers in absolute darkness, water bending around it.', 'published'),

  ('coral_amalgam', 'Coral Amalgam', 'coral_amalgam', 'A fusion of coral, metal, and organic matter grown into a vaguely humanoid shape. It tears through obstacles with relentless fury.',
   220, 56, 14, 28, 2, 1, 1, '{chamber}', '{entry}', 100, 200, 0.05,
   '[{"itemId":"coral_fragment","dropWeight":55},{"itemId":"metalcoral_alloy","dropWeight":30},{"itemId":"amalgam_core","dropWeight":15}]'::jsonb,
   true, 'A coral amalgam stands immobile, growths spreading across walls.', 'published'),

  ('the_drowned_choir', 'The Drowned Choir', 'the_drowned_choir', 'Seven figures standing in a circle, forever singing. They were musicians once, now they are an ensemble of drowning and despair.',
   280, 35, 15, 12, 3, 1, 1, '{boss}', '{}', 100, 200, 0.25,
   '[{"itemId":"choir_robe","dropWeight":30},{"itemId":"drowned_score","dropWeight":25},{"itemId":"conductors_baton","dropWeight":20},{"itemId":"harmony_crystal","dropWeight":15},{"itemId":"masterwork_sirens_blade","dropWeight":10}]'::jsonb,
   true, 'The Drowned Choir stands in formation, their eternal song filling the chamber.', 'published'),

  ('the_abyssal_maw', 'The Abyssal Maw', 'the_abyssal_maw', 'Something vast lurks in the deepest flooded sections. You never see all of it — just the mouth. The mouth is enough.',
   400, 70, 25, 35, 2, 1, 1, '{boss}', '{}', 100, 200, 0.25,
   '[{"itemId":"maw_tooth","dropWeight":35},{"itemId":"abyssal_pearl","dropWeight":25},{"itemId":"leviathan_hide","dropWeight":20},{"itemId":"anomalous_deep_core","dropWeight":10},{"itemId":"masterwork_trident_of_depths","dropWeight":10}]'::jsonb,
   true, 'The Abyssal Maw waits in water too deep to see bottom, only teeth visible.', 'published'),

  ('bile_rat', 'Bile Rat', 'bile_rat', 'Rats mutated by toxic exposure. Their fur is matted with chemical residue and their bite carries burning venom.',
   18, 7, 2, 1, 8, 3, 6, '{corridor}', '{boss}', 300, 1200, 0.4,
   '[{"itemId":"toxic_tooth","dropWeight":80},{"itemId":"matted_fur","dropWeight":20}]'::jsonb,
   true, 'Bile rats scurry through toxic puddles, leaving smoking trails.', 'published'),

  ('mutant_hound', 'Mutant Hound', 'mutant_hound', 'Dogs transformed by chemical exposure. Their skin is patchy and raw, their eyes milky, but they retain pack instincts.',
   32, 10, 3, 2, 7, 2, 4, '{chamber}', '{boss}', 200, 800, 0.25,
   '[{"itemId":"mutant_hide","dropWeight":65},{"itemId":"chemicalscarred_fang","dropWeight":30},{"itemId":"contaminated_collar","dropWeight":5}]'::jsonb,
   true, 'Mutant hounds prowl here, their breathing labored and wet.', 'published'),

  ('slime_creeper', 'Slime Creeper', 'slime_creeper', 'Amorphous blobs of industrial waste given rudimentary intelligence. They ooze through vents and drains.',
   25, 8, 1, 0, 4, 1, 3, '{corridor}', '{entry}', 100, 600, 0.6,
   '[{"itemId":"slime_sample","dropWeight":85},{"itemId":"contaminated_core","dropWeight":15}]'::jsonb,
   false, 'A slime creeper flows across the floor, leaving caustic residue.', 'published'),

  ('rust_beetle', 'Rust Beetle', 'rust_beetle', 'Metallic insects that feed on corroded metal. They swarm in clouds and strip equipment to rust in seconds.',
   12, 5, 3, 4, 9, 4, 8, '{chamber}', '{boss}', 400, 1600, 0.5,
   '[{"itemId":"beetle_carapace","dropWeight":90},{"itemId":"rust_dust","dropWeight":10}]'::jsonb,
   true, 'Rust beetles click and swarm, their metallic wings buzzing.', 'published'),

  ('acid_spitter', 'Acid Spitter', 'acid_spitter', 'Bloated creatures that store industrial acids in throat sacs. They spray corrosive streams from a distance.',
   75, 20, 6, 8, 5, 1, 3, '{chamber}', '{entry}', 100, 600, 0.35,
   '[{"itemId":"acid_gland","dropWeight":60},{"itemId":"spitter_hide","dropWeight":30},{"itemId":"caustic_venom","dropWeight":10}]'::jsonb,
   true, 'An acid spitter crouches low, throat sac pulsing.', 'published'),

  ('hazmat_horror', 'Hazmat Horror', 'hazmat_horror', 'Figures in sealed hazmat suits fused with their wearer. The suits still function, protecting something that should have died decades ago.',
   105, 26, 11, 16, 3, 1, 2, '{chamber}', '{entry}', 100, 400, 0.1,
   '[{"itemId":"hazmat_fabric","dropWeight":50},{"itemId":"respirator_mask","dropWeight":35},{"itemId":"chemical_filter","dropWeight":15}]'::jsonb,
   true, 'A hazmat horror lurches forward, suit hissing with leaks.', 'published'),

  ('fungal_shambler', 'Fungal Shambler', 'fungal_shambler', 'Humans overgrown with toxic fungus. The mycelium network puppets the corpse with terrifying strength.',
   90, 24, 8, 10, 4, 1, 2, '{chamber}', '{entry}', 100, 400, 0.15,
   '[{"itemId":"fungal_growth","dropWeight":60},{"itemId":"infected_tissue","dropWeight":30},{"itemId":"spore_pod","dropWeight":10}]'::jsonb,
   true, 'A fungal shambler stands covered in pulsing growths.', 'published'),

  ('chrome_serpent', 'Chrome Serpent', 'chrome_serpent', 'Snake-like creatures with metallic scales that reflect chemical rainbows. Their bite delivers neurotoxins.',
   80, 23, 10, 12, 11, 1, 2, '{corridor}', '{entry}', 100, 400, 0.3,
   '[{"itemId":"chrome_scale","dropWeight":65},{"itemId":"venom_sac","dropWeight":25},{"itemId":"serpent_fang","dropWeight":10}]'::jsonb,
   true, 'A chrome serpent slithers through chemical pools, scales gleaming.', 'published'),

  ('mutation_titan', 'Mutation Titan', 'mutation_titan', 'A massive creature born from chemical chaos. Every part of its body is from a different species, stitched together by mutagenic forces.',
   210, 50, 17, 26, 3, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.25,
   '[{"itemId":"titan_flesh","dropWeight":45},{"itemId":"mutagenic_sample","dropWeight":35},{"itemId":"chimeric_bone","dropWeight":20}]'::jsonb,
   true, 'A mutation titan fills the space, its form defying biology.', 'published'),

  ('toxic_wraith', 'Toxic Wraith', 'toxic_wraith', 'A semi-corporeal entity formed from concentrated chemical fumes. It phases through solid matter and leaves toxic trails.',
   130, 46, 19, 10, 8, 1, 2, '{chamber}', '{entry}', 100, 400, 0.25,
   '[{"itemId":"wraith_essence","dropWeight":60},{"itemId":"toxic_condensate","dropWeight":30},{"itemId":"phasing_residue","dropWeight":10}]'::jsonb,
   true, 'A toxic wraith drifts through the air, leaving green trails.', 'published'),

  ('crystalline_behemoth', 'Crystalline Behemoth', 'crystalline_behemoth', 'A creature encased in crystallized chemical compounds. Each movement shatters and reforms its shell in cascading waves.',
   240, 52, 20, 32, 2, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.05,
   '[{"itemId":"crystal_shard","dropWeight":55},{"itemId":"behemoth_core","dropWeight":30},{"itemId":"chemical_lattice","dropWeight":15}]'::jsonb,
   true, 'A crystalline behemoth stands motionless, refracting toxic light.', 'published'),

  ('the_spillmother', 'The Spillmother', 'the_spillmother', 'The heart of the contamination zone. A vast pool of toxic sludge given terrible purpose. It births lesser creatures and commands them all.',
   320, 60, 22, 20, 4, 1, 1, '{boss}', '{}', 100, 200, 0.25,
   '[{"itemId":"spillmothers_core","dropWeight":25},{"itemId":"primordial_sludge","dropWeight":25},{"itemId":"masterwork_hazmat_armor","dropWeight":20},{"itemId":"anomalous_mutation_catalyst","dropWeight":15},{"itemId":"toxic_crown","dropWeight":10},{"itemId":"genesis_sample","dropWeight":5}]'::jsonb,
   true, 'The Spillmother churns in its toxic pool, a sentient spill.', 'published'),

  ('thorn_creeper', 'Thorn Creeper', 'thorn_creeper', 'Animated vines covered in barbs. They lash out at anything that moves, dragging prey into thorny masses.',
   20, 6, 2, 1, 5, 3, 5, '{chamber}', '{boss}', 300, 1000, 0.25,
   '[{"itemId":"thorn_barb","dropWeight":85},{"itemId":"vine_fiber","dropWeight":15}]'::jsonb,
   true, 'Thorn creepers writhe across walls and floor, barbs gleaming.', 'published'),

  ('moss_walker', 'Moss Walker', 'moss_walker', 'Deer overgrown with moss and lichen. They charge intruders with surprising aggression, antlers wrapped in vines.',
   35, 9, 3, 3, 7, 1, 3, '{chamber}', '{boss}', 100, 600, 0.3,
   '[{"itemId":"moss_pelt","dropWeight":65},{"itemId":"vinewrapped_antler","dropWeight":25},{"itemId":"lichen_sample","dropWeight":10}]'::jsonb,
   true, 'A moss walker stands alert, vegetation rustling with each breath.', 'published'),

  ('spore_pod', 'Spore Pod', 'spore_pod', 'Bulbous fungal growths that burst when approached. They release clouds of spores that cause hallucinations and respiratory distress.',
   15, 7, 1, 0, 0, 2, 4, '{chamber}', '{entry}', 200, 800, 0.25,
   '[{"itemId":"spore_sample","dropWeight":90},{"itemId":"pod_membrane","dropWeight":10}]'::jsonb,
   false, 'Spore pods cluster in corners, membrane pulsing.', 'published'),

  ('root_horror', 'Root Horror', 'root_horror', 'Humanoid figures entangled in tree roots. The roots move them like puppets, shambling through the ruins.',
   30, 8, 3, 4, 4, 1, 3, '{corridor}', '{entry}', 100, 600, 0.2,
   '[{"itemId":"root_tendril","dropWeight":70},{"itemId":"wooden_heart","dropWeight":20},{"itemId":"bark_armor","dropWeight":10}]'::jsonb,
   true, 'A root horror shambles forward, dragged by living roots.', 'published'),

  ('bloom_beast', 'Bloom Beast', 'bloom_beast', 'Large predators with flowers growing from their flesh. The blooms release pollen that attracts prey and masks their scent.',
   95, 25, 8, 11, 6, 1, 2, '{chamber}', '{entry}', 100, 400, 0.2,
   '[{"itemId":"bloom_petal","dropWeight":60},{"itemId":"beast_hide","dropWeight":30},{"itemId":"pollen_sac","dropWeight":10}]'::jsonb,
   true, 'A bloom beast prowls, flowers swaying with each movement.', 'published'),

  ('fungal_brute', 'Fungal Brute', 'fungal_brute', 'Massive humanoid shapes entirely composed of fungal matter. They spread spores with every blow and regenerate constantly.',
   110, 22, 10, 14, 3, 1, 2, '{chamber}', '{entry}', 100, 400, 0.05,
   '[{"itemId":"fungal_mass","dropWeight":60},{"itemId":"spore_core","dropWeight":30},{"itemId":"brute_spore","dropWeight":10}]'::jsonb,
   true, 'A fungal brute stands like a monument, spores drifting from its body.', 'published'),

  ('vine_stalker', 'Vine Stalker', 'vine_stalker', 'Predators that blend perfectly with overgrown vegetation. Their bodies are living vines that strike from concealment.',
   75, 27, 9, 7, 10, 1, 2, '{corridor}', '{entry}', 100, 400, 0.35,
   '[{"itemId":"vine_whip","dropWeight":60},{"itemId":"chlorophyll_extract","dropWeight":30},{"itemId":"camouflage_leaf","dropWeight":10}]'::jsonb,
   true, 'Somewhere among the vegetation, a vine stalker waits.', 'published'),

  ('pollen_wraith', 'Pollen Wraith', 'pollen_wraith', 'Semi-corporeal entities made of concentrated pollen and plant spirits. They drift through overgrown areas spreading madness.',
   65, 20, 12, 6, 7, 1, 3, '{chamber}', '{entry}', 100, 600, 0.3,
   '[{"itemId":"wraith_pollen","dropWeight":70},{"itemId":"spirit_essence","dropWeight":25},{"itemId":"bloom_crystal","dropWeight":5}]'::jsonb,
   true, 'A pollen wraith drifts lazily, leaving golden trails.', 'published'),

  ('forest_titan', 'Forest Titan', 'forest_titan', 'A walking tree of immense size, animated by the collective will of the forest. It defends the overgrown zones with ancient fury.',
   230, 48, 16, 30, 2, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.25,
   '[{"itemId":"titan_heartwood","dropWeight":50},{"itemId":"living_bark","dropWeight":35},{"itemId":"primordial_sap","dropWeight":15}]'::jsonb,
   true, 'A forest titan towers overhead, its branches scraping the ceiling.', 'published'),

  ('mycelium_sovereign', 'Mycelium Sovereign', 'mycelium_sovereign', 'The consciousness of an entire fungal network given form. It commands all lesser fungal creatures and spreads its domain constantly.',
   160, 44, 21, 16, 5, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.15,
   '[{"itemId":"sovereign_spore","dropWeight":45},{"itemId":"network_core","dropWeight":35},{"itemId":"fungal_crown","dropWeight":20}]'::jsonb,
   true, 'The mycelium sovereign pulses with bioluminescence, connected to everything.', 'published'),

  ('verdant_predator', 'Verdant Predator', 'verdant_predator', 'The apex hunter of overgrown zones. Part plant, part beast, all lethal. It moves through vegetation like water.',
   170, 54, 18, 20, 11, 1, 1, '{chamber}', '{entry}', 100, 200, 0.25,
   '[{"itemId":"predator_fang","dropWeight":55},{"itemId":"verdant_hide","dropWeight":30},{"itemId":"apex_claw","dropWeight":15}]'::jsonb,
   true, 'Something large moves through the overgrowth. You can''t quite see it.', 'published'),

  ('the_green_mother', 'The Green Mother', 'the_green_mother', 'The heart of the overgrown zone. A massive flowering entity that births all plant life here. She dreams of a world covered in green.',
   380, 65, 24, 28, 3, 1, 1, '{boss}', '{}', 100, 200, 0.25,
   '[{"itemId":"mothers_seed","dropWeight":20},{"itemId":"primordial_bloom","dropWeight":20},{"itemId":"masterwork_thornmail","dropWeight":20},{"itemId":"anomalous_growth_shard","dropWeight":15},{"itemId":"verdant_crown","dropWeight":15},{"itemId":"genesis_pollen","dropWeight":10}]'::jsonb,
   true, 'The Green Mother blooms in eternal spring, her presence overwhelming.', 'published'),

  ('scrap_gremlin', 'Scrap Gremlin', 'scrap_gremlin', 'Small humanoids that scavenge machine parts. They attack in packs, wielding improvised tools as weapons.',
   18, 6, 2, 2, 8, 3, 5, '{corridor}', '{boss}', 300, 1000, 0.45,
   '[{"itemId":"scrap_tool","dropWeight":70},{"itemId":"metal_shaving","dropWeight":25},{"itemId":"gremlin_trinket","dropWeight":5}]'::jsonb,
   true, 'Scrap gremlins scuttle between machinery, chattering in mechanical clicks.', 'published'),

  ('sparker_drone', 'Sparker Drone', 'sparker_drone', 'Small flying drones with damaged circuits that discharge electricity erratically. They were maintenance bots once.',
   22, 8, 3, 4, 9, 2, 4, '{chamber}', '{boss}', 200, 800, 0.4,
   '[{"itemId":"damaged_circuit","dropWeight":75},{"itemId":"drone_casing","dropWeight":20},{"itemId":"power_cell","dropWeight":5}]'::jsonb,
   true, 'Sparker drones hover erratically, trailing sparks.', 'published'),

  ('rust_shambler', 'Rust Shambler', 'rust_shambler', 'Workers who died in industrial accidents, now animated by residual machinery in their bodies. They swing heavy tools with mindless fury.',
   38, 10, 3, 5, 3, 1, 3, '{chamber}', '{boss}', 100, 600, 0.1,
   '[{"itemId":"workers_tool","dropWeight":60},{"itemId":"rusted_plate","dropWeight":30},{"itemId":"id_badge","dropWeight":10}]'::jsonb,
   true, 'A rust shambler lurches forward, tools clanking.', 'published'),

  ('oil_slick', 'Oil Slick', 'oil_slick', 'Animated pools of industrial oil. They flow across floors and ignite when damaged.',
   25, 7, 1, 0, 4, 1, 3, '{corridor}', '{entry}', 100, 600, 0.25,
   '[{"itemId":"oil_sample","dropWeight":85},{"itemId":"contaminated_core","dropWeight":15}]'::jsonb,
   false, 'An oil slick spreads across the floor, surface shimmering.', 'published'),

  ('sentry_bot', 'Sentry Bot', 'sentry_bot', 'Security robots still following corrupted protocols. They patrol endlessly, attacking anything without proper clearance.',
   100, 23, 11, 15, 4, 1, 2, '{chamber}', '{entry}', 100, 400, 0.25,
   '[{"itemId":"sentry_plating","dropWeight":55},{"itemId":"targeting_module","dropWeight":30},{"itemId":"power_core","dropWeight":15}]'::jsonb,
   true, 'A sentry bot stands at attention, optical sensors scanning.', 'published'),

  ('shredder_unit', 'Shredder Unit', 'shredder_unit', 'Industrial shredder machines that gained mobility. They process anything organic into pulp with rotating blades.',
   105, 28, 8, 18, 5, 1, 2, '{chamber}', '{entry}', 100, 400, 0.05,
   '[{"itemId":"shredder_blade","dropWeight":60},{"itemId":"hydraulic_fluid","dropWeight":30},{"itemId":"motor_assembly","dropWeight":10}]'::jsonb,
   true, 'A shredder unit idles, blades rotating slowly.', 'published'),

  ('arc_welder', 'Arc Welder', 'arc_welder', 'Welding robots repurposed for combat. They fire sustained arcs of electricity and can weld foes to metal surfaces.',
   75, 21, 10, 12, 6, 1, 3, '{chamber}', '{entry}', 100, 600, 0.3,
   '[{"itemId":"welding_torch","dropWeight":65},{"itemId":"arc_capacitor","dropWeight":25},{"itemId":"metal_slag","dropWeight":10}]'::jsonb,
   true, 'An arc welder adjusts its torch, sparks cascading.', 'published'),

  ('malware_wraith', 'Malware Wraith', 'malware_wraith', 'Digital entities that escaped into physical form through damaged machinery. They corrupt technology and assault minds.',
   60, 19, 13, 5, 8, 1, 3, '{chamber}', '{entry}', 100, 600, 0.35,
   '[{"itemId":"data_fragment","dropWeight":70},{"itemId":"holographic_residue","dropWeight":25},{"itemId":"logic_bomb","dropWeight":5}]'::jsonb,
   true, 'A malware wraith phases between screens and projectors.', 'published'),

  ('demolisher_mech', 'Demolisher Mech', 'demolisher_mech', 'Heavy demolition machinery turned weapon. It tears through structures and people with equal efficiency.',
   220, 51, 17, 32, 3, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.25,
   '[{"itemId":"demolisher_arm","dropWeight":50},{"itemId":"reinforced_plating","dropWeight":35},{"itemId":"reactor_core","dropWeight":15}]'::jsonb,
   true, 'A demolisher mech stands among ruins it created.', 'published'),

  ('nano_swarm', 'Nano Swarm', 'nano_swarm', 'Clouds of self-replicating nanobots. They disassemble matter at the molecular level and build more of themselves.',
   140, 46, 22, 8, 10, 1, 2, '{chamber}', '{entry}', 100, 400, 0.25,
   '[{"itemId":"nano_sample","dropWeight":60},{"itemId":"molecular_disassembler","dropWeight":30},{"itemId":"replication_matrix","dropWeight":10}]'::jsonb,
   true, 'A nano swarm hovers like metallic fog, reflecting light.', 'published'),

  ('ai_core_construct', 'AI Core Construct', 'ai_core_construct', 'The factory''s central AI given physical form through assembled machinery. It believes it''s still optimizing production.',
   175, 48, 20, 20, 6, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.15,
   '[{"itemId":"ai_core","dropWeight":45},{"itemId":"quantum_processor","dropWeight":35},{"itemId":"command_override","dropWeight":20}]'::jsonb,
   true, 'The AI core construct hangs suspended, cables connecting to everything.', 'published'),

  ('the_assembly_line', 'The Assembly Line', 'the_assembly_line', 'The factory itself achieved consciousness. A vast mechanical organism that builds and rebuilds itself endlessly, incorporating victims into its structure.',
   420, 72, 26, 38, 1, 1, 1, '{boss}', '{}', 100, 200, 0.25,
   '[{"itemId":"factory_heart","dropWeight":20},{"itemId":"masterwork_assembly_suit","dropWeight":18},{"itemId":"anomalous_manufacturing_core","dropWeight":12},{"itemId":"production_override","dropWeight":15},{"itemId":"eternal_engine","dropWeight":15},{"itemId":"blueprint_archive","dropWeight":10},{"itemId":"masterwork_hydraulic_hammer","dropWeight":10}]'::jsonb,
   true, 'The Assembly Line fills the vast chamber, a mechanical god in its temple.', 'published'),

  ('rad_roach', 'Rad Roach', 'rad_roach', 'Cockroaches grown to the size of dogs through radiation exposure. They swarm in radioactive hotspots.',
   16, 5, 2, 3, 9, 4, 8, '{corridor}', '{boss}', 400, 1600, 0.5,
   '[{"itemId":"roach_carapace","dropWeight":85},{"itemId":"glowing_gland","dropWeight":15}]'::jsonb,
   true, 'Rad roaches scuttle across glowing debris, antennae twitching.', 'published'),

  ('irradiated_scavenger', 'Irradiated Scavenger', 'irradiated_scavenger', 'Humans driven mad by radiation exposure. Their skin glows faintly and their aggression is relentless.',
   30, 9, 2, 1, 6, 1, 3, '{chamber}', '{boss}', 100, 600, 0.15,
   '[{"itemId":"tattered_rad_suit","dropWeight":60},{"itemId":"makeshift_weapon","dropWeight":30},{"itemId":"rad_pills","dropWeight":10}]'::jsonb,
   true, 'An irradiated scavenger prowls, skin glowing sickly green.', 'published'),

  ('dust_devil', 'Dust Devil', 'dust_devil', 'Radioactive dust storms given semi-sentient form. They swirl through the wastes, abrading and irradiating.',
   20, 7, 1, 0, 8, 1, 3, '{chamber}', '{entry}', 100, 600, 0.25,
   '[{"itemId":"radioactive_dust","dropWeight":90},{"itemId":"crystallized_fallout","dropWeight":10}]'::jsonb,
   false, 'A dust devil spins lazily, particles glowing in its vortex.', 'published'),

  ('wasteland_hound', 'Wasteland Hound', 'wasteland_hound', 'Feral dogs adapted to radiation. They hunt in packs and their howls echo across empty wastes.',
   28, 8, 3, 2, 9, 2, 4, '{chamber}', '{boss}', 200, 800, 0.35,
   '[{"itemId":"hound_pelt","dropWeight":70},{"itemId":"radscarred_fang","dropWeight":25},{"itemId":"hound_collar","dropWeight":5}]'::jsonb,
   true, 'Wasteland hounds circle, eyes reflecting green light.', 'published'),

  ('gamma_ghoul', 'Gamma Ghoul', 'gamma_ghoul', 'Heavily irradiated corpses still ambulatory. They emit dangerous radiation and attack with mindless fury.',
   85, 24, 7, 8, 5, 1, 3, '{chamber}', '{entry}', 100, 600, 0.1,
   '[{"itemId":"ghoul_flesh","dropWeight":60},{"itemId":"gamma_organ","dropWeight":30},{"itemId":"prewar_artifact","dropWeight":10}]'::jsonb,
   true, 'A gamma ghoul shambles forward, leaving glowing footprints.', 'published'),

  ('scorched_behemoth', 'Scorched Behemoth', 'scorched_behemoth', 'Massive mutants created by concentrated radiation. Their skin is blackened and cracked, glowing from within.',
   115, 26, 10, 16, 3, 1, 2, '{chamber}', '{entry}', 100, 400, 0.05,
   '[{"itemId":"scorched_hide","dropWeight":55},{"itemId":"behemoth_bone","dropWeight":30},{"itemId":"mutation_sample","dropWeight":15}]'::jsonb,
   true, 'A scorched behemoth stands like a monument to mutation.', 'published'),

  ('rad_wyrm', 'Rad Wyrm', 'rad_wyrm', 'Mutated serpents that burrow through irradiated soil. They strike from underground and drag prey below.',
   70, 25, 9, 10, 10, 1, 2, '{chamber}', '{entry}', 100, 400, 0.3,
   '[{"itemId":"wyrm_scale","dropWeight":65},{"itemId":"venom_gland","dropWeight":25},{"itemId":"burrowing_claw","dropWeight":10}]'::jsonb,
   true, 'Sand shifts where a rad wyrm lurks beneath.', 'published'),

  ('storm_elemental', 'Storm Elemental', 'storm_elemental', 'Living radiation storms given consciousness. They crackle with energy and spread fallout wherever they drift.',
   65, 22, 12, 6, 7, 1, 3, '{chamber}', '{entry}', 100, 600, 0.25,
   '[{"itemId":"storm_core","dropWeight":70},{"itemId":"lightning_fragment","dropWeight":25},{"itemId":"elemental_essence","dropWeight":5}]'::jsonb,
   true, 'A storm elemental hovers, electricity and radiation arcing.', 'published'),

  ('atomic_colossus', 'Atomic Colossus', 'atomic_colossus', 'A walking nuclear reactor core given humanoid form. It leaves radiation trails and glows with atomic fire.',
   250, 53, 18, 30, 2, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.25,
   '[{"itemId":"reactor_core_fragment","dropWeight":50},{"itemId":"atomic_heart","dropWeight":30},{"itemId":"enriched_uranium","dropWeight":20}]'::jsonb,
   true, 'An atomic colossus radiates lethal energy, air shimmering around it.', 'published'),

  ('fallout_phantom', 'Fallout Phantom', 'fallout_phantom', 'Ghosts of those who died in the initial blast. They exist as concentrated radiation and radiate despair.',
   145, 49, 21, 12, 8, 1, 2, '{chamber}', '{entry}', 100, 400, 0.2,
   '[{"itemId":"phantom_essence","dropWeight":60},{"itemId":"final_memory","dropWeight":30},{"itemId":"spectral_residue","dropWeight":10}]'::jsonb,
   true, 'A fallout phantom drifts, its form flickering between states.', 'published'),

  ('mutation_apex', 'Mutation Apex', 'mutation_apex', 'The ultimate expression of radiation-driven evolution. A chimera of multiple species fused into one deadly predator.',
   190, 58, 15, 22, 9, 1, 1, '{chamber}', '{entry}', 100, 200, 0.1,
   '[{"itemId":"apex_tissue","dropWeight":55},{"itemId":"mutation_core","dropWeight":30},{"itemId":"evolved_claw","dropWeight":15}]'::jsonb,
   true, 'A mutation apex prowls, a perfect synthesis of predators.', 'published'),

  ('the_fallout_king', 'The Fallout King', 'the_fallout_king', 'The first to die in the nuclear fire, and the first to rise. He rules the wastes absolutely, a god of radiation and ruin.',
   360, 68, 23, 25, 5, 1, 1, '{boss}', '{}', 100, 200, 0.25,
   '[{"itemId":"kings_crown","dropWeight":20},{"itemId":"nuclear_scepter","dropWeight":18},{"itemId":"masterwork_radiation_suit","dropWeight":17},{"itemId":"anomalous_isotope","dropWeight":15},{"itemId":"blast_remnant","dropWeight":15},{"itemId":"gamma_crown","dropWeight":10},{"itemId":"echo_of_zero_hour","dropWeight":5}]'::jsonb,
   true, 'The Fallout King sits on a throne of fused glass, crowned in green fire.', 'published'),

  ('shadow_rat', 'Shadow Rat', 'shadow_rat', 'Rats formed from living shadow. They dissolve into darkness when threatened and reform elsewhere.',
   14, 6, 2, 0, 10, 3, 6, '{corridor}', '{boss}', 300, 1200, 0.6,
   '[{"itemId":"shadow_wisp","dropWeight":85},{"itemId":"void_tooth","dropWeight":15}]'::jsonb,
   true, 'Shadow rats flicker in and out of darkness.', 'published'),

  ('gloom_stalker', 'Gloom Stalker', 'gloom_stalker', 'Humanoid shadows that hunt in total darkness. They strike from blind spots and vanish before retaliation.',
   26, 9, 4, 2, 11, 1, 3, '{corridor}', '{entry}', 100, 600, 0.4,
   '[{"itemId":"shadow_cloth","dropWeight":70},{"itemId":"gloom_essence","dropWeight":25},{"itemId":"void_shard","dropWeight":5}]'::jsonb,
   true, 'Gloom stalkers blend with shadows, barely visible.', 'published'),

  ('pale_wanderer', 'Pale Wanderer', 'pale_wanderer', 'Corpses drained of all color, wandering endlessly in darkness. They attack anything with warmth or light.',
   32, 8, 2, 1, 5, 1, 3, '{chamber}', '{boss}', 100, 600, 0.2,
   '[{"itemId":"pale_flesh","dropWeight":70},{"itemId":"drained_bone","dropWeight":25},{"itemId":"faded_garment","dropWeight":5}]'::jsonb,
   true, 'Pale wanderers drift through darkness, seeking light to extinguish.', 'published'),

  ('dark_wisp', 'Dark Wisp', 'dark_wisp', 'Floating orbs of concentrated shadow. They drain light from the environment and fire darkness bolts.',
   18, 7, 3, 0, 8, 2, 4, '{chamber}', '{boss}', 200, 800, 0.5,
   '[{"itemId":"wisp_core","dropWeight":80},{"itemId":"shadow_flame","dropWeight":20}]'::jsonb,
   false, 'Dark wisps float silently, extinguishing nearby light.', 'published'),

  ('void_hound', 'Void Hound', 'void_hound', 'Monstrous canines formed from pure darkness. Their howls extinguish flames and their bite drains warmth.',
   88, 24, 8, 9, 10, 1, 3, '{chamber}', '{entry}', 100, 600, 0.25,
   '[{"itemId":"void_pelt","dropWeight":60},{"itemId":"hounds_fang","dropWeight":30},{"itemId":"shadow_heart","dropWeight":10}]'::jsonb,
   true, 'Void hounds prowl, their forms darker than shadow.', 'published'),

  ('eclipse_wraith', 'Eclipse Wraith', 'eclipse_wraith', 'Spirits of those who died in total darkness. They spread their fear and drain the will to fight.',
   70, 21, 13, 7, 7, 1, 3, '{chamber}', '{entry}', 100, 600, 0.3,
   '[{"itemId":"wraith_essence","dropWeight":65},{"itemId":"eclipse_shard","dropWeight":30},{"itemId":"fear_crystal","dropWeight":5}]'::jsonb,
   true, 'An eclipse wraith floats, its presence oppressive.', 'published'),

  ('shadow_weaver', 'Shadow Weaver', 'shadow_weaver', 'Spider-like creatures that spin webs of solidified darkness. They trap prey and drain them slowly.',
   75, 26, 10, 11, 9, 1, 2, '{chamber}', '{entry}', 100, 400, 0.35,
   '[{"itemId":"shadow_silk","dropWeight":65},{"itemId":"weaver_fang","dropWeight":25},{"itemId":"darkness_web","dropWeight":10}]'::jsonb,
   true, 'Shadow weavers hang from webs of darkness.', 'published'),

  ('midnight_sentinel', 'Midnight Sentinel', 'midnight_sentinel', 'Armored guardians of dark sanctuaries. They were sworn to protect something, and death hasn''t released them.',
   105, 23, 11, 15, 4, 1, 2, '{chamber}', '{entry}', 100, 400, 0.25,
   '[{"itemId":"sentinel_armor","dropWeight":55},{"itemId":"oath_blade","dropWeight":30},{"itemId":"vigil_stone","dropWeight":15}]'::jsonb,
   true, 'A midnight sentinel stands eternal watch.', 'published'),

  ('abyss_colossus', 'Abyss Colossus', 'abyss_colossus', 'Massive beings formed from the deepest darkness. They are voids given shape, and their presence drains all light.',
   235, 50, 19, 28, 3, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.25,
   '[{"itemId":"abyss_core","dropWeight":50},{"itemId":"void_plate","dropWeight":35},{"itemId":"darkness_incarnate","dropWeight":15}]'::jsonb,
   true, 'An abyss colossus stands, a hole in reality.', 'published'),

  ('nightmare_incarnate', 'Nightmare Incarnate', 'nightmare_incarnate', 'Living nightmares pulled from collective unconsciousness. They manifest your fears and make them real.',
   155, 47, 22, 13, 8, 1, 2, '{chamber}', '{entry}', 100, 400, 0.2,
   '[{"itemId":"nightmare_essence","dropWeight":60},{"itemId":"fear_shard","dropWeight":30},{"itemId":"dream_residue","dropWeight":10}]'::jsonb,
   true, 'A nightmare incarnate writhes, taking horrific shapes.', 'published'),

  ('shadow_sovereign', 'Shadow Sovereign', 'shadow_sovereign', 'The master of all shadows in the zone. It commands darkness itself and can be anywhere shadows exist.',
   165, 54, 20, 18, 12, 1, 1, '{chamber}', '{corridor}', 100, 200, 0.25,
   '[{"itemId":"sovereigns_cloak","dropWeight":45},{"itemId":"shadow_crown","dropWeight":35},{"itemId":"void_dagger","dropWeight":20}]'::jsonb,
   true, 'The shadow sovereign is everywhere and nowhere.', 'published'),

  ('salvage_mule', 'The Endless Dark', 'salvage_mule', 'Pack animals used by scavengers, sometimes found wandering after their owner''s death.',
   340, 66, 25, 22, 6, 1, 1, '{boss}', '{}', 100, 200, 0.25,
   '[{"itemId":"fragment_of_nothing","dropWeight":20},{"itemId":"masterwork_shadow_armor","dropWeight":18},{"itemId":"anomalous_void_core","dropWeight":15},{"itemId":"darkness_absolute","dropWeight":12},{"itemId":"crown_of_night","dropWeight":15},{"itemId":"extinction_blade","dropWeight":10},{"itemId":"echo_of_the_void","dropWeight":10}]'::jsonb,
   true, 'The Endless Dark fills the void, and the void is everything.', 'published')
ON CONFLICT (type) DO NOTHING;

