-- Migration 038c: All exits for the expanded Warrens zone (101 rooms).
-- Covers: cross-zone, approach area, 7x7 slum grid, extra surface rooms,
-- surface-to-sewer vertical shafts, and the underground sewer network.
-- Designed by Laeral (Content Designer), built by Bruenor (Content Builder).
-- Idempotent: uses INSERT ... ON CONFLICT DO NOTHING so re-running is safe.
--
-- Topology revision notes (v2):
--   1. cistern-access connected to slum-r7c2 (was orphaned on surface).
--   2. sunken-square connected to slum-r1c1 west (additional surface link).
--   3. Approach loop broken into tree branches off the main spine
--      (merchants-row→gutter-run). burned-chapel/scavengers-den branch east
--      of merchants-row; blighted-courtyard/condemned-arch/ironmongers-ruin
--      branch east of gutter-run.
--   4. sluice-gate moved to slum-r5c1 west (mid-grid sewer access).
--   5. dustfall-extraction moved to dead-end off slum-r6c7 east (destination,
--      not waypoint).

-- Wipe all existing Warrens exits so this migration is the single source of truth.
-- Previous migrations (033) created exits that are now obsolete after the expansion.
DELETE FROM zone_exits
WHERE zone_id = (SELECT id FROM zones WHERE slug = 'warrens');

-- Insert all exits for the expanded Warrens zone.
INSERT INTO zone_exits (zone_id, from_room_slug, direction, to_room_slug, target_zone_slug, target_room_slug, locked, hidden)
SELECT z.id, v.from_slug, v.direction, v.to_slug,
       NULLIF(v.target_zone, ''), NULLIF(v.target_room, ''),
       v.is_locked, v.is_hidden
FROM zones z, (VALUES
  -- ── Cross-zone exit ──────────────────────────────────────────────────
  ('shattered-gate', 'west', 'shattered-gate', 'the-refuge', 'hearth', false, false),

  -- ── Approach area (surface) ─────────────────────────────────────────
  -- Main spine: shattered-gate → rubble-boulevard → collapsed-overpass
  --             → hollow-market → merchants-row → gutter-run → grid
  ('shattered-gate', 'east', 'rubble-boulevard', '', '', false, false),
  ('rubble-boulevard', 'west', 'shattered-gate', '', '', false, false),
  ('rubble-boulevard', 'east', 'collapsed-overpass', '', '', false, false),
  ('collapsed-overpass', 'west', 'rubble-boulevard', '', '', false, false),
  ('rubble-boulevard', 'up', 'overwatch-tower', '', '', false, false),
  ('overwatch-tower', 'down', 'rubble-boulevard', '', '', false, false),
  ('collapsed-overpass', 'east', 'hollow-market', '', '', false, false),
  ('hollow-market', 'west', 'collapsed-overpass', '', '', false, false),
  ('hollow-market', 'north', 'broken-sanctuary', '', '', false, false),
  ('broken-sanctuary', 'south', 'hollow-market', '', '', false, false),
  ('hollow-market', 'south', 'whispering-alley', '', '', false, false),
  ('whispering-alley', 'north', 'hollow-market', '', '', false, false),
  ('hollow-market', 'east', 'merchants-row', '', '', false, false),
  ('merchants-row', 'west', 'hollow-market', '', '', false, false),
  ('whispering-alley', 'east', 'collapsed-tenement', '', '', false, false),
  ('collapsed-tenement', 'west', 'whispering-alley', '', '', false, false),
  ('broken-sanctuary', 'east', 'sunken-square', '', '', true, false),
  ('sunken-square', 'west', 'broken-sanctuary', '', '', true, false),
  -- Branch: merchants-row east → burned-chapel → scavengers-den
  ('merchants-row', 'east', 'burned-chapel', '', '', false, false),
  ('burned-chapel', 'west', 'merchants-row', '', '', false, false),
  ('burned-chapel', 'south', 'scavengers-den', '', '', false, false),
  ('scavengers-den', 'north', 'burned-chapel', '', '', false, false),
  -- Spine continued
  ('merchants-row', 'south', 'gutter-run', '', '', false, false),
  ('gutter-run', 'north', 'merchants-row', '', '', false, false),
  -- Branch: gutter-run east → blighted-courtyard → condemned-arch → ironmongers-ruin
  ('gutter-run', 'east', 'blighted-courtyard', '', '', false, false),
  ('blighted-courtyard', 'west', 'gutter-run', '', '', false, false),
  ('blighted-courtyard', 'south', 'condemned-arch', '', '', false, false),
  ('condemned-arch', 'north', 'blighted-courtyard', '', '', false, false),
  ('condemned-arch', 'east', 'ironmongers-ruin', '', '', false, false),
  ('ironmongers-ruin', 'west', 'condemned-arch', '', '', false, false),
  -- Grid entry
  ('gutter-run', 'south', 'slum-r1c1', '', '', false, false),
  ('slum-r1c1', 'north', 'gutter-run', '', '', false, false),

  -- ── 7x7 Slum Grid — east/west ─────────────────────────────────────
  ('slum-r1c1', 'east', 'slum-r1c2', '', '', false, false),
  ('slum-r1c2', 'west', 'slum-r1c1', '', '', false, false),
  ('slum-r1c2', 'east', 'slum-r1c3', '', '', false, false),
  ('slum-r1c3', 'west', 'slum-r1c2', '', '', false, false),
  ('slum-r1c3', 'east', 'slum-r1c4', '', '', false, false),
  ('slum-r1c4', 'west', 'slum-r1c3', '', '', false, false),
  ('slum-r1c4', 'east', 'slum-r1c5', '', '', false, false),
  ('slum-r1c5', 'west', 'slum-r1c4', '', '', false, false),
  ('slum-r1c5', 'east', 'slum-r1c6', '', '', false, false),
  ('slum-r1c6', 'west', 'slum-r1c5', '', '', false, false),
  ('slum-r1c6', 'east', 'slum-r1c7', '', '', false, false),
  ('slum-r1c7', 'west', 'slum-r1c6', '', '', false, false),
  ('slum-r2c1', 'east', 'slum-r2c2', '', '', false, false),
  ('slum-r2c2', 'west', 'slum-r2c1', '', '', false, false),
  ('slum-r2c2', 'east', 'slum-r2c3', '', '', false, false),
  ('slum-r2c3', 'west', 'slum-r2c2', '', '', false, false),
  ('slum-r2c3', 'east', 'slum-r2c4', '', '', false, false),
  ('slum-r2c4', 'west', 'slum-r2c3', '', '', false, false),
  ('slum-r2c4', 'east', 'slum-r2c5', '', '', false, false),
  ('slum-r2c5', 'west', 'slum-r2c4', '', '', false, false),
  ('slum-r2c5', 'east', 'slum-r2c6', '', '', false, false),
  ('slum-r2c6', 'west', 'slum-r2c5', '', '', false, false),
  ('slum-r2c6', 'east', 'slum-r2c7', '', '', false, false),
  ('slum-r2c7', 'west', 'slum-r2c6', '', '', false, false),
  ('slum-r3c1', 'east', 'slum-r3c2', '', '', false, false),
  ('slum-r3c2', 'west', 'slum-r3c1', '', '', false, false),
  ('slum-r3c2', 'east', 'slum-r3c3', '', '', false, false),
  ('slum-r3c3', 'west', 'slum-r3c2', '', '', false, false),
  ('slum-r3c3', 'east', 'slum-r3c4', '', '', false, false),
  ('slum-r3c4', 'west', 'slum-r3c3', '', '', false, false),
  ('slum-r3c4', 'east', 'slum-r3c5', '', '', false, false),
  ('slum-r3c5', 'west', 'slum-r3c4', '', '', false, false),
  ('slum-r3c5', 'east', 'slum-r3c6', '', '', false, false),
  ('slum-r3c6', 'west', 'slum-r3c5', '', '', false, false),
  ('slum-r3c6', 'east', 'slum-r3c7', '', '', false, false),
  ('slum-r3c7', 'west', 'slum-r3c6', '', '', false, false),
  ('slum-r4c1', 'east', 'slum-r4c2', '', '', false, false),
  ('slum-r4c2', 'west', 'slum-r4c1', '', '', false, false),
  ('slum-r4c2', 'east', 'slum-r4c3', '', '', false, false),
  ('slum-r4c3', 'west', 'slum-r4c2', '', '', false, false),
  ('slum-r4c3', 'east', 'slum-r4c4', '', '', false, false),
  ('slum-r4c4', 'west', 'slum-r4c3', '', '', false, false),
  ('slum-r4c4', 'east', 'slum-r4c5', '', '', false, false),
  ('slum-r4c5', 'west', 'slum-r4c4', '', '', false, false),
  ('slum-r4c5', 'east', 'slum-r4c6', '', '', false, false),
  ('slum-r4c6', 'west', 'slum-r4c5', '', '', false, false),
  ('slum-r4c6', 'east', 'slum-r4c7', '', '', false, false),
  ('slum-r4c7', 'west', 'slum-r4c6', '', '', false, false),
  ('slum-r5c1', 'east', 'slum-r5c2', '', '', false, false),
  ('slum-r5c2', 'west', 'slum-r5c1', '', '', false, false),
  ('slum-r5c2', 'east', 'slum-r5c3', '', '', false, false),
  ('slum-r5c3', 'west', 'slum-r5c2', '', '', false, false),
  ('slum-r5c3', 'east', 'slum-r5c4', '', '', false, false),
  ('slum-r5c4', 'west', 'slum-r5c3', '', '', false, false),
  ('slum-r5c4', 'east', 'slum-r5c5', '', '', false, false),
  ('slum-r5c5', 'west', 'slum-r5c4', '', '', false, false),
  ('slum-r5c5', 'east', 'slum-r5c6', '', '', false, false),
  ('slum-r5c6', 'west', 'slum-r5c5', '', '', false, false),
  ('slum-r5c6', 'east', 'slum-r5c7', '', '', false, false),
  ('slum-r5c7', 'west', 'slum-r5c6', '', '', false, false),
  ('slum-r6c1', 'east', 'slum-r6c2', '', '', false, false),
  ('slum-r6c2', 'west', 'slum-r6c1', '', '', false, false),
  ('slum-r6c2', 'east', 'slum-r6c3', '', '', false, false),
  ('slum-r6c3', 'west', 'slum-r6c2', '', '', false, false),
  ('slum-r6c3', 'east', 'slum-r6c4', '', '', false, false),
  ('slum-r6c4', 'west', 'slum-r6c3', '', '', false, false),
  ('slum-r6c4', 'east', 'slum-r6c5', '', '', false, false),
  ('slum-r6c5', 'west', 'slum-r6c4', '', '', false, false),
  ('slum-r6c5', 'east', 'slum-r6c6', '', '', false, false),
  ('slum-r6c6', 'west', 'slum-r6c5', '', '', false, false),
  ('slum-r6c6', 'east', 'slum-r6c7', '', '', false, false),
  ('slum-r6c7', 'west', 'slum-r6c6', '', '', false, false),
  ('slum-r7c1', 'east', 'slum-r7c2', '', '', false, false),
  ('slum-r7c2', 'west', 'slum-r7c1', '', '', false, false),
  ('slum-r7c2', 'east', 'slum-r7c3', '', '', false, false),
  ('slum-r7c3', 'west', 'slum-r7c2', '', '', false, false),
  ('slum-r7c3', 'east', 'slum-r7c4', '', '', false, false),
  ('slum-r7c4', 'west', 'slum-r7c3', '', '', false, false),
  ('slum-r7c4', 'east', 'slum-r7c5', '', '', false, false),
  ('slum-r7c5', 'west', 'slum-r7c4', '', '', false, false),
  ('slum-r7c5', 'east', 'slum-r7c6', '', '', false, false),
  ('slum-r7c6', 'west', 'slum-r7c5', '', '', false, false),
  ('slum-r7c6', 'east', 'slum-r7c7', '', '', false, false),
  ('slum-r7c7', 'west', 'slum-r7c6', '', '', false, false),

  -- ── 7x7 Slum Grid — north/south ──────────────────────────────────
  ('slum-r1c1', 'south', 'slum-r2c1', '', '', false, false),
  ('slum-r2c1', 'north', 'slum-r1c1', '', '', false, false),
  ('slum-r1c2', 'south', 'slum-r2c2', '', '', false, false),
  ('slum-r2c2', 'north', 'slum-r1c2', '', '', false, false),
  ('slum-r1c3', 'south', 'slum-r2c3', '', '', false, false),
  ('slum-r2c3', 'north', 'slum-r1c3', '', '', false, false),
  ('slum-r1c4', 'south', 'slum-r2c4', '', '', false, false),
  ('slum-r2c4', 'north', 'slum-r1c4', '', '', false, false),
  ('slum-r1c5', 'south', 'slum-r2c5', '', '', false, false),
  ('slum-r2c5', 'north', 'slum-r1c5', '', '', false, false),
  ('slum-r1c6', 'south', 'slum-r2c6', '', '', false, false),
  ('slum-r2c6', 'north', 'slum-r1c6', '', '', false, false),
  ('slum-r1c7', 'south', 'slum-r2c7', '', '', false, false),
  ('slum-r2c7', 'north', 'slum-r1c7', '', '', false, false),
  ('slum-r2c1', 'south', 'slum-r3c1', '', '', false, false),
  ('slum-r3c1', 'north', 'slum-r2c1', '', '', false, false),
  ('slum-r2c2', 'south', 'slum-r3c2', '', '', false, false),
  ('slum-r3c2', 'north', 'slum-r2c2', '', '', false, false),
  ('slum-r2c3', 'south', 'slum-r3c3', '', '', false, false),
  ('slum-r3c3', 'north', 'slum-r2c3', '', '', false, false),
  ('slum-r2c4', 'south', 'slum-r3c4', '', '', false, false),
  ('slum-r3c4', 'north', 'slum-r2c4', '', '', false, false),
  ('slum-r2c5', 'south', 'slum-r3c5', '', '', false, false),
  ('slum-r3c5', 'north', 'slum-r2c5', '', '', false, false),
  ('slum-r2c6', 'south', 'slum-r3c6', '', '', false, false),
  ('slum-r3c6', 'north', 'slum-r2c6', '', '', false, false),
  ('slum-r2c7', 'south', 'slum-r3c7', '', '', false, false),
  ('slum-r3c7', 'north', 'slum-r2c7', '', '', false, false),
  ('slum-r3c1', 'south', 'slum-r4c1', '', '', false, false),
  ('slum-r4c1', 'north', 'slum-r3c1', '', '', false, false),
  ('slum-r3c2', 'south', 'slum-r4c2', '', '', false, false),
  ('slum-r4c2', 'north', 'slum-r3c2', '', '', false, false),
  ('slum-r3c3', 'south', 'slum-r4c3', '', '', false, false),
  ('slum-r4c3', 'north', 'slum-r3c3', '', '', false, false),
  ('slum-r3c4', 'south', 'slum-r4c4', '', '', false, false),
  ('slum-r4c4', 'north', 'slum-r3c4', '', '', false, false),
  ('slum-r3c5', 'south', 'slum-r4c5', '', '', false, false),
  ('slum-r4c5', 'north', 'slum-r3c5', '', '', false, false),
  ('slum-r3c6', 'south', 'slum-r4c6', '', '', false, false),
  ('slum-r4c6', 'north', 'slum-r3c6', '', '', false, false),
  ('slum-r3c7', 'south', 'slum-r4c7', '', '', false, false),
  ('slum-r4c7', 'north', 'slum-r3c7', '', '', false, false),
  ('slum-r4c1', 'south', 'slum-r5c1', '', '', false, false),
  ('slum-r5c1', 'north', 'slum-r4c1', '', '', false, false),
  ('slum-r4c2', 'south', 'slum-r5c2', '', '', false, false),
  ('slum-r5c2', 'north', 'slum-r4c2', '', '', false, false),
  ('slum-r4c3', 'south', 'slum-r5c3', '', '', false, false),
  ('slum-r5c3', 'north', 'slum-r4c3', '', '', false, false),
  ('slum-r4c4', 'south', 'slum-r5c4', '', '', false, false),
  ('slum-r5c4', 'north', 'slum-r4c4', '', '', false, false),
  ('slum-r4c5', 'south', 'slum-r5c5', '', '', false, false),
  ('slum-r5c5', 'north', 'slum-r4c5', '', '', false, false),
  ('slum-r4c6', 'south', 'slum-r5c6', '', '', false, false),
  ('slum-r5c6', 'north', 'slum-r4c6', '', '', false, false),
  ('slum-r4c7', 'south', 'slum-r5c7', '', '', false, false),
  ('slum-r5c7', 'north', 'slum-r4c7', '', '', false, false),
  ('slum-r5c1', 'south', 'slum-r6c1', '', '', false, false),
  ('slum-r6c1', 'north', 'slum-r5c1', '', '', false, false),
  ('slum-r5c2', 'south', 'slum-r6c2', '', '', false, false),
  ('slum-r6c2', 'north', 'slum-r5c2', '', '', false, false),
  ('slum-r5c3', 'south', 'slum-r6c3', '', '', false, false),
  ('slum-r6c3', 'north', 'slum-r5c3', '', '', false, false),
  ('slum-r5c4', 'south', 'slum-r6c4', '', '', false, false),
  ('slum-r6c4', 'north', 'slum-r5c4', '', '', false, false),
  ('slum-r5c5', 'south', 'slum-r6c5', '', '', false, false),
  ('slum-r6c5', 'north', 'slum-r5c5', '', '', false, false),
  ('slum-r5c6', 'south', 'slum-r6c6', '', '', false, false),
  ('slum-r6c6', 'north', 'slum-r5c6', '', '', false, false),
  ('slum-r5c7', 'south', 'slum-r6c7', '', '', false, false),
  ('slum-r6c7', 'north', 'slum-r5c7', '', '', false, false),
  ('slum-r6c1', 'south', 'slum-r7c1', '', '', false, false),
  ('slum-r7c1', 'north', 'slum-r6c1', '', '', false, false),
  ('slum-r6c2', 'south', 'slum-r7c2', '', '', false, false),
  ('slum-r7c2', 'north', 'slum-r6c2', '', '', false, false),
  ('slum-r6c3', 'south', 'slum-r7c3', '', '', false, false),
  ('slum-r7c3', 'north', 'slum-r6c3', '', '', false, false),
  ('slum-r6c4', 'south', 'slum-r7c4', '', '', false, false),
  ('slum-r7c4', 'north', 'slum-r6c4', '', '', false, false),
  ('slum-r6c5', 'south', 'slum-r7c5', '', '', false, false),
  ('slum-r7c5', 'north', 'slum-r6c5', '', '', false, false),
  ('slum-r6c6', 'south', 'slum-r7c6', '', '', false, false),
  ('slum-r7c6', 'north', 'slum-r6c6', '', '', false, false),
  ('slum-r6c7', 'south', 'slum-r7c7', '', '', false, false),
  ('slum-r7c7', 'north', 'slum-r6c7', '', '', false, false),

  -- ── Grid edge → extra surface rooms ──────────────────────────────
  -- NW corner: sunken-square (sewer shaft access via the-ratways)
  ('slum-r1c1', 'west', 'sunken-square', '', '', false, false),
  ('sunken-square', 'east', 'slum-r1c1', '', '', false, false),
  -- N edge: gutter-bridge (dead-end lookout)
  ('slum-r1c4', 'north', 'gutter-bridge', '', '', false, false),
  ('gutter-bridge', 'south', 'slum-r1c4', '', '', false, false),
  -- NE corner: gallows-square → tilted-tower
  ('slum-r1c7', 'east', 'gallows-square', '', '', false, false),
  ('gallows-square', 'west', 'slum-r1c7', '', '', false, false),
  ('gallows-square', 'east', 'tilted-tower', '', '', false, false),
  ('tilted-tower', 'west', 'gallows-square', '', '', false, false),
  -- W edge mid: plague-ward
  ('slum-r4c1', 'west', 'plague-ward', '', '', false, false),
  ('plague-ward', 'east', 'slum-r4c1', '', '', false, false),
  -- E edge mid: rubble-maze → watchmens-post
  ('slum-r4c7', 'east', 'rubble-maze', '', '', false, false),
  ('rubble-maze', 'west', 'slum-r4c7', '', '', false, false),
  ('rubble-maze', 'east', 'watchmens-post', '', '', false, false),
  ('watchmens-post', 'west', 'rubble-maze', '', '', false, false),
  -- W edge mid-low: sluice-gate (sewer access via sewer-main-junction)
  ('slum-r5c1', 'west', 'sluice-gate', '', '', false, false),
  ('sluice-gate', 'east', 'slum-r5c1', '', '', false, false),
  -- E edge low: dustfall-extraction (zone extraction destination)
  ('slum-r6c7', 'east', 'dustfall-extraction', '', '', false, false),
  ('dustfall-extraction', 'west', 'slum-r6c7', '', '', false, false),
  -- SW corner: dyers-vats → beggar-kings-throne
  ('slum-r7c1', 'south', 'dyers-vats', '', '', false, false),
  ('dyers-vats', 'north', 'slum-r7c1', '', '', false, false),
  ('dyers-vats', 'west', 'beggar-kings-throne', '', '', false, false),
  ('beggar-kings-throne', 'east', 'dyers-vats', '', '', false, false),
  -- S edge: cistern-access (sewer access via sewer-cistern)
  ('slum-r7c2', 'south', 'cistern-access', '', '', false, false),
  ('cistern-access', 'north', 'slum-r7c2', '', '', false, false),
  -- S edge mid: ashfall-gardens (dead-end exploration)
  ('slum-r7c4', 'south', 'ashfall-gardens', '', '', false, false),
  ('ashfall-gardens', 'north', 'slum-r7c4', '', '', false, false),
  -- SE corner: tannery-ruins → blind-alley
  ('slum-r7c7', 'south', 'tannery-ruins', '', '', false, false),
  ('tannery-ruins', 'north', 'slum-r7c7', '', '', false, false),
  ('tannery-ruins', 'east', 'blind-alley', '', '', false, false),
  ('blind-alley', 'west', 'tannery-ruins', '', '', false, false),

  -- ── Surface → sewer vertical shafts ──────────────────────────────
  ('sunken-square', 'down', 'the-ratways', '', '', false, true),
  ('the-ratways', 'up', 'sunken-square', '', '', false, false),
  ('sluice-gate', 'down', 'sewer-main-junction', '', '', false, false),
  ('sewer-main-junction', 'up', 'sluice-gate', '', '', false, false),
  ('cistern-access', 'down', 'sewer-cistern', '', '', false, false),
  ('sewer-cistern', 'up', 'cistern-access', '', '', false, false),

  -- ── Sewer internal network ────────────────────────────────────────
  ('the-ratways', 'east', 'sewer-main-junction', '', '', false, false),
  ('sewer-main-junction', 'west', 'the-ratways', '', '', false, false),
  ('the-ratways', 'south', 'charnel-pit', '', '', false, false),
  ('charnel-pit', 'north', 'the-ratways', '', '', false, false),
  ('sewer-main-junction', 'north', 'sewer-north-tunnel', '', '', false, false),
  ('sewer-north-tunnel', 'south', 'sewer-main-junction', '', '', false, false),
  ('sewer-main-junction', 'south', 'sewer-south-tunnel', '', '', false, false),
  ('sewer-south-tunnel', 'north', 'sewer-main-junction', '', '', false, false),
  ('sewer-main-junction', 'east', 'sewer-east-conduit', '', '', false, false),
  ('sewer-east-conduit', 'west', 'sewer-main-junction', '', '', false, false),
  ('sewer-north-tunnel', 'east', 'sewer-drain-grate', '', '', false, false),
  ('sewer-drain-grate', 'west', 'sewer-north-tunnel', '', '', false, false),
  ('sewer-north-tunnel', 'north', 'sewer-rat-nest', '', '', false, false),
  ('sewer-rat-nest', 'south', 'sewer-north-tunnel', '', '', false, false),
  ('sewer-rat-nest', 'east', 'sewer-bone-shelf', '', '', false, false),
  ('sewer-bone-shelf', 'west', 'sewer-rat-nest', '', '', false, false),
  ('sewer-drain-grate', 'east', 'sewer-overflow-chamber', '', '', false, false),
  ('sewer-overflow-chamber', 'west', 'sewer-drain-grate', '', '', false, false),
  ('sewer-overflow-chamber', 'south', 'sewer-east-conduit', '', '', false, false),
  ('sewer-east-conduit', 'north', 'sewer-overflow-chamber', '', '', false, false),
  ('sewer-east-conduit', 'east', 'sewer-pipe-maze', '', '', false, false),
  ('sewer-pipe-maze', 'west', 'sewer-east-conduit', '', '', false, false),
  ('sewer-pipe-maze', 'south', 'sewer-effluent-pool', '', '', false, false),
  ('sewer-effluent-pool', 'north', 'sewer-pipe-maze', '', '', false, false),
  ('sewer-pipe-maze', 'east', 'sewer-gas-pocket', '', '', false, false),
  ('sewer-gas-pocket', 'west', 'sewer-pipe-maze', '', '', false, false),
  ('sewer-south-tunnel', 'south', 'sewer-flooded-vault', '', '', false, false),
  ('sewer-flooded-vault', 'north', 'sewer-south-tunnel', '', '', false, false),
  ('sewer-south-tunnel', 'west', 'sewer-west-conduit', '', '', false, false),
  ('sewer-west-conduit', 'east', 'sewer-south-tunnel', '', '', false, false),
  ('sewer-south-tunnel', 'east', 'sewer-blackwater-crossing', '', '', false, false),
  ('sewer-blackwater-crossing', 'west', 'sewer-south-tunnel', '', '', false, false),
  ('sewer-flooded-vault', 'east', 'sewer-collapsed-drain', '', '', false, false),
  ('sewer-collapsed-drain', 'west', 'sewer-flooded-vault', '', '', false, false),
  ('sewer-blackwater-crossing', 'south', 'sewer-deep-channel', '', '', false, false),
  ('sewer-deep-channel', 'north', 'sewer-blackwater-crossing', '', '', false, false),
  ('sewer-deep-channel', 'east', 'sewer-effluent-pool', '', '', false, false),
  ('sewer-effluent-pool', 'west', 'sewer-deep-channel', '', '', false, false),
  ('sewer-deep-channel', 'west', 'sewer-silt-chamber', '', '', false, false),
  ('sewer-silt-chamber', 'east', 'sewer-deep-channel', '', '', false, false),
  ('sewer-west-conduit', 'west', 'sewer-cistern', '', '', false, false),
  ('sewer-cistern', 'east', 'sewer-west-conduit', '', '', false, false),
  ('sewer-west-conduit', 'north', 'sewer-lurker-den', '', '', false, false),
  ('sewer-lurker-den', 'south', 'sewer-west-conduit', '', '', false, false),
  ('sewer-cistern', 'north', 'sewer-fungal-grotto', '', '', false, false),
  ('sewer-fungal-grotto', 'south', 'sewer-cistern', '', '', false, false),
  ('sewer-fungal-grotto', 'east', 'sewer-lurker-den', '', '', false, false),
  ('sewer-lurker-den', 'west', 'sewer-fungal-grotto', '', '', false, false)
) AS v(from_slug, direction, to_slug, target_zone, target_room, is_locked, is_hidden)
WHERE z.slug = 'warrens'
ON CONFLICT (zone_id, from_room_slug, direction) DO NOTHING;
